/users/enseig/franck/ko6/src/soft/hal/devices/timer/clint-timer.c File Reference
#include <hal/devices/timer/clint-timer.h>
*
Functions
static void clint_timer_set_tick (struct timer_s *timer, unsigned tick)
Set the number of ticks between two CLINT timer interrupts.
static void clint_timer_init (struct timer_s *timer, unsigned address, unsigned tick)
CLINT timer initialization.
static void clint_timer_set_event (struct timer_s *timer, void(*f)(void *arg), void *arg)
Set the event that will triggered by a CLINT interrupt.
void clint_timer_isr (unsigned irq, struct timer_s *timer)
ISR of the CLINT device.
Variables
struct timer_ops_s ClintTimerOps
Function Documentation
static void clint_timer_init (struct timer_s * timer, unsigned address, unsigned tick) [static]
CLINT timer initialization.
Parameters
timer timer device to initialize
address address of the device
tick number of ticks between two interrupts
Returns
nothing
References timer_s::address, clint_timer_set_tick(), ClintTimerOps, and timer_s::ops.
{
    timer->address = address;
    timer->ops = &ClintTimerOps;
    clint_timer_set_tick(timer, tick); // next period
}
void clint_timer_isr (unsigned irq, struct timer_s * timer)
ISR of the CLINT device.
Parameters
irq irq linked to the ISR
timer device linked to the ISR
Returns
nothing
References timer_event_s::arg, timer_s::event, timer_event_s::f, timer_s::ops, timer_s::period, and timer_ops_s::timer_set_tick.
Referenced by isrcall().
{
    /* Reset timer */
    timer->ops->timer_set_tick(timer, timer->period);
    /* If a function is available, trigger the event */
    if (timer->event.f)
        timer->event.f(timer->event.arg);
}
static void clint_timer_set_event (struct timer_s * timer, void(*)(void *arg) f, void * arg) [static]
Set the event that will triggered by a CLINT interrupt.
Parameters
timer the timer device
f the function corresponding to the event
arg argument that will be passed to the function
Returns
nothing
References timer_event_s::arg, timer_s::event, and timer_event_s::f.
{
    timer->event.f = f;
    timer->event.arg = arg;
}
static void clint_timer_set_tick (struct timer_s * timer, unsigned tick) [static]
Set the number of ticks between two CLINT timer interrupts.
Parameters
timer timer device
tick number of ticks
Returns
nothing
References timer_s::address, CLINT_MTIME_OFFSET, CLINT_MTIMECMP_OFFSET, and timer_s::period.
Referenced by clint_timer_init().
{
    // We have to options: either set mtimecmp, or reset mtime
    *(unsigned*) (timer->address + CLINT_MTIMECMP_OFFSET) =
        (*(unsigned*) (timer->address + CLINT_MTIME_OFFSET)) + tick;
    timer->period = tick;
}
Variable Documentation
struct timer_ops_s ClintTimerOps
Initial value:
= {
    .timer_init = clint_timer_init,
    .timer_set_event = clint_timer_set_event,
    .timer_set_tick = clint_timer_set_tick
}
Referenced by clint_timer_init(), and soc_timer_init().