/users/enseig/franck/ko6/src/soft/external/libfdt/fdt_wip.c File Reference
#include `libfdt_env.h`
*
#include <external/libfdt/fdt.h>
*
#include <external/libfdt/libfdt.h>
*
#include `libfdt_internal.h`
*
Functions
int fdt_setprop_inplace_namelen_partial (void *fdt, int nodeoffset, const char *name, int namelen, uint32_t idx, const void *val, int len)
int fdt_setprop_inplace (void *fdt, int nodeoffset, const char *name, const void *val, int len)
static void fdt_nop_region_ (void *start, int len)
int fdt_nop_property (void *fdt, int nodeoffset, const char *name)
int fdt_node_end_offset_ (void *fdt, int offset)
int fdt_nop_node (void *fdt, int nodeoffset)
Function Documentation
int fdt_node_end_offset_ (void * fdt, int offset)
References fdt_next_node().
Referenced by fdt_del_node(), and fdt_nop_node().
{
    int depth = 0;
    while ((offset >= 0) && (depth >= 0))
        offset = fdt_next_node(fdt, offset, &depth);
    return offset;
}
int fdt_nop_node (void * fdt, int nodeoffset)
fdt_nop_node - replace a node (subtree) with nop tags : pointer to the device tree blob : offset of the node to nop
fdt_nop_node() will replace a given node's representation in the blob, including all its subnodes, if any, with FDT_NOP tags, effectively removing it from the tree.
This function will alter only the bytes in the blob which contain the node and its properties and subnodes, and will not alter or move any other part of the tree.
returns: 0, on success -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
References fdt_node_end_offset_(), fdt_nop_region_(), and fdt_offset_ptr_w().
{
    int endoffset;
    endoffset = fdt_node_end_offset_(fdt, nodeoffset);
    if (endoffset < 0)
        return endoffset;
    fdt_nop_region_(fdt_offset_ptr_w(fdt, nodeoffset, 0),
            endoffset - nodeoffset);
    return 0;
}
int fdt_nop_property (void * fdt, int nodeoffset, const char * name)
References fdt_get_property_w(), fdt_nop_region_(), and fdt_property::len.
{
    struct fdt_property *prop;
    int len;
    prop = fdt_get_property_w(fdt, nodeoffset, name, &len);
    if (!prop)
        return len;
    fdt_nop_region_(prop, len + sizeof(*prop));
    return 0;
}
static void fdt_nop_region_ (void * start, int len) [static]
References cpu_to_fdt32(), and FDT_NOP.
Referenced by fdt_nop_node(), and fdt_nop_property().
{
    fdt32_t *p;
    for (p = start; (char *)p < ((char *)start + len); p++)
        *p = cpu_to_fdt32(FDT_NOP);
}
int fdt_setprop_inplace (void * fdt, int nodeoffset, const char * name, const void * val, int len)
References FDT_ERR_NOSPACE, fdt_getprop(), fdt_setprop_inplace_namelen_partial(), and strlen().
Referenced by fdt_setprop_inplace_u32(), and fdt_setprop_inplace_u64().
{
    const void *propval;
    int proplen;
    propval = fdt_getprop(fdt, nodeoffset, name, &proplen);
    if (!propval)
        return proplen;
    if (proplen != len)
        return -FDT_ERR_NOSPACE;
    return fdt_setprop_inplace_namelen_partial(fdt, nodeoffset, name,
                           strlen(name), 0,
                           val, len);
}
int fdt_setprop_inplace_namelen_partial (void * fdt, int nodeoffset, const char * name, int namelen, uint32_t idx, const void * val, int len)
References FDT_ERR_NOSPACE, fdt_getprop_namelen_w(), and memcpy().
Referenced by fdt_setprop_inplace(), overlay_fixup_one_phandle(), and overlay_update_local_node_references().
{
    void *propval;
    int proplen;
    propval = fdt_getprop_namelen_w(fdt, nodeoffset, name, namelen,
                    &proplen);
    if (!propval)
        return proplen;
    if ((unsigned)proplen < (len + idx))
        return -FDT_ERR_NOSPACE;
    memcpy((char *)propval + idx, val, len);
    return 0;
}