/users/enseig/franck/ko6/src/soft/fs/kfs/kfs.h File Reference
Macros
#define KFS_NPG_DISK 0x2000 /* number of pages in the whole disk */
#define KFS_NPG_MBR 1 /* number of pages in MBR */
#define KFS_NPG_VBR 3 /* number of pages in VBR (bootloader) */
#define KFS_NPG_SBLOCK 2 /* number of pages in SBLOCK (contains all bitmaps) */
#define KFS_NPG_DENTRY 2 /* number of pages for all dentries */
#define KFS_NPG_INODE 2 /* number of pages for all inodes */
#define KFS_NPG_FMAP 16 /* number of pages for all file maps (inode extensions) */
#define KFS_NPG_BOOT (KFS_NPG_MBR+KFS_NPG_VBR)
#define KFS_NPG_META (KFS_NPG_SBLOCK+KFS_NPG_DENTRY+KFS_NPG_INODE+KFS_NPG_FMAP)
Enumerations
enum kfs_type_e { KFS_DIR,
KFS_FILE,
KFS_PIPE,
KFS_SLINK
 }
Functions
int kfs_root (int dentry)
read access functions to dentries
int kfs_next (int dentry)
int kfs_leaf (int dentry)
int kfs_inode (int dentry)
char * kfs_name (int dentry)
int kfs_isdir (int dentry)
boolean functions for dentries or inode
int kfs_count (int inode)
read access functions to inodes
int kfs_type (int inode)
int kfs_mode (int inode)
int kfs_size (int inode)
int kfs_owner (int inode)
int kfs_mtime (int inode)
int kfs_page (int inode, int pg_offset)
int kfs_chmode (int inode, int mode)
write access functions to inode's properties
int kfs_chowner (int inode, int owner)
int kfs_chmtime (int inode, int mtime)
int kfs_open (char *full_pathname)
opens a file or directory, if file or directory not found, all the pathname is created
int kfs_openat (int root, char *dentry_name)
looks for name in the directory root, if the name is not found, it is created
int kfs_readdir (int dentry, int leaf, void *buffer)
Reads a directory, it reads one entry from the directory dentry to memory buffer. After reading, buffer will contain the name of the directory or item.
int kfs_read (int dentry, int pg_offset, int *buffer)
Reads a file, it reads one page from the file dentry to memory buffer. After reading, buffer will contain the entire page of which the offset belongs.
int kfs_set_size (int dentry, int newsize)
Sets the size field of the inode associated with the dentry to newsize.
int kfs_write (int dentry, int pg_offset, void *buffer)
Writes one page from memory buffer to file dentry. The buffer is written on the disk in file page of which the offset belongs.
int kfs_remove (char *full_pathname)
removes a file or a directory
int kfs_unlink (char *name)
int kfs_link (char *old_name, char *new_name)
creates a new link (also called hard link) on an existing file.
int kfs_tree_cb (int root, void(*callback)(int dentry, int depth, int position))
calls the callback function on each entry from root dentry
int kfs_add_mbr (char *pathname)
Loads a 512 bytes sized MBR in kfs. Meant to be used exclusively on Linux.
int kfs_add_vbr (char *pathname)
Loads a VBR in kfs. Meant to be used exclusively on Linux.
int kfs_disk_load (char *pathname)
Loads the disk from an external support. On HOST It means from the host disk in file whose name is given in parameter. After load, the whole content of the disk is present in memory in tables KfsMbr, KfsVbr, KfsSblock, KfsDentry, KfsInode, KfsFmap & KfsDisk. On ko6 It means from the virtual disk connected to the Block Device controller. After load, only METADATA content of the disk is present in memory in tables KfsSblock, KfsDentry, KfsInode, KfsFmap.
int kfs_disk_save (char *pathname)
Saves the disk to an external support. On HOST It means to the host disk in a file whose name is given in parameter. After save, the whole content of the disk is written in file on host. That is KfsMbr, KfsVbr, KfsSblock, KfsDentry, KfsInode, KfsFmap & KfsDisk. On ko6 It means to file connected to the Block Device controller. After save only METADATA content of the disk is written to the virtual disk. That is KfsSblock, KfsDentry, KfsInode, KfsFmap.
Macro Definition Documentation
#define KFS_NPG_BOOT (KFS_NPG_MBR+KFS_NPG_VBR)
#define KFS_NPG_DENTRY 2 /* number of pages for all dentries */
#define KFS_NPG_DISK 0x2000 /* number of pages in the whole disk */
Referenced by kfs_write_page().
#define KFS_NPG_FMAP 16 /* number of pages for all file maps (inode extensions) */
#define KFS_NPG_INODE 2 /* number of pages for all inodes */
#define KFS_NPG_MBR 1 /* number of pages in MBR */
#define KFS_NPG_META (KFS_NPG_SBLOCK+KFS_NPG_DENTRY+KFS_NPG_INODE+KFS_NPG_FMAP)
#define KFS_NPG_SBLOCK 2 /* number of pages in SBLOCK (contains all bitmaps) */
#define KFS_NPG_VBR 3 /* number of pages in VBR (bootloader) */
Enumeration Type Documentation
enum kfs_type_e
Enumerator
KFS_DIR
 type of files for the real disk (less than vfs) directory
KFS_FILE
 regular file
KFS_PIPE
 named fifo not yet handled #fixme
KFS_SLINK
 symbolic link not yet handled #fixme
                {
    KFS_DIR,
    KFS_FILE,
    KFS_PIPE,
    KFS_SLINK
};
Function Documentation
int kfs_add_mbr (char * pathname)
Loads a 512 bytes sized MBR in kfs. Meant to be used exclusively on Linux.
Parameters
pathname the pathname on host to the mbr
Returns
the number of bytes read
Referenced by main().
int kfs_add_vbr (char * pathname)
Loads a VBR in kfs. Meant to be used exclusively on Linux.
Parameters
pathname the pathname on host to the vbr
Returns
the number of bytes read
Referenced by main().
int kfs_chmode (int inode, int mode)
write access functions to inode's properties
Parameters
index of an inode
mode,owner & mtime are the new property value
Returns
the new property or -1 if failure
References kfs_inode_s::mode.
{return KfsInode[inode].mode = mode; }
int kfs_chmtime (int inode, int mtime)
References kfs_inode_s::mtime.
{return KfsInode[inode].mtime= mtime;}
int kfs_chowner (int inode, int owner)
References kfs_inode_s::owner.
{return KfsInode[inode].owner= owner;}
int kfs_count (int inode)
read access functions to inodes
Parameters
index of an inode
offset is the page number in the file (start at 0 to filesize / sizeof(page))
Returns
- kfs_count : number of dentry pointing to this inode
kfs_type : type defined in kfs_enum_e
kfs_mode : permission modes rwxrwx for the owner and others (there are no groups)
kfs_size : file size
kfs_owner : file or directory owner
kfs_mtime : modification / creation relative time
kfs_page : index of page of data on the disk
References kfs_inode_s::count.
Referenced by kfs_print_dentry().
{return KfsInode[inode].count;}
int kfs_disk_load (char * pathname)
Loads the disk from an external support. On HOST It means from the host disk in file whose name is given in parameter. After load, the whole content of the disk is present in memory in tables KfsMbr, KfsVbr, KfsSblock, KfsDentry, KfsInode, KfsFmap & KfsDisk. On ko6 It means from the virtual disk connected to the Block Device controller. After load, only METADATA content of the disk is present in memory in tables KfsSblock, KfsDentry, KfsInode, KfsFmap.
Parameters
filename parameter only used by the HOST
Returns
a number > 0 on success, and <= 0 on failure
Referenced by main().
int kfs_disk_save (char * pathname)
Saves the disk to an external support. On HOST It means to the host disk in a file whose name is given in parameter. After save, the whole content of the disk is written in file on host. That is KfsMbr, KfsVbr, KfsSblock, KfsDentry, KfsInode, KfsFmap & KfsDisk. On ko6 It means to file connected to the Block Device controller. After save only METADATA content of the disk is written to the virtual disk. That is KfsSblock, KfsDentry, KfsInode, KfsFmap.
Parameters
filename parameter only used by the HOST
Returns
a number > 0 on success, and <= 0 on fealure
Referenced by main().
int kfs_inode (int dentry)
References kfs_dentry_s::inode.
Referenced by kfs_print_dentry(), kfs_print_files(), kfs_read(), kfs_set_size(), kfs_write(), and split().
{return KfsDentry[dentry].inode;}
int kfs_isdir (int dentry)
boolean functions for dentries or inode
Parameters
index of a dentry
Returns
- 0 if false, not 0 if true
References kfs_dentry_s::inode, KFS_DIR, and kfs_inode_s::type.
Referenced by kfs_readdir(), kfs_tree_cb(), and kfs_tree_cb_r().
{return KfsInode[KfsDentry[dentry].inode].type ==
      KFS_DIR;}
int kfs_leaf (int dentry)
References kfs_dentry_s::leaf.
Referenced by kfs_print_dentry().
{return KfsDentry[dentry].leaf ;}
int kfs_link (char * old_name, char * new_name)
creates a new link (also called hard link) on an existing file.
Parameters
old_name is an existing file name
new_name is the new name of the same file as old_name if new_name already exists it is not created, and it's a failure
Returns
0 if success, -1 if failure
References kfs_inode_s::count, kfs_dentry_s::inode, kfs_free_inode(), and kfs_open().
Referenced by dummy_disk().
{
    u16_t src_dentry = kfs_open (src_name);
    u16_t dst_dentry = kfs_open (dst_name);
    u16_t src_inode = KfsDentry[src_dentry].inode;
    u16_t dst_inode = KfsDentry[dst_dentry].inode;
    KfsDentry[dst_dentry].inode = src_inode;
    KfsInode[src_inode].count++;
    kfs_free_inode (dst_inode);
    return dst_dentry;
}
int kfs_mode (int inode)
References kfs_inode_s::mode.
Referenced by kfs_print_dentry().
{return KfsInode[inode].mode; }
int kfs_mtime (int inode)
References kfs_inode_s::mtime.
Referenced by kfs_print_dentry().
{return KfsInode[inode].mtime;}
char* kfs_name (int dentry)
References kfs_dentry_s::name.
Referenced by kfs_absolute_pathname(), and kfs_print_dentry().
{return KfsDentry[dentry].name ;}
int kfs_next (int dentry)
References kfs_dentry_s::next.
Referenced by kfs_print_dentry().
{return KfsDentry[dentry].next ;}
int kfs_open (char * pathname)
opens a file or directory, if file or directory not found, all the pathname is created
Parameters
pathname is the absolute name of the file or directory to find in root
Returns
dentry index of the file or directory, that is the file descriptor or -1 on failure
`deep-first walk` of the name tree to find or create the file defined by its absolute name
References kfs_dentry_s::inode, kfs_getname(), kfs_openat(), KfsOffset, and NULL.
Referenced by build(), dummy_disk(), kfs_files(), kfs_link(), kfs_tree(), kfs_unlink(), and main().
{
    char * name = kfs_getname (pathname); // get first name up to character
       '/'
    if (name == NULL) return -1; // pathname not correct, failure
    u32_t dentry = 0; // search from root fs
    while ((name = kfs_getname (NULL))) // get the next name in pathname
        dentry = kfs_openat (dentry, name); // look for it in current directory
    KfsOffset[KfsDentry[dentry].inode] = 0; // by defaut, set offset
       to firstpage
    return dentry; // finally, the last dentry found
}
int kfs_openat (int root, char * name)
looks for name in the directory root, if the name is not found, it is created
Parameters
root is a dentry index
dentry_name is the name of the file or directory to find in root
Returns
dentry index of the file, that is the file descriptor
find or create the file defined by its relative name into the directory defined by its dentry
References kfs_dentry_s::inode, kfs_alloc_dentry(), kfs_alloc_inode(), KFS_DIR, KFS_FILE, kfs_strcmp(), kfs_dentry_s::leaf, kfs_dentry_s::next, kfs_dentry_s::root, and kfs_inode_s::type.
Referenced by dummy_disk(), and kfs_open().
{
    u32_t leaf = KfsDentry[root].leaf; // get first leaf of current
       root
    int notfound = 1; // by default, suppose name not found
    KfsInode[KfsDentry[root].inode].type = KFS_DIR; // root is
       necessarily a directory
    if (leaf) { // if there are leafs
        u32_t leaf_next = KfsDentry[leaf].next; // get next leaf
        notfound = kfs_strcmp(KfsDentry[leaf].name, name); // !=0 if different
        while (notfound && leaf_next) { // while not good leaf and there is more
            leaf = leaf_next; // change the leaf to the next leaf
            leaf_next = KfsDentry[leaf].next; // get next leaf
            notfound= kfs_strcmp(KfsDentry[leaf].name,name);// compare current leaf
        }
    }
    if (notfound) {
        leaf = kfs_alloc_dentry (name); // create a new dentry for the
       file
        KfsDentry[leaf].inode = kfs_alloc_inode (
      KFS_FILE); // create an empty inode (default FILE)
        KfsDentry[leaf].leaf = 0; // if new leaf is FILE, thus no
       leaf
        KfsDentry[leaf].root = root; // set the root of the new leaf
        KfsDentry[leaf].next = KfsDentry[root].leaf; // put new leaf in
       same level nodes list
        KfsDentry[root].leaf = leaf; // the beginning of the list of
       leafs
    }
    return leaf; // return the found or created leaf
}
int kfs_owner (int inode)
References kfs_inode_s::owner.
Referenced by kfs_print_dentry().
{return KfsInode[inode].owner;}
int kfs_page (int inode, int pg_offset)
References kfs_fmap(), kfs_size(), KfsFmap, and kfs_inode_s::page.
Referenced by kfs_print_dentry(), and kfs_read().
{
    int size = kfs_size(inode); // real size of file
    if ((size==0) || (pg_offset > size>>12)) return -1; // if pg_offset is > than the nb of page
    if (pg_offset < 12) return KfsInode[inode].page[pg_offset];// page is referenced by inode
    pg_offset -= 12; // all others are in fmaps
    int map1 = kfs_fmap(inode); // get the first level
    if (size <= 28<<12) return KfsFmap[map1][pg_offset]; // if size is <= 28 pages, then 1 level
    int map2 = KfsFmap[map1][pg_offset/16]; // else get the second level
    return KfsFmap[map2][pg_offset%16]; // then get the page
}
int kfs_read (int dentry, int pg_offset, int * buf)
Reads a file, it reads one page from the file dentry to memory buffer. After reading, buffer will contain the entire page of which the offset belongs.
Parameters
dentry given by open or openat
pg_offset is the page of the file to be read, if offset == -1 then the item or page placed just after the previous one read
buffer to put the read page or filename (at least one page length)
Returns
for a file the number of pages read : 1 if success with page in buffer as a side effect, 0 if file smaller than offset, -1 if something is wrong
Try to read an entire page (4kiB) from file dentry
References kfs_inode(), kfs_page(), and kfs_read_page().
Referenced by dummy_disk(), kfs_print_files(), and split().
{
    int page = kfs_page (kfs_inode (dentry), pg_offset); // get the page number in the
       disk
    if (page == -1) return 0; // if outside of the file
    return kfs_read_page (buf, page); // at last read disk page to buf
}
int kfs_readdir (int root, int leaf, void * buf)
Reads a directory, it reads one entry from the directory dentry to memory buffer. After reading, buffer will contain the name of the directory or item.
Parameters
dentry given by open or openat
leaf is a dentry of an item present in the directory if leaf == -1 then the item is the one placed just after the previous one read
buffer to put the filename
Returns
next dentry to read or -1 if something is wrong
readdir reads all entries in a directory
References kfs_isdir(), kfs_strcpy(), kfs_dentry_s::leaf, and kfs_dentry_s::next.
Referenced by kfs_tree_cb_r().
{
    if (!kfs_isdir(root)) return -1; // root dentry must be a directory
    if (buf) kfs_strcpy (buf, KfsDentry[leaf].name); // if asked, get this leaf
       dentry name
    if (leaf == root) // at first, leaf is the root
        return KfsDentry[root].leaf; // get the first leaf thus 0 if
       empty
    if (KfsDentry[leaf].root != root) return -1; // leaf must be in root directory
    return KfsDentry[leaf].next; // find and return next leaf (0 if
       last)
}
int kfs_remove (char * full_pathname)
removes a file or a directory
Parameters
pathname is the absolute name of the file or directory to find in root
Returns
dentry index of the file or directory, that is the file descriptor or -1 on failure
int kfs_root (int dentry)
read access functions to dentries
Parameters
index of a dentry
Returns
- a dentry number for kfs_root(), kfs_next(), kfs_leaf(). For these three functions, 0 means either file system root '/' or last leaf
the inode number for kfs_inode(), there is always one
the pointer to the entry name for kfs_name()
References kfs_dentry_s::root.
Referenced by kfs_absolute_pathname(), and kfs_print_dentry().
{return KfsDentry[dentry].root ;}
int kfs_set_size (int dentry, int newsize)
Sets the size field of the inode associated with the dentry to newsize.
Parameters
dentry given by open or openat
newsize new size of the file
Returns
int : the size of the file after modification
References kfs_inode(), kfs_size(), and kfs_inode_s::size.
Referenced by add_new_file(), and dummy_disk().
{
    u16_t inode = kfs_inode(dentry); // get inode associated with the dentry
    KfsInode[inode].size = newsize; // set the new size
    return kfs_size(inode);
}
int kfs_size (int inode)
References kfs_inode_s::size.
Referenced by kfs_page(), kfs_print_dentry(), kfs_print_files(), kfs_set_size(), and split().
{return KfsInode[inode].size; }
int kfs_tree_cb (int root, void(*)(int dentry, int depth, int position) callback)
calls the callback function on each entry from root dentry
Parameters
root is the dentry for which the recursion begins
callback is a provided function which will be called on each dentry
dentry is the current entry in this directory which can be of any type
depth gives the callback() function information about the depth of the recursion. the depth of the root is 0, then the first level is 1, etc.
position is the current position in the current directory (0, 1, etc.)
Returns
the number of calls of the callback function
int kfs_type (int inode)
References kfs_inode_s::type.
Referenced by kfs_print_dentry(), kfs_print_files(), and split().
{return KfsInode[inode].type; }
int kfs_unlink (char * name)
References kfs_inode_s::fmap, kfs_dentry_s::inode, kfs_free_dentry(), kfs_free_fmap(), kfs_free_inode(), kfs_free_page(), kfs_open(), KfsFmap, kfs_inode_s::page, and kfs_inode_s::size.
{
    u16_t dentry = kfs_open (name);
    u32_t inode = KfsDentry[dentry].inode;
    u32_t size = KfsInode[inode].size;
    u32_t fmap1 = KfsInode[inode].fmap;
    u32_t fmap2 = 0;
    u32_t freemap=0;
    u16_t * ppage;
    kfs_free_dentry (dentry);
    if (KfsInode[inode].count-- == 0) {
        for (int s = size, p = 0; s > 0; s -= 1<<12, p++){
            if (p < 12) {
                ppage = &(KfsInode[inode].page[p]);
            } else if (size <= (28<<12)) {
                ppage = &(KfsFmap[fmap1][p-12]);
                if (p == size>>12) freemap=1;
            } else {
                fmap2 = KfsFmap[fmap1][(p-12)/16];
                ppage = &(KfsFmap[fmap2][(p-12)%16]);
                if ((p-12)%16 == 15) freemap=2;
                if (p == size>>12) freemap=3;
            }
            kfs_free_page (*ppage);
            if (freemap & 1) kfs_free_fmap(fmap1);
            if (freemap & 2) kfs_free_fmap(fmap2);
        }
        kfs_free_inode (inode);
    }
    return 0;
}
int kfs_write (int dentry, int pg_offset, void * buffer)
Writes one page from memory buffer to file dentry. The buffer is written on the disk in file page of which the offset belongs.
Parameters
dentry given by open or openat
pg_offset is the number of the page that will be written
buffer contains the page to write (at least one page length)
Returns
the number of pages written 1 if success with page in disk as a side effect, 0 if success but buffer was full of 0, thus no page needs to be allocated -1 if something is wrong
References kfs_alloc_page(), kfs_free_page(), kfs_inode(), kfs_ppage(), kfs_write_page(), and NULL.
Referenced by add_new_file(), and dummy_disk().
{
    u16_t inode = kfs_inode(dentry); // get inode associated with the dentry
    u16_t *ppage = kfs_ppage (inode, pg_offset); // get addr in fmaps of page number
       (alloc fmap)
    if (ppage == NULL) return -1; // NULL means no more space in fmaps
    if (*ppage == 0) *ppage = kfs_alloc_page(); // if page absent, allocate a new page
    if (*ppage == 0) return -1; // 0 means no more space on the disk
    if (kfs_write_page (buf, *ppage)) return 1; // at last write disk page from buf
    kfs_free_page (*ppage); // if returns 0, it means page full of 0
    return *ppage = 0; // erase page number in fmap;
}