/users/enseig/franck/ko6/src/soft/kernel/kmemory.h File Reference
#include <common/usermem.h>
*
Functions
void memory_init (void)
initialize all the kernel memory allocators
void * kmalloc (size_t size)
allocate an object in the kernel address space
void kfree (void *obj, size_t size)
free an allocated object with kmalloc()
void kmalloc_print (void)
Print data about slab allocator usage.
void kmalloc_test (size_t turn, size_t size)
Test Slab alocator, allocates and frees as many values as 'turn' then free all test.
int * malloc_ustack (void)
allocate a new user stack
void free_ustack (int *stack)
free a use stack
void print_ustack (void)
print ustack state
void test_ustack (size_t turn)
void * sbrk (int increment)
change the boundary of the heap
Function Documentation
void free_ustack (int * stack)
free a use stack
Parameters
stack is a pointer returned by kmalloc_ustack
References _usermem, cmp_addr(), list_addsort(), list_foreach, list_getfirst(), MAGIC_STACK, PANIC_IF, _usermem_s::ustack_end, and USTACK_SIZE.
Referenced by test_ustack().
{
    int * end = 1 + top - USTACK_SIZE/sizeof(int); // last int of ustack (+1 because
       MAGIC)
    PANIC_IF (*top != MAGIC_STACK, "Corrupted top Stack"); // if no magic number then
       panic
    PANIC_IF (*end != MAGIC_STACK, "Corrupted end Stack"); // if no magic number then
       panic
    if (end ==_usermem.ustack_end) { // if it is the lowest stack
        _usermem.ustack_end += USTACK_SIZE/sizeof(int); // shrink the
       stacks' region
        list_foreach (&FreeUserStack, stack) { // foreach free stack
            if ((int *)stack != _usermem.ustack_end) // if it isn't the end of
       stack region
                break; // then stop trying to shrink
            end = (int *)list_getfirst (&FreeUserStack); // extract the stack
            end += USTACK_SIZE/sizeof(int); // new end of stacks'region
            _usermem.ustack_end = end; // save this new end
        }
    } else // else the freed stack isn't at the end
        list_addsort (&FreeUserStack,(list_t*)end,
      cmp_addr);// add it in free list in order
}
void kfree (void * obj, size_t size)
free an allocated object with kmalloc()
Parameters
obj pointer to the allocated object
size in bytes used for allocation
References kmb, list_addfirst(), list_foreach, list_unlink(), MaxLinePage, NBLINE, NbPages, ObjectsThisSize, PAGE_SIZE, PANIC_IF, and page_s::slab.
Referenced by dev_free(), kmalloc_test(), thread_barrier_destroy(), and thread_mutex_destroy().
{
    size_t nbline= NBLINE(size) % MaxLinePage; // which slab to use
    size_t npage = (size_t)(obj - (void *)kmb)>>12; // relative page number from kmb
    PANIC_IF ((nbline>255)||(npage >= NbPages), // too big or outside of the
       region
        "\ncan't free object not allocated by kmalloc()"); // write a message then panic
    list_addfirst (&Slab[nbline], (list_t *)obj); // add it to the right
       free list
    ObjectsThisSize[nbline]--; // decr the number of obj of
       size nbline
    if (size == PAGE_SIZE) return;
    if (--Page[npage].alloc==0) { // splitted page and no more object left
        list_t *page = (list_t *)((size_t)obj & ~0xFFF); // address of the page containing
       obj
        list_foreach (&Slab[nbline], item) { // browse all item in free list
            size_t np_item = (size_t)((char*)item-kmb)>>12; // page number Page[] table
            if (np_item == npage) { // if current item is in the page
                list_unlink (item); // unlink it
            }
        }
        Page[npage].slab = 0; // since the page is empty, thus slab 0
        list_addfirst (&Slab[0], (list_t *)page); // add the free page in
       slab[O]
        ObjectsThisSize[0]--; // decr the number of pages used
    }
}
void* kmalloc (size_t size)
allocate an object in the kernel address space
Parameters
size in bytes (must be at most a PAGE SIZE)
Returns
a pointer to an object with at least `size` byte size It is rounded up to a whole number of cache lines.
References page_s::alloc, CacheLineSize, kmalloc(), kmb, list_addlast(), list_getfirst(), list_isempty(), MaxLinePage, NBLINE, ObjectsThisSize, PAGE_SIZE, PANIC_IF, page_s::slab, and wzero().
Referenced by dev_alloc(), kmalloc(), kmalloc_test(), memory_init(), ns16550_init(), soclib_tty_init(), thread_barrier_init(), thread_create(), and thread_mutex_init().
{
    PANIC_IF (size > PAGE_SIZE, // kmalloc is for small object
        "%d is too big, more than a single page", size); // write a message then panic
    PANIC_IF ((size==PAGE_SIZE) && list_isempty (&
      Slab[0]), // free page are listed in Slab[0]
        "No more kernel data space"); // write a message then panic
    size_t nbline = NBLINE(size); // required lines for size
    size = nbline * CacheLineSize; // actual size asked
    if ((size!=PAGE_SIZE) && list_isempty (&Slab[nbline])) {// if no more object
       in the slab
        char *page = kmalloc (PAGE_SIZE); // ask for a free page (i.e.
       slab)
        size_t npage = (size_t)(page - (char *)kmb)>>12; // relative page number from kmb
        Page[npage].alloc = 0; // reset the allocated counter
        for (char *p=page; p+size<=page+PAGE_SIZE; p+=size) // cut the slab into objects
            list_addlast (&Slab[nbline], (list_t *)p); // and chain them
       together
    }
    void * res = list_getfirst (&Slab[nbline%MaxLinePage]); // res is the first
       object in list
    size_t npage = (size_t)(res - (void *)kmb)>>12; // relative page number from kmb
    ObjectsThisSize[nbline%MaxLinePage]++; // increment the
       number of objects
    Page[npage].slab = nbline%MaxLinePage; // this page is used of slab
       of nbline
    Page[npage].alloc++; // one more times
    wzero (res, size); // clear allocated memory
    return res; // finally returns res
}
void kmalloc_print (void)
Print data about slab allocator usage.
for each open slab, tells the object size and how many free and allocated objects
for each page used, tells to which stab it belongs and how many objects are allocated in
References page_s::alloc, CacheLineSize, kprintf(), list_nbobj(), MaxLinePage, NbPages, ObjectsThisSize, and page_s::slab.
Referenced by kmalloc_test().
{
    size_t cr = 0, pr = 1;
    kprintf ("\nOpen Slab[] : Object Size ; Free Objects ; Allocated Objects\n");
    for (size_t nbline=0 ; nbline<MaxLinePage ; nbline++) { // for all slabs
        size_t sz = (nbline)?nbline*CacheLineSize:4096; // size really allocated
        size_t nf = list_nbobj (&Slab[nbline]); // number of free obj of size
       nline
        size_t na = ObjectsThisSize[nbline]; // number of allocated obj of
       size nline
        if (nf+na) { // if there is something to print
            kprintf ("|s %d\t f %d\t a %d", sz, nf, na); // print data
            kprintf ((++cr%3)?"\t":"\t|\n"); // adds a \n all three print
            pr=0;
        }
    }
    kprintf ((cr+pr)?"\n":""); // adds a \n if not just added it
    cr = 0; pr = 1;
    kprintf ("\nUsed Memory Pages : Slab Type (nb cache lines) ; Allocated Objects\n");
    for (size_t p = 0; p < NbPages; p++) { // for all pages
        size_t ps = Page[p].slab; // for what slab[] it is used
        size_t pa = Page[p].alloc; // how many alloc objects there are in
        if (pa) { // if the page contain allocated object
            kprintf ("|p %d\t s %d\t a %d",p,ps,pa); // print data
            kprintf ((++cr%3)?"\t":"\t|\n"); // adds a \n all three print
            pr=0;
        }
    }
    kprintf ((cr+pr)?"\n":""); // adds a \n if not just added it
}
void kmalloc_test (size_t turn, size_t size)
Test Slab alocator, allocates and frees as many values as 'turn' then free all test.
Parameters
turn is the number of allocation or release are performed
size is the maximum objects size (from 1 to PAGE_SIZE)
References CacheLineSize, kfree(), kmalloc(), kmalloc_print(), kprintf(), list_addlast(), list_foreach, list_getfirst(), list_init(), list_unlink(), MaxLinePage, NBLINE, and rand().
Referenced by memory_init().
{
    list_t *obj; // object allocated or freed
    if (turn == 0) return; // if no turn forgive now
    kprintf ("kmalloc test %s turn %d size max %d\n", // a small message
             __func__,turn,size);
    for (int i = 0 ; i < MaxLinePage ; i++) // nitialize KMallocTest
        list_init (&KMallocTest[i]); // KMallocTest[i] ->
       i*cachelinesize
    while (turn--) { // the number of turn is configurable
        int sz = 1+(rand()+CacheLineSize/2) % size; // choose a size
        size_t nbline = NBLINE(sz); // required lines for size
        nbline %= MaxLinePage; // if sz==PAGE_SIZE use Slab[0]
        if (rand()%2) { // alloc or free
            obj = kmalloc (sz); // allocate a new object
            list_addlast (&KMallocTest[nbline], obj); // add it in allocated
       object
        } else { // else
            obj = list_getfirst (&KMallocTest[nbline]); // try to get a
       previously allocated obj
            if (obj) kfree (obj, nbline*CacheLineSize); // on success, free it
        }
    }
    kmalloc_print(); // Slab status after alloc/free
       series
    for (int i = 0 ; i < MaxLinePage ; i++) { // for all list
        list_foreach (&KMallocTest[i], item) { // browse allocated
       objects
            list_unlink (item); // if found it, unlinked it
            kfree (item,i*CacheLineSize); // then free it
        }
    }
    kmalloc_print(); // Slab status after total clean
       od test
}
int* malloc_ustack (void)
allocate a new user stack
Returns
a pointer to an empty stack (of STACK_SIZE bytes) The pointer is just above the new stack
References _usermem, list_getlast(), MAGIC_STACK, NULL, PANIC_IF, _usermem_s::uheap_end, _usermem_s::ustack_end, and USTACK_SIZE.
Referenced by test_ustack(), and thread_create().
{
    int * top; // top will be the new stack pointer
    int * end = (int *)list_getlast (&FreeUserStack); // get last free stack
       (biggest addr)
    if (end == NULL) { // if there is no more free stack
        top = _usermem.ustack_end; // try to get one
        end = top - USTACK_SIZE/sizeof(int); // and compute the end of the stack
        PANIC_IF (end < _usermem.uheap_end, // if the stack end is
       in the heap
            "no more space for user stack!\n"); // it is impossible to solve that
        _usermem.ustack_end = end; // expand the stacks' region
    } else {
        top = end + USTACK_SIZE/sizeof(int); // compute stack's top from stack's
       end
    }
    top--; // get a word to put MAGIC
    *top = *end = MAGIC_STACK; // to be able to check free
    return top; // finally return the top
}
void memory_init (void)
initialize all the kernel memory allocators
References cachelinesize, CacheLineSize, CEIL, kmalloc(), kmalloc_test(), kmb, kme, list_addlast(), list_init(), MaxLinePage, NbPages, PAGE_SIZE, and PANIC_IF.
Referenced by kinit().
{
    CacheLineSize = CEIL(cachelinesize(),16); // true line
       size, but expand to 16 min
    NbPages = (kme-kmb)/PAGE_SIZE; // maximum number of
       pages
    MaxLinePage = PAGE_SIZE / CacheLineSize; // 256 when
       line is 16, 128 for 32, etc.
    PANIC_IF (NbPages*sizeof(page_t) > PAGE_SIZE, // Not more than
       2048 thus 8MB
        "kmalloc can't handled %d pages", NbPages); // write a message then panic
    list_init (&FreeUserStack); // initialize the free
       user stack list
    for (int i = 0 ; i < MaxLinePage ; i++) // initialize each list is Slab
       table
        list_init (&Slab[i]); // Slab[i] -> i*cachelinesize
       objects
    for (char *p = kmb; p != kme; p += PAGE_SIZE) // initialize the page (slab)
       list
        list_addlast (&Slab[0], (list_t *)p); // pointed by Slab[0]
    Page = kmalloc (PAGE_SIZE); // allocate the Page
       decritor table
    kmalloc_test(0,PAGE_SIZE/8);
}
void print_ustack (void)
print ustack state
References _usermem, kprintf(), list_foreach, _usermem_s::uheap_beg, _usermem_s::uheap_end, _usermem_s::ustack_beg, _usermem_s::ustack_end, and USTACK_SIZE.
Referenced by test_ustack().
{
    kprintf ("---------------\nNumber of stacks : %d\n",
            ((char *)(_usermem.ustack_beg) -
             (char *)(_usermem.ustack_end))/USTACK_SIZE);
    kprintf ("_usermem.ustack_beg : %p\n", _usermem.ustack_beg);
    kprintf ("_usermem.ustack_end : %p\n", _usermem.ustack_end);
    kprintf ("_usermem.uheap_beg : %p\n", _usermem.uheap_beg);
    kprintf ("_usermem.uheap_end : %p\n", _usermem.uheap_end);
    kprintf ("----\nFree stacks : \n");
    list_foreach (&FreeUserStack, item) {
        kprintf ("Address %p\n", item);
    }
}
void* sbrk (int increment)
change the boundary of the heap
Parameters
increment integer added to the current heap boundary
Returns
SUCCESS or FAILURE
{
    errno = SUCCESS;
    int * a = _usermem.uheap_end + increment/sizeof(int); // sizeof() because uheap_end
       is int*
    a = (int *) FLOOR (a, CacheLineSize); // addr 'a' could be the new
       uheap_end
    if ((a<_usermem.uheap_beg)||(a>_usermem.ustack_end)){ // if it is
       outside the heap zone
        errno = ENOMEM;
        return (void *)-1; // -1 on failure
    }
    return a; // else return a;
}
void test_ustack (size_t turn)
References free_ustack(), malloc_ustack(), NBSTACK, NULL, print_ustack(), and rand().
{
# define NBSTACK 10
    int * stack [NBSTACK] = {NULL};
    while (turn--) {
        int place = (unsigned)rand() % NBSTACK;
        if (stack[place])
            free_ustack (stack[place]);
        stack[place] = malloc_ustack();
    }
    for (int place = 0; place < NBSTACK; place++)
        if (stack[place])
            free_ustack (stack[place]);
    print_ustack();
}