/users/enseig/franck/ko6/src/soft/ulib/libc.h File Reference
#include <debug_off.h>
*
#include <stdarg.h>
*
#include <stddef.h>
*
#include <cstd.h>
*
#include <list.h>
*
#include <syscalls.h>
*
#include <memory.h>
*
#include <usermem.h>
*
#include <errno.h>
*
#include <esc_code.h>
*
Macros
#define VERBOSE 0
#define RAND_MAX 32767 /* maximum random value by default, must be < 0x7FFFFFFE */
#define PRINTF_MAX 256 /* largest printed message */
#define CEIL(a, b) ((int)(b)*(((int)(a)+(int)(b)-1)/(int)(b))) /* round up a aligned on b */
#define FLOOR(a, b) ((int)(b)*((int)(a)/(int)(b))) /* round down a aligned on b */
#define EXIT(n) *(char*)(0xFFFF0000+0x##n*16)=0 /* cause a panic with BAR = 0xFFFF-n-0 */
Functions
void perror (char *s)
finds the error message corresponding to the current value of the global variable errno and writes it, followed by a newline (errno is thread safe)
void exit (int status)
exit the application, thus never returns
void delay (unsigned nbcycles)
stop until a delay mesured in cycles
int read (int fd, void *buf, int count)
reads in at most count characters from fd and stores them into buf.
int write (int fd, void *buf, int count)
write in at most count characters from buf to fd.
unsigned clock (void)
clock cycle counter
size_t cachelinesize (void)
ask the processor what is the L1-cache line size
void dcache_buf_inval (void *buf, size_t size)
invalidate all lines from data L1 cache belonging to buffer buf
void dcache_inval (void *addr)
invalidate the line from data L1 cache where the addr is located
int rand (void)
random int generator
void srand (unsigned seed)
allow to define a specific random suite
int fputc (int tty, int c)
write un single char on tty
int fgetc (int tty)
reads the next character from tty and returns it cast to an int
int fgets (char *s, int size, int tty)
reads in at most size-1 characters from tty and stores them into the buffer s. Reading stops after a newline. If a newline is read, it is stored into the buffer. A terminating null byte (0) is stored after the last character in the buffer.
int fprintf (int tty, char *fmt,...)
this a simplified version which handles only: c, s, $d, x and p
Macro Definition Documentation
#define CEIL(a, b) ((int)(b)*(((int)(a)+(int)(b)-1)/(int)(b))) /* round up a aligned on b */
#define EXIT(n) *(char*)(0xFFFF0000+0x##n*16)=0 /* cause a panic with BAR = 0xFFFF-n-0 */
#define FLOOR(a, b) ((int)(b)*((int)(a)/(int)(b))) /* round down a aligned on b */
#define PRINTF_MAX 256 /* largest printed message */
#define RAND_MAX 32767 /* maximum random value by default, must be < 0x7FFFFFFE */
#define VERBOSE 0
Function Documentation
size_t cachelinesize (void)
ask the processor what is the L1-cache line size
Returns
the cache line size in bytes
ask the processor what is the L1-cache line size
Returns
the size
References SYSCALL_CACHELINESIZE, and syscall_fct.
{
    return syscall_fct (0, 0, 0, 0, SYSCALL_CACHELINESIZE);
}
unsigned clock (void)
clock cycle counter
Returns
the number of cycles from the reset
References SYSCALL_CLOCK, and syscall_fct.
{
    return syscall_fct (0, 0, 0, 0, SYSCALL_CLOCK);
}
void dcache_buf_inval (void * buf, size_t size)
invalidate all lines from data L1 cache belonging to buffer buf
Parameters
buf user buffer address
size buffer size in bytes
References SYSCALL_DCACHEBUFINVAL, and syscall_fct.
{
    syscall_fct (0, 0, 0, 0, SYSCALL_DCACHEBUFINVAL);
}
void dcache_inval (void * addr)
invalidate the line from data L1 cache where the addr is located
Parameters
addr address into the line to invalidate
References SYSCALL_DCACHEINVAL, and syscall_fct.
{
    syscall_fct (0, 0, 0, 0, SYSCALL_DCACHEINVAL);
}
void delay (unsigned nbcycles)
stop until a delay mesured in cycles
Parameters
nbcycles number of cycle to wait
References clock.
Referenced by soclib_dma_memcpy(), and soclib_tty_write().
{
    unsigned old_time, expected_time;
    old_time = clock (); // get the number od cycles at first
    expected_time = old_time + nbcycles; // compute the number of cycles to reach
    while (clock () < expected_time); // wait for expected time
}
void exit (int status)
exit the application, thus never returns
Parameters
status return value of the application
References PANIC_IF, SYSCALL_EXIT, and syscall_fct.
Referenced by _start(), free(), main(), malloc_init(), sched_insert(), and usage().
{
    PANIC_IF(true,"\n\nEXIT status = %d\n", status);
}
int fgetc (int tty)
reads the next character from tty and returns it cast to an int
Parameters
tty tty number (between 0 and TTY_MAX-1)
References read(), and write().
{
    char buf[1]; // create a buffer for the read char
    int res = read (tty, buf, 1); // ask for one char from TTY
    if (res != 1) return 0; // if no char read, should return EOF
    res = write (tty, buf, 1); // send it back to the TTY
    if (res != 1) return 0; // if no char written, should return EOF
    return (int) buf[0]; // return char read
}
int fgets (char * s, int size, int tty)
reads in at most size-1 characters from tty and stores them into the buffer s. Reading stops after a newline. If a newline is read, it is stored into the buffer. A terminating null byte (0) is stored after the last character in the buffer.
Parameters
s pointer to the buffer where the characters read will be written
size number of places in bytes in the buffer s.
tty tty number (between 0 and TTY_MAX-1) should be a FILE *
References read(), and write().
Referenced by main().
{
    // to make the backspace, we use ANSI codes : https://www.wikiwand.com/en/ANSI_escape_code
    char *DEL = "\033[D \033[D"; // move left, then write ' ' and move left
    int res = 0;
    count--; // we need to add a NUL (0) char at the end
    char c=0;
    while ((count != 0) && (c != '\n')) { // as long as we can or need to get a char
        read (tty, &c, 1); // read only 1 char
        if (c == '\n') // if c is the line feed (10)
            read (tty, &c, 1); // drop it and read the next one
        if (c == '\r') // if c is the carriage return (13)
                c = '\n'; // change it for '\n', that is what fgets waits for
        if ((c == 8)||(c == 127)) { // 8 = backspace, 127 = delete
            if (res) { // go back in the buffer if possible
                write (tty, DEL, 7); // erase current char
                count++; // count is the remaining place
                buf--; // but is the next address in buffer
                res--;
            }
            continue; // ask for another key
        } else {
            write (tty, &c, 1); // loop back to the tty
        }
        *buf = c; // write the char into the buffer
        buf++; // increments the writing pointer
        count--; // decrements the remaining space
        res++; // increments the read char
    }
    *buf = 0; // add a last 0 to end the string
    return res; // returns the number of char read
}
int fprintf (int tty, char * fmt, ...)
this a simplified version which handles only: c, s, $d, x and p
Parameters
tty tty number (between 0 and TTY_MAX-1)
fmt formated string
... variadic arguments, i.e. variable number of arguments
Returns
number of printed char
References buffer, PRINTF_MAX, vsnprintf(), and write().
Referenced by main(), malloc_print(), perror(), and t0_fun().
{
    static char buffer[PRINTF_MAX];
    int res;
    va_list ap;
    va_start (ap, fmt);
    res = vsnprintf(buffer, sizeof(buffer), fmt, ap);
    res = write(tty, buffer, res);
    va_end(ap);
    return res;
}
int fputc (int tty, int c)
write un single char on tty
Parameters
tty tty number (between 0 and TTY_MAX-1)
c char to print
Returns
the written char
References write().
{
    write (tty, &c, 1); // the char is in the least significant byte
    return c;
}
void perror (char * s)
finds the error message corresponding to the current value of the global variable errno and writes it, followed by a newline (errno is thread safe)
Parameters
s is a string written if not NULL and not empty just before the system error
References errno, errno_mess, and fprintf().
{
    if (s && *s)
        fprintf (0, "%s: %s\n", s, errno_mess[errno + 1]); // first number of errno
       is -1
    else
        fprintf (0, "%s\n", errno_mess[errno + 1]);
}
int rand (void)
random int generator
Returns
a random int between 0 and RAND_MAX
https://en.wikipedia.org/wiki/Linear_congruential_generator (glibc generator)
random int generator
Returns
a random int between 0 and RAND_MAX
References RAND_MAX, randnext, and randseed.
Referenced by kmalloc_test(), t0_fun(), and test_ustack().
{
    randseed = randseed * 1664525 + 1013904223; // Numerical Recipes
    return (randseed>>1);
}
int read (int fd, void * buf, int count)
reads in at most count characters from fd and stores them into buf.
Parameters
fd normally it is the file descriptor, but now it is just the tty number
buf pointer to the buffer
count number of bytes to read, must be lower than buf size
Returns
on success, the number of char read, else -1
References syscall_fct, and SYSCALL_READ.
Referenced by add_new_file(), fgetc(), and fgets().
{
    return syscall_fct(fd, (int)buf, count, 0, SYSCALL_READ);
}
void srand (unsigned seed)
allow to define a specific random suite
Parameters
seed any integer
References randnext, and randseed.
{
    randseed = seed;
}
int write (int fd, void * buf, int count)
write in at most count characters from buf to fd.
Parameters
fd normally it is the file descriptor, but now it is just the tty number
buf pointer to the buffer
count number of bytes to write, must be lower than buf size
Returns
on success, the number of written char, else -1
References syscall_fct, and SYSCALL_WRITE.
Referenced by fgetc(), fgets(), fprintf(), fputc(), kfs_print_files(), and split().
{
    return syscall_fct(fd, (int)buf, count, 0, SYSCALL_WRITE);
}