/users/enseig/franck/ko6/src/soft/external/libfdt/libfdt.h File Reference
#include <external/libfdt/libfdt_env.h>
*
#include <external/libfdt/fdt.h>
*
Macros
#define FDT_FIRST_SUPPORTED_VERSION 0x02
#define FDT_LAST_COMPATIBLE_VERSION 0x10
#define FDT_LAST_SUPPORTED_VERSION 0x11
#define FDT_ERR_NOTFOUND 1
#define FDT_ERR_EXISTS 2
#define FDT_ERR_NOSPACE 3
#define FDT_ERR_BADOFFSET 4
#define FDT_ERR_BADPATH 5
#define FDT_ERR_BADPHANDLE 6
#define FDT_ERR_BADSTATE 7
#define FDT_ERR_TRUNCATED 8
#define FDT_ERR_BADMAGIC 9
#define FDT_ERR_BADVERSION 10
#define FDT_ERR_BADSTRUCTURE 11
#define FDT_ERR_BADLAYOUT 12
#define FDT_ERR_INTERNAL 13
#define FDT_ERR_BADNCELLS 14
#define FDT_ERR_BADVALUE 15
#define FDT_ERR_BADOVERLAY 16
#define FDT_ERR_NOPHANDLES 17
#define FDT_ERR_BADFLAGS 18
#define FDT_ERR_ALIGNMENT 19
#define FDT_ERR_MAX 19
#define FDT_MAX_PHANDLE 0xfffffffe
#define fdt_for_each_subnode(node, fdt, parent)
#define fdt_get_header(fdt, field) (fdt32_ld(&((const struct fdt_header *)(fdt))->field))
#define fdt_magic(fdt) (fdt_get_header(fdt, magic))
#define fdt_totalsize(fdt) (fdt_get_header(fdt, totalsize))
#define fdt_off_dt_struct(fdt) (fdt_get_header(fdt, off_dt_struct))
#define fdt_off_dt_strings(fdt) (fdt_get_header(fdt, off_dt_strings))
#define fdt_off_mem_rsvmap(fdt) (fdt_get_header(fdt, off_mem_rsvmap))
#define fdt_version(fdt) (fdt_get_header(fdt, version))
#define fdt_last_comp_version(fdt) (fdt_get_header(fdt, last_comp_version))
#define fdt_boot_cpuid_phys(fdt) (fdt_get_header(fdt, boot_cpuid_phys))
#define fdt_size_dt_strings(fdt) (fdt_get_header(fdt, size_dt_strings))
#define fdt_size_dt_struct(fdt) (fdt_get_header(fdt, size_dt_struct))
#define fdt_set_hdr_(name)
Functions
const void * fdt_offset_ptr (const void *fdt, int offset, unsigned int checklen)
static void * fdt_offset_ptr_w (void *fdt, int offset, int checklen)
uint32_t fdt_next_tag (const void *fdt, int offset, int *nextoffset)
static uint16_t fdt16_ld (const fdt16_t *p)
static uint32_t fdt32_ld (const fdt32_t *p)
static void fdt32_st (void *property, uint32_t value)
static uint64_t fdt64_ld (const fdt64_t *p)
static void fdt64_st (void *property, uint64_t value)
int fdt_next_node (const void *fdt, int offset, int *depth)
int fdt_first_subnode (const void *fdt, int offset)
int fdt_next_subnode (const void *fdt, int offset)
fdt_set_hdr_ (magic)
fdt_set_hdr_ (totalsize)
fdt_set_hdr_ (off_dt_struct)
fdt_set_hdr_ (off_dt_strings)
fdt_set_hdr_ (off_mem_rsvmap)
fdt_set_hdr_ (version)
fdt_set_hdr_ (last_comp_version)
fdt_set_hdr_ (boot_cpuid_phys)
fdt_set_hdr_ (size_dt_strings)
fdt_set_hdr_ (size_dt_struct)
size_t fdt_header_size (const void *fdt)
size_t fdt_header_size_ (uint32_t version)
int fdt_check_header (const void *fdt)
int fdt_move (const void *fdt, void *buf, int bufsize)
int fdt_check_full (const void *fdt, size_t bufsize)
const char * fdt_get_string (const void *fdt, int stroffset, int *lenp)
const char * fdt_string (const void *fdt, int stroffset)
int fdt_find_max_phandle (const void *fdt, uint32_t *phandle)
static uint32_t fdt_get_max_phandle (const void *fdt)
int fdt_generate_phandle (const void *fdt, uint32_t *phandle)
int fdt_num_mem_rsv (const void *fdt)
int fdt_get_mem_rsv (const void *fdt, int n, uint64_t *address, uint64_t *size)
: name of the property to find
fdt_getprop - retrieve the value of a given property : pointer to the device tree blob : offset of the node whose property to find
: pointer to an integer variable (will be overwritten) or NULL
fdt_getprop() retrieves a pointer to the value of the property named
struct fdt_property * fdt_get_property_namelen (const void *fdt, int nodeoffset, const char *name, int namelen, int *lenp)
struct fdt_property * fdt_get_property (const void *fdt, int nodeoffset, const char *name, int *lenp)
static struct fdt_property * fdt_get_property_w (void *fdt, int nodeoffset, const char *name, int *lenp)
const void * fdt_getprop_by_offset (const void *fdt, int offset, const char **namep, int *lenp)
const void * fdt_getprop_namelen (const void *fdt, int nodeoffset, const char *name, int namelen, int *lenp)
static void * fdt_getprop_namelen_w (void *fdt, int nodeoffset, const char *name, int namelen, int *lenp)
of the node at offset @nodeoffset (this will be a
pointer to within the device blob itself, not a copy of the value). If is non-NULL, the length of the property value is also returned, in the integer pointed to by .
returns: pointer to the property's value if lenp is non-NULL, *lenp contains the length of the property value (>=0) NULL, on error if lenp is non-NULL, *lenp contains an error code (<0): -FDT_ERR_NOTFOUND, node does not have named property -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
const void * fdt_getprop (const void *fdt, int nodeoffset, const char *name, int *lenp)
static void * fdt_getprop_w (void *fdt, int nodeoffset, const char *name, int *lenp)
uint32_t fdt_get_phandle (const void *fdt, int nodeoffset)
, if it exists,
NULL otherwise
const char * fdt_get_alias_namelen (const void *fdt, const char *name, int namelen)
const char * fdt_get_symbol_namelen (const void *fdt, const char *name, int namelen)
in the node /aliases.
returns: a pointer to the expansion of the alias named 'name', if it exists NULL, if the given alias or the /aliases node does not exist
const char * fdt_get_alias (const void *fdt, const char *name)
: name of the property to change the value of
fdt_setprop_inplace_cell - change the value of a single-cell property : pointer to the device tree blob : offset of the node containing the property
: new value of the 32-bit cell
This is an alternative name for fdt_setprop_inplace_u32() Return: 0 on success, negative libfdt error number otherwise.
static int fdt_setprop_inplace_cell (void *fdt, int nodeoffset, const char *name, uint32_t val)
: name to give the node
fdt_set_name - change the name of a given node : pointer to the device tree blob : structure block offset of a node
fdt_set_name() replaces the name (including unit address, if any) of the given node with the given string. NOTE: this function can't efficiently check if the new name is unique amongst the given node's siblings; results are undefined if this function is invoked with a name equal to one of the given node's siblings.
This function may insert or delete data from the blob, and will therefore change the offsets of some existing nodes.
returns: 0, on success -FDT_ERR_NOSPACE, there is insufficient free space in the blob to contain the new name -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, standard meanings
int fdt_set_name (void *fdt, int nodeoffset, const char *name)
: name of the property to append to
fdt_appendprop - append to or create a property : pointer to the device tree blob : offset of the node whose property to change
: pointer to data to append to the property value : length of the data to append to the property value
fdt_appendprop() appends the value to the named property in the given node, creating the property if it does not already exist.
This function may insert data into the blob, and will therefore change the offsets of some existing nodes.
returns: 0, on success -FDT_ERR_NOSPACE, there is insufficient free space in the blob to contain the new property value -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADLAYOUT, -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADLAYOUT, -FDT_ERR_TRUNCATED, standard meanings
int fdt_appendprop (void *fdt, int nodeoffset, const char *name, const void *val, int len)
: name of property
fdt_appendprop_addrrange - append a address range property : pointer to the device tree blob : offset of the parent node : offset of the node to add a property at
: start address of a given range : size of a given range
fdt_appendprop_addrrange() appends an address range value (start address and size) to the value of the named property in the given node, or creates a new property with that value if it does not already exist. If `name` is not specified, a default `reg` is used. Cell sizes are determined by parent's #address-cells and #size-cells.
This function may insert data into the blob, and will therefore change the offsets of some existing nodes.
returns: 0, on success -FDT_ERR_BADLAYOUT, -FDT_ERR_BADMAGIC, -FDT_ERR_BADNCELLS, if the node has a badly formatted or invalid #address-cells property -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADVERSION, -FDT_ERR_BADVALUE, addr or size doesn't fit to respective cells size -FDT_ERR_NOSPACE, there is insufficient free space in the blob to contain a new property -FDT_ERR_TRUNCATED, standard meanings
int fdt_appendprop_addrrange (void *fdt, int parent, int nodeoffset, const char *name, uint64_t addr, uint64_t size)
as the name of the new node. This is useful for
creating subnodes based on a portion of a larger string, such as a full path.
Return: structure block offset of the created subnode (>=0), negative libfdt error value otherwise
int fdt_add_subnode_namelen (void *fdt, int parentoffset, const char *name, int namelen)
: name of the subnode to locate
fdt_add_subnode - creates a new node : pointer to the device tree blob : structure block offset of a node
fdt_add_subnode() creates a new node as a subnode of the node at structure block offset parentoffset, with the given name (which should include the unit address, if any).
This function will insert data into the blob, and will therefore change the offsets of some existing nodes.
returns: structure block offset of the created nodeequested subnode (>=0), on success -FDT_ERR_NOTFOUND, if the requested subnode does not exist -FDT_ERR_BADOFFSET, if parentoffset did not point to an FDT_BEGIN_NODE tag -FDT_ERR_EXISTS, if the node at parentoffset already has a subnode of the given name -FDT_ERR_NOSPACE, if there is insufficient free space in the blob to contain the new node -FDT_ERR_NOSPACE -FDT_ERR_BADLAYOUT -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings.
#define fdt_for_each_property_offset(property, fdt, node)
int fdt_subnode_offset_namelen (const void *fdt, int parentoffset, const char *name, int namelen)
int fdt_subnode_offset (const void *fdt, int parentoffset, const char *name)
int fdt_path_offset_namelen (const void *fdt, const char *path, int namelen)
int fdt_path_offset (const void *fdt, const char *path)
const char * fdt_get_name (const void *fdt, int nodeoffset, int *lenp)
int fdt_first_property_offset (const void *fdt, int nodeoffset)
int fdt_next_property_offset (const void *fdt, int offset)
struct fdt_property * fdt_get_property_by_offset (const void *fdt, int offset, int *lenp)
static struct fdt_property * fdt_get_property_by_offset_w (void *fdt, int offset, int *lenp)
int fdt_add_subnode (void *fdt, int parentoffset, const char *name)
int fdt_del_node (void *fdt, int nodeoffset)
int fdt_overlay_apply (void *fdt, void *fdto)
int fdt_overlay_target_offset (const void *fdt, const void *fdto, int fragment_offset, char const **pathp)
const char * fdt_strerror (int errval)
in the node
/__symbols__. Such a node exists only for a device tree blob that has been compiled with the -@ dtc option. Each property corresponds to a label appearing in the device tree source, with the name of the property being the label and the value being the full path of the node it is attached to.
returns: a pointer to the expansion of the symbol named 'name', if it exists NULL, if the given symbol or the /__symbols__ node does not exist
#define FDT_MAX_NCELLS 4
const char * fdt_get_symbol (const void *fdt, const char *name)
int fdt_get_path (const void *fdt, int nodeoffset, char *buf, int buflen)
int fdt_supernode_atdepth_offset (const void *fdt, int nodeoffset, int supernodedepth, int *nodedepth)
int fdt_node_depth (const void *fdt, int nodeoffset)
int fdt_parent_offset (const void *fdt, int nodeoffset)
int fdt_node_offset_by_prop_value (const void *fdt, int startoffset, const char *propname, const void *propval, int proplen)
int fdt_node_offset_by_phandle (const void *fdt, uint32_t phandle)
int fdt_node_check_compatible (const void *fdt, int nodeoffset, const char *compatible)
int fdt_node_offset_by_compatible (const void *fdt, int startoffset, const char *compatible)
int fdt_stringlist_contains (const char *strlist, int listlen, const char *str)
int fdt_stringlist_count (const void *fdt, int nodeoffset, const char *property)
int fdt_stringlist_search (const void *fdt, int nodeoffset, const char *property, const char *string)
const char * fdt_stringlist_get (const void *fdt, int nodeoffset, const char *property, int index, int *lenp)
int fdt_address_cells (const void *fdt, int nodeoffset)
int fdt_size_cells (const void *fdt, int nodeoffset)
: name of the property to change
fdt_appendprop_string - append a string to a property : pointer to the device tree blob : offset of the node whose property to change
: string value to append to the property
fdt_appendprop_string() appends the given string to the value of the named property in the given node, or creates a new property with that value if it does not already exist.
This function may insert data into the blob, and will therefore change the offsets of some existing nodes.
returns: 0, on success -FDT_ERR_NOSPACE, there is insufficient free space in the blob to contain the new property value -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADLAYOUT, -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADLAYOUT, -FDT_ERR_TRUNCATED, standard meanings
#define fdt_setprop_string(fdt, nodeoffset, name, str) fdt_setprop((fdt), (nodeoffset), (name), (str), strlen(str)+1)
#define fdt_setprop_empty(fdt, nodeoffset, name) fdt_setprop((fdt), (nodeoffset), (name), NULL, 0)
#define fdt_appendprop_string(fdt, nodeoffset, name, str) fdt_appendprop((fdt), (nodeoffset), (name), (str), strlen(str)+1)
int fdt_setprop_inplace_namelen_partial (void *fdt, int nodeoffset, const char *name, int namelen, uint32_t idx, const void *val, int len)
int fdt_setprop_inplace (void *fdt, int nodeoffset, const char *name, const void *val, int len)
static int fdt_setprop_inplace_u32 (void *fdt, int nodeoffset, const char *name, uint32_t val)
static int fdt_setprop_inplace_u64 (void *fdt, int nodeoffset, const char *name, uint64_t val)
int fdt_setprop (void *fdt, int nodeoffset, const char *name, const void *val, int len)
int fdt_setprop_placeholder (void *fdt, int nodeoffset, const char *name, int len, void **prop_data)
static int fdt_setprop_u32 (void *fdt, int nodeoffset, const char *name, uint32_t val)
static int fdt_setprop_u64 (void *fdt, int nodeoffset, const char *name, uint64_t val)
static int fdt_setprop_cell (void *fdt, int nodeoffset, const char *name, uint32_t val)
static int fdt_appendprop_u32 (void *fdt, int nodeoffset, const char *name, uint32_t val)
static int fdt_appendprop_u64 (void *fdt, int nodeoffset, const char *name, uint64_t val)
static int fdt_appendprop_cell (void *fdt, int nodeoffset, const char *name, uint32_t val)
: name of the property to nop
fdt_delprop - delete a property : pointer to the device tree blob : offset of the node whose property to nop
fdt_del_property() will delete the given property.
This function will delete data from the blob, and will therefore change the offsets of some existing nodes.
returns: 0, on success -FDT_ERR_NOTFOUND, node does not have the named property -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADLAYOUT, -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
#define FDT_CREATE_FLAG_NO_NAME_DEDUP 0x1
#define FDT_CREATE_FLAGS_ALL (FDT_CREATE_FLAG_NO_NAME_DEDUP)
int fdt_nop_property (void *fdt, int nodeoffset, const char *name)
int fdt_nop_node (void *fdt, int nodeoffset)
int fdt_create_with_flags (void *buf, int bufsize, uint32_t flags)
int fdt_create (void *buf, int bufsize)
int fdt_resize (void *fdt, void *buf, int bufsize)
int fdt_add_reservemap_entry (void *fdt, uint64_t addr, uint64_t size)
int fdt_finish_reservemap (void *fdt)
int fdt_begin_node (void *fdt, const char *name)
int fdt_property (void *fdt, const char *name, const void *val, int len)
static int fdt_property_u32 (void *fdt, const char *name, uint32_t val)
static int fdt_property_u64 (void *fdt, const char *name, uint64_t val)
static int fdt_property_cell (void *fdt, const char *name, uint32_t val)
int fdt_delprop (void *fdt, int nodeoffset, const char *name)
: name of property to add
fdt_property_placeholder - add a new property and return a ptr to its value
: pointer to the device tree blob
: length of property value in bytes : returns a pointer to where where the value should be placed
returns: 0, on success -FDT_ERR_BADMAGIC, -FDT_ERR_NOSPACE, standard meanings
#define fdt_property_string(fdt, name, str) fdt_property(fdt, name, str, strlen(str)+1)
int fdt_property_placeholder (void *fdt, const char *name, int len, void **valp)
int fdt_end_node (void *fdt)
int fdt_finish (void *fdt)
int fdt_create_empty_tree (void *buf, int bufsize)
int fdt_open_into (const void *fdt, void *buf, int bufsize)
int fdt_pack (void *fdt)
int fdt_add_mem_rsv (void *fdt, uint64_t address, uint64_t size)
int fdt_del_mem_rsv (void *fdt, int n)
Macro Definition Documentation
#define fdt_appendprop_string(fdt, nodeoffset, name, str) fdt_appendprop((fdt), (nodeoffset), (name), (str), strlen(str)+1)
#define fdt_boot_cpuid_phys(fdt) (fdt_get_header(fdt, boot_cpuid_phys))
Referenced by fdt_open_into().
#define FDT_CREATE_FLAG_NO_NAME_DEDUP 0x1
Referenced by fdt_property_placeholder().
#define FDT_CREATE_FLAGS_ALL (FDT_CREATE_FLAG_NO_NAME_DEDUP)
Referenced by fdt_create_with_flags().
#define FDT_ERR_ALIGNMENT 19
Referenced by fdt_check_header(), and fdt_ro_probe_().
#define FDT_ERR_BADFLAGS 18
Referenced by fdt_create_with_flags().
#define FDT_ERR_BADLAYOUT 12
Referenced by fdt_rw_probe_().
#define FDT_ERR_BADMAGIC 9
Referenced by fdt_check_header(), fdt_ro_probe_(), and fdt_sw_probe_().
#define FDT_ERR_BADNCELLS 14
Referenced by fdt_address_cells(), fdt_appendprop_addrrange(), and fdt_cells().
#define FDT_ERR_BADOFFSET 4
Referenced by fdt_check_node_offset_(), fdt_check_prop_offset_(), fdt_get_mem_rsv(), fdt_get_path(), fdt_get_string(), fdt_splice_(), and fdt_supernode_atdepth_offset().
#define FDT_ERR_BADOVERLAY 16
Referenced by fdt_overlay_target_offset(), overlay_fixup_one_phandle(), overlay_fixup_phandle(), overlay_symbol_update(), and overlay_update_local_node_references().
#define FDT_ERR_BADPATH 5
Referenced by fdt_path_offset_namelen().
#define FDT_ERR_BADPHANDLE 6
Referenced by fdt_node_offset_by_phandle(), fdt_overlay_target_offset(), and overlay_phandle_add_offset().
#define FDT_ERR_BADSTATE 7
Referenced by fdt_ro_probe_(), fdt_sw_probe_(), fdt_sw_probe_memrsv_(), and fdt_sw_probe_struct_().
#define FDT_ERR_BADSTRUCTURE 11
Referenced by fdt_check_full(), fdt_get_name(), fdt_get_path(), fdt_next_tag(), fdt_supernode_atdepth_offset(), and nextprop_().
#define FDT_ERR_BADVALUE 15
Referenced by fdt_appendprop_addrrange(), fdt_stringlist_count(), fdt_stringlist_get(), fdt_stringlist_search(), and overlay_symbol_update().
#define FDT_ERR_BADVERSION 10
Referenced by fdt_check_header(), fdt_get_property_by_offset(), fdt_get_property_namelen(), fdt_open_into(), fdt_ro_probe_(), and fdt_rw_probe_().
#define FDT_ERR_EXISTS 2
Referenced by fdt_add_subnode_namelen(), and overlay_apply_node().
#define FDT_ERR_INTERNAL 13
Referenced by fdt_add_subnode_namelen(), fdt_check_full(), fdt_get_property_namelen_(), fdt_get_string(), fdt_node_depth(), fdt_resize(), fdt_supernode_atdepth_offset(), overlay_apply_node(), and overlay_fixup_phandle().
#define FDT_ERR_MAX 19
#define FDT_ERR_NOPHANDLES 17
Referenced by fdt_generate_phandle(), and overlay_phandle_add_offset().
#define FDT_ERR_NOSPACE 3
Referenced by fdt_add_reservemap_entry(), fdt_begin_node(), fdt_create_with_flags(), fdt_end_node(), fdt_finish(), fdt_get_path(), fdt_move(), fdt_open_into(), fdt_property_placeholder(), fdt_resize(), fdt_setprop_inplace(), fdt_setprop_inplace_namelen_partial(), fdt_splice_(), and overlay_update_local_node_references().
#define FDT_ERR_NOTFOUND 1
Referenced by fdt_add_subnode_namelen(), fdt_address_cells(), fdt_del_mem_rsv(), fdt_find_max_phandle(), fdt_first_subnode(), fdt_get_path(), fdt_next_node(), fdt_next_subnode(), fdt_node_offset_by_compatible(), fdt_overlay_target_offset(), fdt_setprop_placeholder(), fdt_size_cells(), fdt_stringlist_get(), fdt_stringlist_search(), fdt_subnode_offset_namelen(), fdt_supernode_atdepth_offset(), nextprop_(), overlay_adjust_node_phandles(), overlay_apply_node(), overlay_fixup_one_phandle(), overlay_fixup_phandle(), overlay_fixup_phandles(), overlay_merge(), overlay_symbol_update(), overlay_update_local_node_references(), overlay_update_local_references(), soc_dma_init(), soc_icu_init(), soc_timer_init(), and soc_tty_init().
#define FDT_ERR_TRUNCATED 8
Referenced by fdt_check_full(), fdt_check_header(), fdt_get_string(), fdt_next_node(), fdt_next_tag(), fdt_num_mem_rsv(), and fdt_ro_probe_().
#define FDT_FIRST_SUPPORTED_VERSION 0x02
Referenced by fdt_check_header(), and fdt_ro_probe_().
#define fdt_for_each_property_offset(property, fdt, node)
Value:
for (property = fdt_first_property_offset(fdt, node); \
         property >= 0; \
         property = fdt_next_property_offset(fdt, property))
Referenced by overlay_apply_node(), overlay_fixup_phandles(), overlay_symbol_update(), and overlay_update_local_node_references().
#define fdt_for_each_subnode(node, fdt, parent)
Value:
for (node = fdt_first_subnode(fdt, parent); \
         node >= 0; \
         node = fdt_next_subnode(fdt, node))
fdt_for_each_subnode - iterate over all subnodes of a parent
: child node (int, lvalue) : FDT blob (const void *) : parent node (int)
This is actually a wrapper around a for loop and would be used like so:
fdt_for_each_subnode(node, fdt, parent) { Use node ... }
if ((node < 0) && (node != -FDT_ERR_NOTFOUND)) { Error handling }
Note that this is implemented as a macro and is used as iterator in the loop. The parent variable be constant or even a literal.
Referenced by overlay_adjust_node_phandles(), overlay_apply_node(), overlay_merge(), and overlay_update_local_node_references().
#define fdt_get_header(fdt, field) (fdt32_ld(&((const struct fdt_header *)(fdt))->field))
#define fdt_last_comp_version(fdt) (fdt_get_header(fdt, last_comp_version))
Referenced by fdt_check_header(), fdt_ro_probe_(), and sw_flags().
#define FDT_LAST_COMPATIBLE_VERSION 0x10
Referenced by fdt_finish().
#define FDT_LAST_SUPPORTED_VERSION 0x11
Referenced by fdt_check_header(), fdt_create_with_flags(), and fdt_ro_probe_().
#define fdt_magic(fdt) (fdt_get_header(fdt, magic))
Referenced by fdt_check_header(), fdt_get_string(), fdt_ro_probe_(), fdt_sw_probe_(), and soc_init().
#define FDT_MAX_NCELLS 4
FDT_MAX_NCELLS - maximum value for #address-cells and #size-cells
This is the maximum value for #address-cells, #size-cells and similar properties that will be processed by libfdt. IEE1275 requires that OF implementations handle values up to 4. Implementations may support larger values, but in practice higher values aren't used.
Referenced by fdt_cells().
#define FDT_MAX_PHANDLE 0xfffffffe
Referenced by fdt_generate_phandle().
#define fdt_off_dt_strings(fdt) (fdt_get_header(fdt, off_dt_strings))
Referenced by fdt_blocks_misordered_(), fdt_check_header(), fdt_data_size_(), fdt_find_add_string_(), fdt_get_string(), fdt_packblocks_(), fdt_resize(), fdt_splice_mem_rsv_(), fdt_splice_string_(), fdt_splice_struct_(), fdt_sw_probe_memrsv_(), and fdt_sw_probe_struct_().
#define fdt_off_dt_struct(fdt) (fdt_get_header(fdt, off_dt_struct))
Referenced by fdt_add_reservemap_entry(), fdt_add_string_(), fdt_blocks_misordered_(), fdt_check_header(), fdt_finish(), fdt_grab_space_(), fdt_offset_ptr(), fdt_offset_ptr_(), fdt_packblocks_(), fdt_resize(), and fdt_splice_mem_rsv_().
#define fdt_off_mem_rsvmap(fdt) (fdt_get_header(fdt, off_mem_rsvmap))
Referenced by fdt_blocks_misordered_(), fdt_check_header(), fdt_create_with_flags(), fdt_mem_rsv(), fdt_mem_rsv_(), and fdt_packblocks_().
#define fdt_property_string(fdt, name, str) fdt_property(fdt, name, str, strlen(str)+1)
#define fdt_set_hdr_(name)
Value:
static inline void fdt_set_##name(void *fdt, uint32_t val) \
    { \
        struct fdt_header *fdth = (struct fdt_header *)fdt; \
        fdth->name = cpu_to_fdt32(val); \
    }
#define fdt_setprop_empty(fdt, nodeoffset, name) fdt_setprop((fdt), (nodeoffset), (name), NULL, 0)
#define fdt_setprop_string(fdt, nodeoffset, name, str) fdt_setprop((fdt), (nodeoffset), (name), (str), strlen(str)+1)
#define fdt_size_dt_strings(fdt) (fdt_get_header(fdt, size_dt_strings))
Referenced by fdt_add_string_(), fdt_blocks_misordered_(), fdt_check_header(), fdt_data_size_(), fdt_del_last_string_(), fdt_find_add_string_(), fdt_finish(), fdt_get_string(), fdt_grab_space_(), fdt_open_into(), fdt_pack(), fdt_packblocks_(), fdt_resize(), and fdt_splice_string_().
#define fdt_size_dt_struct(fdt) (fdt_get_header(fdt, size_dt_struct))
Referenced by fdt_add_string_(), fdt_check_header(), fdt_finish(), fdt_grab_space_(), fdt_offset_ptr(), fdt_open_into(), fdt_pack(), fdt_resize(), fdt_ro_probe_(), fdt_rw_probe_(), and fdt_splice_struct_().
#define fdt_totalsize(fdt) (fdt_get_header(fdt, totalsize))
Referenced by fdt_add_reservemap_entry(), fdt_add_string_(), fdt_blocks_misordered_(), fdt_check_full(), fdt_check_header(), fdt_find_add_string_(), fdt_finish(), fdt_finish_reservemap(), fdt_grab_space_(), fdt_mem_rsv(), fdt_move(), fdt_offset_ptr(), fdt_open_into(), fdt_resize(), fdt_ro_probe_(), fdt_splice_(), and fdt_sw_probe_struct_().
#define fdt_version(fdt) (fdt_get_header(fdt, version))
Referenced by fdt_check_header(), fdt_get_name(), fdt_get_property_by_offset(), fdt_get_property_namelen(), fdt_get_string(), fdt_getprop_by_offset(), fdt_getprop_namelen(), fdt_header_size(), fdt_next_tag(), fdt_offset_ptr(), fdt_open_into(), fdt_ro_probe_(), and fdt_rw_probe_().
Function Documentation
static uint16_t fdt16_ld (const fdt16_t * p) [inline], [static]
{
    const uint8_t *bp = (const uint8_t *)p;
    return ((uint16_t)bp[0] << 8) | bp[1];
}
static uint32_t fdt32_ld (const fdt32_t * p) [inline], [static]
{
    const uint8_t *bp = (const uint8_t *)p;
    return ((uint32_t)bp[0] << 24)
        | ((uint32_t)bp[1] << 16)
        | ((uint32_t)bp[2] << 8)
        | bp[3];
}
static void fdt32_st (void * property, uint32_t value) [inline], [static]
Referenced by fdt_appendprop_addrrange().
{
    uint8_t *bp = (uint8_t *)property;
    bp[0] = value >> 24;
    bp[1] = (value >> 16) & 0xff;
    bp[2] = (value >> 8) & 0xff;
    bp[3] = value & 0xff;
}
static uint64_t fdt64_ld (const fdt64_t * p) [inline], [static]
{
    const uint8_t *bp = (const uint8_t *)p;
    return ((uint64_t)bp[0] << 56)
        | ((uint64_t)bp[1] << 48)
        | ((uint64_t)bp[2] << 40)
        | ((uint64_t)bp[3] << 32)
        | ((uint64_t)bp[4] << 24)
        | ((uint64_t)bp[5] << 16)
        | ((uint64_t)bp[6] << 8)
        | bp[7];
}
static void fdt64_st (void * property, uint64_t value) [inline], [static]
Referenced by fdt_appendprop_addrrange().
{
    uint8_t *bp = (uint8_t *)property;
    bp[0] = value >> 56;
    bp[1] = (value >> 48) & 0xff;
    bp[2] = (value >> 40) & 0xff;
    bp[3] = (value >> 32) & 0xff;
    bp[4] = (value >> 24) & 0xff;
    bp[5] = (value >> 16) & 0xff;
    bp[6] = (value >> 8) & 0xff;
    bp[7] = value & 0xff;
}
int fdt_add_mem_rsv (void * fdt, uint64_t address, uint64_t size)
fdt_add_mem_rsv - add one memory reserve map entry : pointer to the device tree blob : 64-bit start address of the reserve map entry : 64-bit size of the reserved region
Adds a reserve map entry to the given blob reserving a region at address address of length size.
This function will insert data into the reserve map and will therefore change the indexes of some entries in the table.
returns: 0, on success -FDT_ERR_NOSPACE, there is insufficient free space in the blob to contain the new reservation entry -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADLAYOUT, -FDT_ERR_TRUNCATED, standard meanings
References fdt_reserve_entry::address, cpu_to_fdt64(), fdt_mem_rsv_w_(), fdt_num_mem_rsv(), FDT_RW_PROBE, fdt_splice_mem_rsv_(), and fdt_reserve_entry::size.
{
    struct fdt_reserve_entry *re;
    int err;
    FDT_RW_PROBE(fdt);
    re = fdt_mem_rsv_w_(fdt, fdt_num_mem_rsv(fdt));
    err = fdt_splice_mem_rsv_(fdt, re, 0, 1);
    if (err)
        return err;
    re->address = cpu_to_fdt64(address);
    re->size = cpu_to_fdt64(size);
    return 0;
}
int fdt_add_reservemap_entry (void * fdt, uint64_t addr, uint64_t size)
References fdt_reserve_entry::address, cpu_to_fdt64(), FDT_ERR_NOSPACE, fdt_off_dt_struct, FDT_SW_PROBE_MEMRSV, fdt_totalsize, and fdt_reserve_entry::size.
Referenced by fdt_finish_reservemap().
{
    struct fdt_reserve_entry *re;
    int offset;
    FDT_SW_PROBE_MEMRSV(fdt);
    offset = fdt_off_dt_struct(fdt);
    if ((offset + sizeof(*re)) > fdt_totalsize(fdt))
        return -FDT_ERR_NOSPACE;
    re = (struct fdt_reserve_entry *)((char *)fdt + offset);
    re->address = cpu_to_fdt64(addr);
    re->size = cpu_to_fdt64(size);
    fdt_set_off_dt_struct(fdt, offset + sizeof(*re));
    return 0;
}
int fdt_add_subnode (void * fdt, int parentoffset, const char * name)
References fdt_add_subnode_namelen(), and strlen().
Referenced by overlay_apply_node(), and overlay_symbol_update().
{
    return fdt_add_subnode_namelen(fdt, parentoffset, name,
      strlen(name));
}
int fdt_add_subnode_namelen (void * fdt, int parentoffset, const char * name, int namelen)
References can_assume, cpu_to_fdt32(), FDT_BEGIN_NODE, FDT_END_NODE, FDT_ERR_EXISTS, FDT_ERR_INTERNAL, FDT_ERR_NOTFOUND, fdt_next_tag(), FDT_NOP, fdt_offset_ptr_w_(), FDT_PROP, FDT_RW_PROBE, fdt_splice_struct_(), fdt_subnode_offset_namelen(), FDT_TAGALIGN, FDT_TAGSIZE, memcpy(), memset(), fdt_node_header::name, and fdt_node_header::tag.
Referenced by fdt_add_subnode().
{
    struct fdt_node_header *nh;
    int offset, nextoffset;
    int nodelen;
    int err;
    uint32_t tag;
    fdt32_t *endtag;
    FDT_RW_PROBE(fdt);
    offset = fdt_subnode_offset_namelen(fdt, parentoffset,
      name, namelen);
    if (offset >= 0)
        return -FDT_ERR_EXISTS;
    else if (offset != -FDT_ERR_NOTFOUND)
        return offset;
    /* Try to place the new node after the parent's properties */
    tag = fdt_next_tag(fdt, parentoffset, &nextoffset);
    /* the fdt_subnode_offset_namelen() should ensure this never hits */
    if (!can_assume(LIBFDT_FLAWLESS) && (tag != FDT_BEGIN_NODE))
        return -FDT_ERR_INTERNAL;
    do {
        offset = nextoffset;
        tag = fdt_next_tag(fdt, offset, &nextoffset);
    } while ((tag == FDT_PROP) || (tag == FDT_NOP));
    nh = fdt_offset_ptr_w_(fdt, offset);
    nodelen = sizeof(*nh) + FDT_TAGALIGN(namelen+1) + FDT_TAGSIZE;
    err = fdt_splice_struct_(fdt, nh, 0, nodelen);
    if (err)
        return err;
    nh->tag = cpu_to_fdt32(FDT_BEGIN_NODE);
    memset(nh->name, 0, FDT_TAGALIGN(namelen+1));
    memcpy(nh->name, name, namelen);
    endtag = (fdt32_t *)((char *)nh + nodelen - FDT_TAGSIZE);
    *endtag = cpu_to_fdt32(FDT_END_NODE);
    return offset;
}
int fdt_address_cells (const void * fdt, int nodeoffset)
fdt_address_cells - retrieve address size for a bus represented in the tree : pointer to the device tree blob : offset of the node to find the address size for
When the node has a valid #address-cells property, returns its value.
returns: 0 <= n < FDT_MAX_NCELLS, on success 2, if the node has no #address-cells property -FDT_ERR_BADNCELLS, if the node has a badly formatted or invalid #address-cells property -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
References fdt_cells(), FDT_ERR_BADNCELLS, and FDT_ERR_NOTFOUND.
Referenced by fdt_appendprop_addrrange().
{
    int val;
    val = fdt_cells(fdt, nodeoffset, "#address-cells");
    if (val == 0)
        return -FDT_ERR_BADNCELLS;
    if (val == -FDT_ERR_NOTFOUND)
        return 2;
    return val;
}
int fdt_appendprop (void * fdt, int nodeoffset, const char * name, const void * val, int len)
References cpu_to_fdt32(), fdt_property::data, fdt_add_property_(), fdt_get_property_w(), FDT_RW_PROBE, fdt_splice_struct_(), FDT_TAGALIGN, fdt_property::len, and memcpy().
Referenced by fdt_appendprop_addrrange(), fdt_appendprop_u32(), and fdt_appendprop_u64().
{
    struct fdt_property *prop;
    int err, oldlen, newlen;
    FDT_RW_PROBE(fdt);
    prop = fdt_get_property_w(fdt, nodeoffset, name, &oldlen);
    if (prop) {
        newlen = len + oldlen;
        err = fdt_splice_struct_(fdt, prop->data,
                     FDT_TAGALIGN(oldlen),
                     FDT_TAGALIGN(newlen));
        if (err)
            return err;
        prop->len = cpu_to_fdt32(newlen);
        memcpy(prop->data + oldlen, val, len);
    } else {
        err = fdt_add_property_(fdt, nodeoffset, name, len, &prop);
        if (err)
            return err;
        memcpy(prop->data, val, len);
    }
    return 0;
}
int fdt_appendprop_addrrange (void * fdt, int parent, int nodeoffset, const char * name, uint64_t addr, uint64_t size)
References fdt32_st(), fdt64_st(), fdt_address_cells(), fdt_appendprop(), FDT_ERR_BADNCELLS, FDT_ERR_BADVALUE, fdt_size_cells(), and UINT32_MAX.
{
    int addr_cells, size_cells, ret;
    uint8_t data[sizeof(fdt64_t) * 2], *prop;
    ret = fdt_address_cells(fdt, parent);
    if (ret < 0)
        return ret;
    addr_cells = ret;
    ret = fdt_size_cells(fdt, parent);
    if (ret < 0)
        return ret;
    size_cells = ret;
    /* check validity of address */
    prop = data;
    if (addr_cells == 1) {
        if ((addr > UINT32_MAX) || (((uint64_t) UINT32_MAX + 1 - addr) < size))
            return -FDT_ERR_BADVALUE;
        fdt32_st(prop, (uint32_t)addr);
    } else if (addr_cells == 2) {
        fdt64_st(prop, addr);
    } else {
        return -FDT_ERR_BADNCELLS;
    }
    /* check validity of size */
    prop += addr_cells * sizeof(fdt32_t);
    if (size_cells == 1) {
        if (size > UINT32_MAX)
            return -FDT_ERR_BADVALUE;
        fdt32_st(prop, (uint32_t)size);
    } else if (size_cells == 2) {
        fdt64_st(prop, size);
    } else {
        return -FDT_ERR_BADNCELLS;
    }
    return fdt_appendprop(fdt, nodeoffset, name, data,
                  (addr_cells + size_cells) * sizeof(fdt32_t));
}
static int fdt_appendprop_cell (void * fdt, int nodeoffset, const char * name, uint32_t val) [inline], [static]
References fdt_appendprop_u32().
{
    return fdt_appendprop_u32(fdt, nodeoffset, name, val);
}
static int fdt_appendprop_u32 (void * fdt, int nodeoffset, const char * name, uint32_t val) [inline], [static]
References cpu_to_fdt32(), and fdt_appendprop().
Referenced by fdt_appendprop_cell().
{
    fdt32_t tmp = cpu_to_fdt32(val);
    return fdt_appendprop(fdt, nodeoffset, name, &tmp, sizeof(tmp));
}
static int fdt_appendprop_u64 (void * fdt, int nodeoffset, const char * name, uint64_t val) [inline], [static]
References cpu_to_fdt64(), and fdt_appendprop().
{
    fdt64_t tmp = cpu_to_fdt64(val);
    return fdt_appendprop(fdt, nodeoffset, name, &tmp, sizeof(tmp));
}
int fdt_begin_node (void * fdt, const char * name)
References cpu_to_fdt32(), FDT_BEGIN_NODE, FDT_ERR_NOSPACE, fdt_grab_space_(), FDT_SW_PROBE_STRUCT, FDT_TAGALIGN, memcpy(), fdt_node_header::name, strlen(), and fdt_node_header::tag.
Referenced by fdt_create_empty_tree().
{
    struct fdt_node_header *nh;
    int namelen;
    FDT_SW_PROBE_STRUCT(fdt);
    namelen = strlen(name) + 1;
    nh = fdt_grab_space_(fdt, sizeof(*nh) + FDT_TAGALIGN(namelen));
    if (! nh)
        return -FDT_ERR_NOSPACE;
    nh->tag = cpu_to_fdt32(FDT_BEGIN_NODE);
    memcpy(nh->name, name, namelen);
    return 0;
}
int fdt_check_full (const void * fdt, size_t bufsize)
References FDT_BEGIN_NODE, fdt_check_header(), FDT_END, FDT_END_NODE, FDT_ERR_BADSTRUCTURE, FDT_ERR_INTERNAL, FDT_ERR_TRUNCATED, fdt_get_name(), fdt_getprop_by_offset(), fdt_header_size(), fdt_next_tag(), FDT_NOP, fdt_num_mem_rsv(), FDT_PROP, fdt_totalsize, FDT_V1_SIZE, and INT_MAX.
{
    int err;
    int num_memrsv;
    int offset, nextoffset = 0;
    uint32_t tag;
    unsigned int depth = 0;
    const void *prop;
    const char *propname;
    bool expect_end = false;
    if (bufsize < FDT_V1_SIZE)
        return -FDT_ERR_TRUNCATED;
    if (bufsize < fdt_header_size(fdt))
        return -FDT_ERR_TRUNCATED;
    err = fdt_check_header(fdt);
    if (err != 0)
        return err;
    if (bufsize < fdt_totalsize(fdt))
        return -FDT_ERR_TRUNCATED;
    num_memrsv = fdt_num_mem_rsv(fdt);
    if (num_memrsv < 0)
        return num_memrsv;
    while (1) {
        offset = nextoffset;
        tag = fdt_next_tag(fdt, offset, &nextoffset);
        if (nextoffset < 0)
            return nextoffset;
        /* If we see two root nodes, something is wrong */
        if (expect_end && tag != FDT_END)
            return -FDT_ERR_BADSTRUCTURE;
        switch (tag) {
        case FDT_NOP:
            break;
        case FDT_END:
            if (depth != 0)
                return -FDT_ERR_BADSTRUCTURE;
            return 0;
        case FDT_BEGIN_NODE:
            depth++;
            if (depth > INT_MAX)
                return -FDT_ERR_BADSTRUCTURE;
            /* The root node must have an empty name */
            if (depth == 1) {
                const char *name;
                int len;
                name = fdt_get_name(fdt, offset, &len);
                if (!name)
                    return len;
                if (*name || len)
                    return -FDT_ERR_BADSTRUCTURE;
            }
            break;
        case FDT_END_NODE:
            if (depth == 0)
                return -FDT_ERR_BADSTRUCTURE;
            depth--;
            if (depth == 0)
                expect_end = true;
            break;
        case FDT_PROP:
            prop = fdt_getprop_by_offset(fdt, offset, &propname,
                             &err);
            if (!prop)
                return err;
            break;
        default:
            return -FDT_ERR_INTERNAL;
        }
    }
}
int fdt_check_header (const void * fdt)
fdt_check_header - sanity check a device tree header : pointer to data which might be a flattened device tree
fdt_check_header() checks that the given buffer contains what appears to be a flattened device tree, and that the header contains valid information (to the extent that can be determined from the header alone).
returns: 0, if the buffer appears to contain a valid device tree -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_TRUNCATED, standard meanings, as above
References can_assume, check_block_(), check_off_(), FDT_ERR_ALIGNMENT, FDT_ERR_BADMAGIC, FDT_ERR_BADVERSION, FDT_ERR_TRUNCATED, FDT_FIRST_SUPPORTED_VERSION, fdt_header_size(), fdt_last_comp_version, FDT_LAST_SUPPORTED_VERSION, FDT_MAGIC, fdt_magic, fdt_off_dt_strings, fdt_off_dt_struct, fdt_off_mem_rsvmap, fdt_size_dt_strings, fdt_size_dt_struct, fdt_totalsize, fdt_version, and INT_MAX.
Referenced by fdt_check_full().
{
    size_t hdrsize;
    /* The device tree must be at an 8-byte aligned address */
    if ((uintptr_t)fdt & 7)
        return -FDT_ERR_ALIGNMENT;
    if (fdt_magic(fdt) != FDT_MAGIC)
        return -FDT_ERR_BADMAGIC;
    if (!can_assume(LATEST)) {
        if ((fdt_version(fdt) < FDT_FIRST_SUPPORTED_VERSION)
            || (fdt_last_comp_version(fdt) >
            FDT_LAST_SUPPORTED_VERSION))
            return -FDT_ERR_BADVERSION;
        if (fdt_version(fdt) < fdt_last_comp_version(fdt))
            return -FDT_ERR_BADVERSION;
    }
    hdrsize = fdt_header_size(fdt);
    if (!can_assume(VALID_DTB)) {
        if ((fdt_totalsize(fdt) < hdrsize)
            || (fdt_totalsize(fdt) > INT_MAX))
            return -FDT_ERR_TRUNCATED;
        /* Bounds check memrsv block */
        if (!check_off_(hdrsize, fdt_totalsize(fdt),
                fdt_off_mem_rsvmap(fdt)))
            return -FDT_ERR_TRUNCATED;
        /* Bounds check structure block */
        if (!can_assume(LATEST) && fdt_version(fdt) < 17) {
            if (!check_off_(hdrsize, fdt_totalsize(fdt),
                    fdt_off_dt_struct(fdt)))
                return -FDT_ERR_TRUNCATED;
        } else {
            if (!check_block_(hdrsize, fdt_totalsize(fdt),
                      fdt_off_dt_struct(fdt),
                      fdt_size_dt_struct(fdt)))
                return -FDT_ERR_TRUNCATED;
        }
        /* Bounds check strings block */
        if (!check_block_(hdrsize, fdt_totalsize(fdt),
                  fdt_off_dt_strings(fdt),
                  fdt_size_dt_strings(fdt)))
            return -FDT_ERR_TRUNCATED;
    }
    return 0;
}
int fdt_create (void * buf, int bufsize)
fdt_create - begin creation of a new fdt : pointer to memory allocated where fdt will be created : size of the memory space at fdt
fdt_create() is equivalent to fdt_create_with_flags() with flags=0.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient for a minimal fdt
References fdt_create_with_flags().
Referenced by fdt_create_empty_tree().
{
    return fdt_create_with_flags(buf, bufsize, 0);
}
int fdt_create_empty_tree (void * buf, int bufsize)
References fdt_begin_node(), fdt_create(), fdt_end_node(), fdt_finish(), fdt_finish_reservemap(), and fdt_open_into().
{
    int err;
    err = fdt_create(buf, bufsize);
    if (err)
        return err;
    err = fdt_finish_reservemap(buf);
    if (err)
        return err;
    err = fdt_begin_node(buf, "");
    if (err)
        return err;
    err = fdt_end_node(buf);
    if (err)
        return err;
    err = fdt_finish(buf);
    if (err)
        return err;
    return fdt_open_into(buf, buf, bufsize);
}
int fdt_create_with_flags (void * buf, int bufsize, uint32_t flags)
fdt_create_with_flags - begin creation of a new fdt : pointer to memory allocated where fdt will be created : size of the memory space at fdt : a valid combination of FDT_CREATE_FLAG_ flags, or 0.
fdt_create_with_flags() begins the process of creating a new fdt with the sequential write interface.
fdt creation process must end with fdt_finish() to produce a valid fdt.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient for a minimal fdt -FDT_ERR_BADFLAGS, flags is not valid
References FDT_ALIGN, FDT_CREATE_FLAGS_ALL, FDT_ERR_BADFLAGS, FDT_ERR_NOSPACE, FDT_LAST_SUPPORTED_VERSION, fdt_off_mem_rsvmap, FDT_SW_MAGIC, and memset().
Referenced by fdt_create().
{
    const int hdrsize = FDT_ALIGN(sizeof(struct fdt_header),
                      sizeof(struct fdt_reserve_entry));
    void *fdt = buf;
    if (bufsize < hdrsize)
        return -FDT_ERR_NOSPACE;
    if (flags & ~FDT_CREATE_FLAGS_ALL)
        return -FDT_ERR_BADFLAGS;
    memset(buf, 0, bufsize);
    /*
     * magic and last_comp_version keep intermediate state during the fdt
     * creation process, which is replaced with the proper FDT format by
     * fdt_finish().
     *
     * flags should be accessed with sw_flags().
     */
    fdt_set_magic(fdt, FDT_SW_MAGIC);
    fdt_set_version(fdt, FDT_LAST_SUPPORTED_VERSION);
    fdt_set_last_comp_version(fdt, flags);
    fdt_set_totalsize(fdt, bufsize);
    fdt_set_off_mem_rsvmap(fdt, hdrsize);
    fdt_set_off_dt_struct(fdt, fdt_off_mem_rsvmap(fdt));
    fdt_set_off_dt_strings(fdt, 0);
    return 0;
}
int fdt_del_mem_rsv (void * fdt, int n)
fdt_del_mem_rsv - remove a memory reserve map entry : pointer to the device tree blob
: entry to remove
fdt_del_mem_rsv() removes the n-th memory reserve map entry from the blob.
This function will delete data from the reservation table and will therefore change the indexes of some entries in the table.
returns: 0, on success -FDT_ERR_NOTFOUND, there is no entry of the given index (i.e. there are less than n+1 reserve map entries) -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADLAYOUT, -FDT_ERR_TRUNCATED, standard meanings
References FDT_ERR_NOTFOUND, fdt_mem_rsv_w_(), fdt_num_mem_rsv(), FDT_RW_PROBE, and fdt_splice_mem_rsv_().
{
    struct fdt_reserve_entry *re = fdt_mem_rsv_w_(fdt, n);
    FDT_RW_PROBE(fdt);
    if (n >= fdt_num_mem_rsv(fdt))
        return -FDT_ERR_NOTFOUND;
    return fdt_splice_mem_rsv_(fdt, re, 1, 0);
}
int fdt_del_node (void * fdt, int nodeoffset)
fdt_del_node - delete a node (subtree) : pointer to the device tree blob : offset of the node to nop
fdt_del_node() will remove the given node, including all its subnodes if any, from the blob.
This function will delete data from the blob, and will therefore change the offsets of some existing nodes.
returns: 0, on success -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADLAYOUT, -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
References fdt_node_end_offset_(), fdt_offset_ptr_w_(), FDT_RW_PROBE, and fdt_splice_struct_().
{
    int endoffset;
    FDT_RW_PROBE(fdt);
    endoffset = fdt_node_end_offset_(fdt, nodeoffset);
    if (endoffset < 0)
        return endoffset;
    return fdt_splice_struct_(fdt, fdt_offset_ptr_w_(fdt, nodeoffset),
                  endoffset - nodeoffset, 0);
}
int fdt_delprop (void * fdt, int nodeoffset, const char * name)
References fdt_get_property_w(), FDT_RW_PROBE, fdt_splice_struct_(), FDT_TAGALIGN, and fdt_property::len.
{
    struct fdt_property *prop;
    int len, proplen;
    FDT_RW_PROBE(fdt);
    prop = fdt_get_property_w(fdt, nodeoffset, name, &len);
    if (!prop)
        return len;
    proplen = sizeof(*prop) + FDT_TAGALIGN(len);
    return fdt_splice_struct_(fdt, prop, proplen, 0);
}
int fdt_end_node (void * fdt)
References cpu_to_fdt32(), FDT_END_NODE, FDT_ERR_NOSPACE, fdt_grab_space_(), FDT_SW_PROBE_STRUCT, and FDT_TAGSIZE.
Referenced by fdt_create_empty_tree().
{
    fdt32_t *en;
    FDT_SW_PROBE_STRUCT(fdt);
    en = fdt_grab_space_(fdt, FDT_TAGSIZE);
    if (! en)
        return -FDT_ERR_NOSPACE;
    *en = cpu_to_fdt32(FDT_END_NODE);
    return 0;
}
int fdt_find_max_phandle (const void * fdt, uint32_t * phandle)
fdt_find_max_phandle - find and return the highest phandle in a tree : pointer to the device tree blob : return location for the highest phandle value found in the tree
fdt_find_max_phandle() finds the highest phandle value in the given device tree. The value returned in is only valid if the function returns success.
returns: 0 on success or a negative error code on failure
References FDT_ERR_NOTFOUND, fdt_get_phandle(), fdt_next_node(), and NULL.
Referenced by fdt_generate_phandle(), fdt_get_max_phandle(), and fdt_overlay_apply().
{
    uint32_t max = 0;
    int offset = -1;
    while (true) {
        uint32_t value;
        offset = fdt_next_node(fdt, offset, NULL);
        if (offset < 0) {
            if (offset == -FDT_ERR_NOTFOUND)
                break;
            return offset;
        }
        value = fdt_get_phandle(fdt, offset);
        if (value > max)
            max = value;
    }
    if (phandle)
        *phandle = max;
    return 0;
}
int fdt_finish (void * fdt)
References cpu_to_fdt32(), fdt32_to_cpu(), FDT_END, FDT_ERR_NOSPACE, fdt_grab_space_(), FDT_LAST_COMPATIBLE_VERSION, FDT_MAGIC, fdt_next_tag(), fdt_off_dt_struct, fdt_offset_ptr_w_(), FDT_PROP, fdt_size_dt_strings, fdt_size_dt_struct, FDT_SW_PROBE_STRUCT, fdt_totalsize, memmove(), fdt_property::nameoff, and fdt_property::tag.
Referenced by fdt_create_empty_tree().
{
    char *p = (char *)fdt;
    fdt32_t *end;
    int oldstroffset, newstroffset;
    uint32_t tag;
    int offset, nextoffset;
    FDT_SW_PROBE_STRUCT(fdt);
    /* Add terminator */
    end = fdt_grab_space_(fdt, sizeof(*end));
    if (! end)
        return -FDT_ERR_NOSPACE;
    *end = cpu_to_fdt32(FDT_END);
    /* Relocate the string table */
    oldstroffset = fdt_totalsize(fdt) - fdt_size_dt_strings(fdt);
    newstroffset = fdt_off_dt_struct(fdt) + fdt_size_dt_struct(fdt);
    memmove(p + newstroffset, p + oldstroffset, fdt_size_dt_strings(fdt));
    fdt_set_off_dt_strings(fdt, newstroffset);
    /* Walk the structure, correcting string offsets */
    offset = 0;
    while ((tag = fdt_next_tag(fdt, offset, &nextoffset)) != FDT_END) {
        if (tag == FDT_PROP) {
            struct fdt_property *prop =
                fdt_offset_ptr_w_(fdt, offset);
            int nameoff;
            nameoff = fdt32_to_cpu(prop->nameoff);
            nameoff += fdt_size_dt_strings(fdt);
            prop->nameoff = cpu_to_fdt32(nameoff);
        }
        offset = nextoffset;
    }
    if (nextoffset < 0)
        return nextoffset;
    /* Finally, adjust the header */
    fdt_set_totalsize(fdt, newstroffset + fdt_size_dt_strings(fdt));
    /* And fix up fields that were keeping intermediate state. */
    fdt_set_last_comp_version(fdt, FDT_LAST_COMPATIBLE_VERSION);
    fdt_set_magic(fdt, FDT_MAGIC);
    return 0;
}
int fdt_finish_reservemap (void * fdt)
References fdt_add_reservemap_entry(), and fdt_totalsize.
Referenced by fdt_create_empty_tree().
{
    int err = fdt_add_reservemap_entry(fdt, 0, 0);
    if (err)
        return err;
    fdt_set_off_dt_strings(fdt, fdt_totalsize(fdt));
    return 0;
}
int fdt_first_property_offset (const void * fdt, int nodeoffset)
fdt_first_property_offset - find the offset of a node's first property : pointer to the device tree blob : structure block offset of a node
fdt_first_property_offset() finds the first property of the node at the given structure block offset.
returns: structure block offset of the property (>=0), on success -FDT_ERR_NOTFOUND, if the requested node has no properties -FDT_ERR_BADOFFSET, if nodeoffset did not point to an FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings.
References fdt_check_node_offset_(), and nextprop_().
Referenced by fdt_get_property_namelen_().
{
    int offset;
    if ((offset = fdt_check_node_offset_(fdt, nodeoffset)) < 0)
        return offset;
    return nextprop_(fdt, offset);
}
int fdt_first_subnode (const void * fdt, int offset)
fdt_first_subnode() - get offset of first direct subnode : FDT blob : Offset of node to check
Return: offset of first subnode, or -FDT_ERR_NOTFOUND if there is none
References FDT_ERR_NOTFOUND, and fdt_next_node().
{
    int depth = 0;
    offset = fdt_next_node(fdt, offset, &depth);
    if (offset < 0 || depth != 1)
        return -FDT_ERR_NOTFOUND;
    return offset;
}
int fdt_generate_phandle (const void * fdt, uint32_t * phandle)
fdt_generate_phandle - return a new, unused phandle for a device tree blob : pointer to the device tree blob : return location for the new phandle
Walks the device tree blob and looks for the highest phandle value. On success, the new, unused phandle value (one higher than the previously highest phandle value in the device tree blob) will be returned in the parameter.
Return: 0 on success or a negative error-code on failure
References FDT_ERR_NOPHANDLES, fdt_find_max_phandle(), and FDT_MAX_PHANDLE.
{
    uint32_t max;
    int err;
    err = fdt_find_max_phandle(fdt, &max);
    if (err < 0)
        return err;
    if (max == FDT_MAX_PHANDLE)
        return -FDT_ERR_NOPHANDLES;
    if (phandle)
        *phandle = max + 1;
    return 0;
}
const char* fdt_get_alias (const void * fdt, const char * name)
References fdt_get_alias_namelen(), and strlen().
{
    return fdt_get_alias_namelen(fdt, name, strlen(name));
}
const char* fdt_get_alias_namelen (const void * fdt, const char * name, int namelen)
References fdt_path_getprop_namelen(), and NULL.
Referenced by fdt_get_alias(), and fdt_path_offset_namelen().
{
    return fdt_path_getprop_namelen(fdt, "/aliases", name, namelen,
      NULL);
}
static uint32_t fdt_get_max_phandle (const void * fdt) [inline], [static]
fdt_get_max_phandle - retrieves the highest phandle in a tree : pointer to the device tree blob
fdt_get_max_phandle retrieves the highest phandle in the given device tree. This will ignore badly formatted phandles, or phandles with a value of 0 or -1.
This function is deprecated in favour of fdt_find_max_phandle().
returns: the highest phandle on success 0, if no phandle was found in the device tree -1, if an error occurred
References fdt_find_max_phandle().
{
    uint32_t phandle;
    int err;
    err = fdt_find_max_phandle(fdt, &phandle);
    if (err < 0)
        return (uint32_t)-1;
    return phandle;
}
int fdt_get_mem_rsv (const void * fdt, int n, uint64_t * address, uint64_t * size)
fdt_get_mem_rsv - retrieve one memory reserve map entry : pointer to the device tree blob
: index of reserve map entry : pointer to 64-bit variable to hold the start address : pointer to 64-bit variable to hold the size of the entry
On success, and will contain the address and size of the n-th reserve map entry from the device tree blob, in native-endian format.
returns: 0, on success -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, standard meanings
References fdt_reserve_entry::address, can_assume, fdt64_ld_(), FDT_ERR_BADOFFSET, fdt_mem_rsv(), FDT_RO_PROBE, and fdt_reserve_entry::size.
{
    const struct fdt_reserve_entry *re;
    FDT_RO_PROBE(fdt);
    re = fdt_mem_rsv(fdt, n);
    if (!can_assume(VALID_INPUT) && !re)
        return -FDT_ERR_BADOFFSET;
    *address = fdt64_ld_(&re->address);
    *size = fdt64_ld_(&re->size);
    return 0;
}
const char* fdt_get_name (const void * fdt, int nodeoffset, int * lenp)
fdt_get_name - retrieve the name of a given node : pointer to the device tree blob : structure block offset of the starting node : pointer to an integer variable (will be overwritten) or NULL
fdt_get_name() retrieves the name (including unit address) of the device tree node at structure block offset nodeoffset. If lenp is non-NULL, the length of this name is also returned, in the integer pointed to by lenp.
returns: pointer to the node's name, on success If lenp is non-NULL, *lenp contains the length of that name (>=0) NULL, on error if lenp is non-NULL *lenp contains an error code (<0): -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, standard meanings
References can_assume, fdt_check_node_offset_(), FDT_ERR_BADSTRUCTURE, fdt_offset_ptr_(), fdt_ro_probe_(), fdt_version, fdt_node_header::name, NULL, strlen(), and strrchr().
Referenced by fdt_check_full(), fdt_get_path(), fdt_nodename_eq_(), fdt_set_name(), get_path_len(), overlay_apply_node(), and overlay_update_local_node_references().
{
    const struct fdt_node_header *nh = fdt_offset_ptr_(fdt, nodeoffset);
    const char *nameptr;
    int err;
    if (((err = fdt_ro_probe_(fdt)) < 0)
        || ((err = fdt_check_node_offset_(fdt, nodeoffset)) < 0))
            goto fail;
    nameptr = nh->name;
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10) {
        /*
         * For old FDT versions, match the naming conventions of V16:
         * give only the leaf name (after all /). The actual tree
         * contents are loosely checked.
         */
        const char *leaf;
        leaf = strrchr(nameptr, '/');
        if (leaf == NULL) {
            err = -FDT_ERR_BADSTRUCTURE;
            goto fail;
        }
        nameptr = leaf+1;
    }
    if (len)
        *len = strlen(nameptr);
    return nameptr;
 fail:
    if (len)
        *len = err;
    return NULL;
}
int fdt_get_path (const void * fdt, int nodeoffset, char * buf, int buflen)
fdt_get_path - determine the full path of a node : pointer to the device tree blob : offset of the node whose path to find : character buffer to contain the returned path (will be overwritten) : size of the character buffer at buf
fdt_get_path() computes the full path of the node at offset nodeoffset, and records that path in the buffer at buf.
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset.
returns: 0, on success buf contains the absolute path of the node at nodeoffset, as a NUL-terminated string. -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_NOSPACE, the path of the given node is longer than (bufsize-1) characters and will not fit in the given buffer. -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References FDT_ERR_BADOFFSET, FDT_ERR_BADSTRUCTURE, FDT_ERR_NOSPACE, FDT_ERR_NOTFOUND, fdt_get_name(), fdt_next_node(), FDT_RO_PROBE, and memcpy().
Referenced by overlay_symbol_update().
{
    int pdepth = 0, p = 0;
    int offset, depth, namelen;
    const char *name;
    FDT_RO_PROBE(fdt);
    if (buflen < 2)
        return -FDT_ERR_NOSPACE;
    for (offset = 0, depth = 0;
         (offset >= 0) && (offset <= nodeoffset);
         offset = fdt_next_node(fdt, offset, &depth)) {
        while (pdepth > depth) {
            do {
                p--;
            } while (buf[p-1] != '/');
            pdepth--;
        }
        if (pdepth >= depth) {
            name = fdt_get_name(fdt, offset, &namelen);
            if (!name)
                return namelen;
            if ((p + namelen + 1) <= buflen) {
                memcpy(buf + p, name, namelen);
                p += namelen;
                buf[p++] = '/';
                pdepth++;
            }
        }
        if (offset == nodeoffset) {
            if (pdepth < (depth + 1))
                return -FDT_ERR_NOSPACE;
            if (p > 1) /* special case so that root path is "/", not "" */
                p--;
            buf[p] = '\0';
            return 0;
        }
    }
    if ((offset == -FDT_ERR_NOTFOUND) || (offset >= 0))
        return -FDT_ERR_BADOFFSET;
    else if (offset == -FDT_ERR_BADOFFSET)
        return -FDT_ERR_BADSTRUCTURE;
    return offset; /* error from fdt_next_node() */
}
uint32_t fdt_get_phandle (const void * fdt, int nodeoffset)
fdt_get_phandle - retrieve the phandle of a given node : pointer to the device tree blob : structure block offset of the node
fdt_get_phandle() retrieves the phandle of the device tree node at structure block offset nodeoffset.
returns: the phandle of the node at nodeoffset, on success (!= 0, != -1) 0, if the node has no phandle, or another error occurs
References fdt32_ld_(), fdt_getprop(), and fdt_property::len.
Referenced by fdt_find_max_phandle(), fdt_node_offset_by_phandle(), and overlay_fixup_one_phandle().
{
    const fdt32_t *php;
    int len;
    /* FIXME: This is a bit sub-optimal, since we potentially scan
     * over all the properties twice. */
    php = fdt_getprop(fdt, nodeoffset, "phandle", &len);
    if (!php || (len != sizeof(*php))) {
        php = fdt_getprop(fdt, nodeoffset, "linux,phandle", &len);
        if (!php || (len != sizeof(*php)))
            return 0;
    }
    return fdt32_ld_(php);
}
struct fdt_property* fdt_get_property (const void * fdt, int nodeoffset, const char * name, int * lenp)
References fdt_get_property_namelen(), and strlen().
Referenced by fdt_get_property_w().
{
    return fdt_get_property_namelen(fdt, nodeoffset,
      name,
                    strlen(name), lenp);
}
struct fdt_property* fdt_get_property_by_offset (const void * fdt, int offset, int * lenp)
fdt_get_property_by_offset - retrieve the property at a given offset : pointer to the device tree blob : offset of the property to retrieve : pointer to an integer variable (will be overwritten) or NULL
fdt_get_property_by_offset() retrieves a pointer to the fdt_property structure within the device tree blob at the given offset. If lenp is non-NULL, the length of the property value is also returned, in the integer pointed to by lenp.
Note that this code only works on device tree versions >= 16. fdt_getprop() works on all versions.
returns: pointer to the structure representing the property if lenp is non-NULL, *lenp contains the length of the property value (>=0) NULL, on error if lenp is non-NULL, *lenp contains an error code (<0): -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_PROP tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
References can_assume, FDT_ERR_BADVERSION, fdt_get_property_by_offset_(), fdt_version, and NULL.
Referenced by fdt_get_property_by_offset_w().
{
    /* Prior to version 16, properties may need realignment
     * and this API does not work. fdt_getprop_*() will, however. */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10) {
        if (lenp)
            *lenp = -FDT_ERR_BADVERSION;
        return NULL;
    }
    return fdt_get_property_by_offset_(fdt, offset, lenp);
}
static struct fdt_property* fdt_get_property_by_offset_w (void * fdt, int offset, int * lenp) [static]
References fdt_get_property_by_offset().
{
    return (struct fdt_property *)(uintptr_t)
        fdt_get_property_by_offset(fdt, offset, lenp);
}
struct fdt_property* fdt_get_property_namelen (const void * fdt, int nodeoffset, const char * name, int namelen, int * lenp)
References can_assume, FDT_ERR_BADVERSION, fdt_get_property_namelen_(), fdt_version, and NULL.
Referenced by fdt_get_property().
{
    /* Prior to version 16, properties may need realignment
     * and this API does not work. fdt_getprop_*() will, however. */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10) {
        if (lenp)
            *lenp = -FDT_ERR_BADVERSION;
        return NULL;
    }
    return fdt_get_property_namelen_(fdt, offset, name, namelen, lenp,
                     NULL);
}
static struct fdt_property* fdt_get_property_w (void * fdt, int nodeoffset, const char * name, int * lenp) [static]
References fdt_get_property().
Referenced by fdt_appendprop(), fdt_delprop(), fdt_nop_property(), and fdt_resize_property_().
{
    return (struct fdt_property *)(uintptr_t)
        fdt_get_property(fdt, nodeoffset, name, lenp);
}
const char* fdt_get_string (const void * fdt, int stroffset, int * lenp)
fdt_get_string - retrieve a string from the strings block of a device tree : pointer to the device tree blob : offset of the string within the strings block (native endian) : optional pointer to return the string's length
fdt_get_string() retrieves a pointer to a single string from the strings block of the device tree blob at fdt, and optionally also returns the string's length in *lenp.
returns: a pointer to the string, on success NULL, if stroffset is out of bounds, or doesn't point to a valid string
References can_assume, FDT_ERR_BADOFFSET, FDT_ERR_INTERNAL, FDT_ERR_TRUNCATED, FDT_MAGIC, fdt_magic, fdt_off_dt_strings, fdt_ro_probe_(), fdt_size_dt_strings, FDT_SW_MAGIC, fdt_version, memchr(), NULL, and strlen().
Referenced by fdt_getprop_by_offset(), fdt_string(), and fdt_string_eq_().
{
    int32_t totalsize;
    uint32_t absoffset;
    size_t len;
    int err;
    const char *s, *n;
    if (can_assume(VALID_INPUT)) {
        s = (const char *)fdt + fdt_off_dt_strings(fdt) + stroffset;
        if (lenp)
            *lenp = strlen(s);
        return s;
    }
    totalsize = fdt_ro_probe_(fdt);
    err = totalsize;
    if (totalsize < 0)
        goto fail;
    err = -FDT_ERR_BADOFFSET;
    absoffset = stroffset + fdt_off_dt_strings(fdt);
    if (absoffset >= (unsigned)totalsize)
        goto fail;
    len = totalsize - absoffset;
    if (fdt_magic(fdt) == FDT_MAGIC) {
        if (stroffset < 0)
            goto fail;
        if (can_assume(LATEST) || fdt_version(fdt) >= 17) {
            if ((unsigned)stroffset >= fdt_size_dt_strings(fdt))
                goto fail;
            if ((fdt_size_dt_strings(fdt) - stroffset) < len)
                len = fdt_size_dt_strings(fdt) - stroffset;
        }
    } else if (fdt_magic(fdt) == FDT_SW_MAGIC) {
        unsigned int sw_stroffset = -stroffset;
        if ((stroffset >= 0) ||
            (sw_stroffset > fdt_size_dt_strings(fdt)))
            goto fail;
        if (sw_stroffset < len)
            len = sw_stroffset;
    } else {
        err = -FDT_ERR_INTERNAL;
        goto fail;
    }
    s = (const char *)fdt + absoffset;
    n = memchr(s, '\0', len);
    if (!n) {
        /* missing terminating NULL */
        err = -FDT_ERR_TRUNCATED;
        goto fail;
    }
    if (lenp)
        *lenp = n - s;
    return s;
fail:
    if (lenp)
        *lenp = err;
    return NULL;
}
const char* fdt_get_symbol (const void * fdt, const char * name)
References fdt_get_symbol_namelen(), and strlen().
{
    return fdt_get_symbol_namelen(fdt, name, strlen(
      name));
}
const char* fdt_get_symbol_namelen (const void * fdt, const char * name, int namelen)
References fdt_path_getprop_namelen(), and NULL.
Referenced by fdt_get_symbol().
{
    return fdt_path_getprop_namelen(fdt, "/__symbols__",
      name, namelen, NULL);
}
const void* fdt_getprop (const void * fdt, int nodeoffset, const char * name, int * lenp)
References fdt_getprop_namelen(), and strlen().
Referenced by fdt_cells(), fdt_get_phandle(), fdt_getprop_w(), fdt_node_check_compatible(), fdt_node_offset_by_prop_value(), fdt_overlay_target_offset(), fdt_setprop_inplace(), fdt_stringlist_count(), fdt_stringlist_get(), fdt_stringlist_search(), get_base_address(), get_irq(), overlay_fixup_one_phandle(), overlay_get_target_phandle(), overlay_phandle_add_offset(), and overlay_update_local_node_references().
{
    return fdt_getprop_namelen(fdt, nodeoffset, name,
      strlen(name), lenp);
}
const void* fdt_getprop_by_offset (const void * fdt, int offset, const char ** namep, int * lenp)
fdt_getprop_by_offset - retrieve the value of a property at a given offset : pointer to the device tree blob : offset of the property to read : pointer to a string variable (will be overwritten) or NULL : pointer to an integer variable (will be overwritten) or NULL
fdt_getprop_by_offset() retrieves a pointer to the value of the property at structure block offset 'offset' (this will be a pointer to within the device blob itself, not a copy of the value). If lenp is non-NULL, the length of the property value is also returned, in the integer pointed to by lenp. If namep is non-NULL, the property's namne will also be returned in the char * pointed to by namep (this will be a pointer to within the device tree's string block, not a new copy of the name).
returns: pointer to the property's value if lenp is non-NULL, *lenp contains the length of the property value (>=0) if namep is non-NULL *namep contiains a pointer to the property name. NULL, on error if lenp is non-NULL, *lenp contains an error code (<0): -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_PROP tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
References can_assume, fdt_property::data, fdt32_ld_(), fdt_get_property_by_offset_(), fdt_get_string(), fdt_string(), fdt_version, fdt_property::len, fdt_property::nameoff, and NULL.
Referenced by fdt_check_full(), overlay_apply_node(), overlay_fixup_phandle(), overlay_symbol_update(), and overlay_update_local_node_references().
{
    const struct fdt_property *prop;
    prop = fdt_get_property_by_offset_(fdt, offset, lenp);
    if (!prop)
        return NULL;
    if (namep) {
        const char *name;
        int namelen;
        if (!can_assume(VALID_INPUT)) {
            name = fdt_get_string(fdt, fdt32_ld_(&prop->
      nameoff),
                          &namelen);
            *namep = name;
            if (!name) {
                if (lenp)
                    *lenp = namelen;
                return NULL;
            }
        } else {
            *namep = fdt_string(fdt, fdt32_ld_(&prop->nameoff));
        }
    }
    /* Handle realignment */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10 &&
        (offset + sizeof(*prop)) % 8 && fdt32_ld_(&prop->len) >= 8)
        return prop->data + 4;
    return prop->data;
}
const void* fdt_getprop_namelen (const void * fdt, int nodeoffset, const char * name, int namelen, int * lenp)
References can_assume, fdt_property::data, fdt32_ld_(), fdt_get_property_namelen_(), fdt_version, fdt_property::len, and NULL.
Referenced by fdt_getprop(), fdt_getprop_namelen_w(), and fdt_path_getprop_namelen().
{
    int poffset;
    const struct fdt_property *prop;
    prop = fdt_get_property_namelen_(fdt, nodeoffset, name, namelen, lenp,
                     &poffset);
    if (!prop)
        return NULL;
    /* Handle realignment */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10 &&
        (poffset + sizeof(*prop)) % 8 && fdt32_ld_(&prop->len) >= 8)
        return prop->data + 4;
    return prop->data;
}
static void* fdt_getprop_namelen_w (void * fdt, int nodeoffset, const char * name, int namelen, int * lenp) [inline], [static]
References fdt_getprop_namelen().
Referenced by fdt_setprop_inplace_namelen_partial().
{
    return (void *)(uintptr_t)fdt_getprop_namelen(fdt, nodeoffset, name,
                              namelen, lenp);
}
static void* fdt_getprop_w (void * fdt, int nodeoffset, const char * name, int * lenp) [inline], [static]
References fdt_getprop().
{
    return (void *)(uintptr_t)fdt_getprop(fdt, nodeoffset, name, lenp);
}
size_t fdt_header_size (const void * fdt)
fdt_header_size - return the size of the tree's header : pointer to a flattened device tree
Return: size of DTB header in bytes
References can_assume, fdt_header_size_(), FDT_V17_SIZE, and fdt_version.
Referenced by fdt_check_full(), and fdt_check_header().
{
    return can_assume(LATEST) ? FDT_V17_SIZE :
        fdt_header_size_(fdt_version(fdt));
}
size_t fdt_header_size_ (uint32_t version)
fdt_header_size_ - internal function to get header size from a version number
Version
: devicetree version number
Return: size of DTB header in bytes
References FDT_V16_SIZE, FDT_V17_SIZE, FDT_V1_SIZE, FDT_V2_SIZE, and FDT_V3_SIZE.
Referenced by fdt_header_size().
{
    if (version <= 1)
        return FDT_V1_SIZE;
    else if (version <= 2)
        return FDT_V2_SIZE;
    else if (version <= 3)
        return FDT_V3_SIZE;
    else if (version <= 16)
        return FDT_V16_SIZE;
    else
        return FDT_V17_SIZE;
}
int fdt_move (const void * fdt, void * buf, int bufsize)
fdt_move - move a device tree around in memory : pointer to the device tree to move : pointer to memory where the device is to be moved : size of the memory space at buf
fdt_move() relocates, if possible, the device tree blob located at fdt to the buffer at buf of size bufsize. The buffer may overlap with the existing device tree blob at fdt. Therefore, fdt_move(fdt, fdt, fdt_totalsize(fdt)) should always succeed.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient to contain the device tree -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, standard meanings
References can_assume, FDT_ERR_NOSPACE, FDT_RO_PROBE, fdt_totalsize, and memmove().
Referenced by fdt_open_into().
{
    if (!can_assume(VALID_INPUT) && bufsize < 0)
        return -FDT_ERR_NOSPACE;
    FDT_RO_PROBE(fdt);
    if (fdt_totalsize(fdt) > (unsigned int)bufsize)
        return -FDT_ERR_NOSPACE;
    memmove(buf, fdt, fdt_totalsize(fdt));
    return 0;
}
int fdt_next_node (const void * fdt, int offset, int * depth)
References FDT_BEGIN_NODE, fdt_check_node_offset_(), FDT_END, FDT_END_NODE, FDT_ERR_NOTFOUND, FDT_ERR_TRUNCATED, fdt_next_tag(), FDT_NOP, FDT_PROP, and fdt_property::tag.
Referenced by fdt_find_max_phandle(), fdt_first_subnode(), fdt_get_path(), fdt_next_subnode(), fdt_node_end_offset_(), fdt_node_offset_by_compatible(), fdt_node_offset_by_phandle(), fdt_node_offset_by_prop_value(), fdt_subnode_offset_namelen(), and fdt_supernode_atdepth_offset().
{
    int nextoffset = 0;
    uint32_t tag;
    if (offset >= 0)
        if ((nextoffset = fdt_check_node_offset_(fdt, offset)) < 0)
            return nextoffset;
    do {
        offset = nextoffset;
        tag = fdt_next_tag(fdt, offset, &nextoffset);
        switch (tag) {
        case FDT_PROP:
        case FDT_NOP:
            break;
        case FDT_BEGIN_NODE:
            if (depth)
                (*depth)++;
            break;
        case FDT_END_NODE:
            if (depth && ((--(*depth)) < 0))
                return nextoffset;
            break;
        case FDT_END:
            if ((nextoffset >= 0)
                || ((nextoffset == -FDT_ERR_TRUNCATED) && !depth))
                return -FDT_ERR_NOTFOUND;
            else
                return nextoffset;
        }
    } while (tag != FDT_BEGIN_NODE);
    return offset;
}
int fdt_next_property_offset (const void * fdt, int offset)
fdt_next_property_offset - step through a node's properties : pointer to the device tree blob : structure block offset of a property
fdt_next_property_offset() finds the property immediately after the one at the given structure block offset. This will be a property of the same node as the given property.
returns: structure block offset of the next property (>=0), on success -FDT_ERR_NOTFOUND, if the given property is the last in its node -FDT_ERR_BADOFFSET, if nodeoffset did not point to an FDT_PROP tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings.
References fdt_check_prop_offset_(), and nextprop_().
Referenced by fdt_get_property_namelen_().
{
    if ((offset = fdt_check_prop_offset_(fdt, offset)) < 0)
        return offset;
    return nextprop_(fdt, offset);
}
int fdt_next_subnode (const void * fdt, int offset)
fdt_next_subnode() - get offset of next direct subnode : FDT blob : Offset of previous subnode
After first calling fdt_first_subnode(), call this function repeatedly to get direct subnodes of a parent node.
Return: offset of next subnode, or -FDT_ERR_NOTFOUND if there are no more subnodes
References FDT_ERR_NOTFOUND, and fdt_next_node().
{
    int depth = 1;
    /*
     * With respect to the parent, the depth of the next subnode will be
     * the same as the last.
     */
    do {
        offset = fdt_next_node(fdt, offset, &depth);
        if (offset < 0 || depth < 1)
            return -FDT_ERR_NOTFOUND;
    } while (depth > 1);
    return offset;
}
uint32_t fdt_next_tag (const void * fdt, int offset, int * nextoffset)
References can_assume, fdt32_to_cpu(), FDT_BEGIN_NODE, FDT_END, FDT_END_NODE, FDT_ERR_BADSTRUCTURE, FDT_ERR_TRUNCATED, FDT_NOP, fdt_offset_ptr(), FDT_PROP, FDT_TAGALIGN, FDT_TAGSIZE, fdt_version, INT_MAX, and fdt_property::tag.
Referenced by fdt_add_subnode_namelen(), fdt_check_full(), fdt_check_node_offset_(), fdt_check_prop_offset_(), fdt_finish(), fdt_next_node(), fdt_open_into(), and nextprop_().
{
    const fdt32_t *tagp, *lenp;
    uint32_t tag, len, sum;
    int offset = startoffset;
    const char *p;
    *nextoffset = -FDT_ERR_TRUNCATED;
    tagp = fdt_offset_ptr(fdt, offset, FDT_TAGSIZE);
    if (!can_assume(VALID_DTB) && !tagp)
        return FDT_END; /* premature end */
    tag = fdt32_to_cpu(*tagp);
    offset += FDT_TAGSIZE;
    *nextoffset = -FDT_ERR_BADSTRUCTURE;
    switch (tag) {
    case FDT_BEGIN_NODE:
        /* skip name */
        do {
            p = fdt_offset_ptr(fdt, offset++, 1);
        } while (p && (*p != '\0'));
        if (!can_assume(VALID_DTB) && !p)
            return FDT_END; /* premature end */
        break;
    case FDT_PROP:
        lenp = fdt_offset_ptr(fdt, offset, sizeof(*lenp));
        if (!can_assume(VALID_DTB) && !lenp)
            return FDT_END; /* premature end */
        len = fdt32_to_cpu(*lenp);
        sum = len + offset;
        if (!can_assume(VALID_DTB) &&
            (INT_MAX <= sum || sum < (uint32_t) offset))
            return FDT_END; /* premature end */
        /* skip-name offset, length and value */
        offset += sizeof(struct fdt_property) - FDT_TAGSIZE + len;
        if (!can_assume(LATEST) &&
            fdt_version(fdt) < 0x10 && len >= 8 &&
            ((offset - len) % 8) != 0)
            offset += 4;
        break;
    case FDT_END:
    case FDT_END_NODE:
    case FDT_NOP:
        break;
    default:
        return FDT_END;
    }
    if (!fdt_offset_ptr(fdt, startoffset, offset - startoffset))
        return FDT_END; /* premature end */
    *nextoffset = FDT_TAGALIGN(offset);
    return tag;
}
int fdt_node_check_compatible (const void * fdt, int nodeoffset, const char * compatible)
fdt_node_check_compatible - check a node's compatible property : pointer to the device tree blob : offset of a tree node : string to match against
fdt_node_check_compatible() returns 0 if the given node contains a property with the given string as one of its elements, it returns non-zero otherwise, or on error.
returns: 0, if the node has a 'compatible' property listing the given string 1, if the node has a 'compatible' property, but it does not list the given string -FDT_ERR_NOTFOUND, if the given node has no 'compatible' property -FDT_ERR_BADOFFSET, if nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References fdt_getprop(), fdt_stringlist_contains(), and fdt_property::len.
Referenced by fdt_node_offset_by_compatible().
{
    const void *prop;
    int len;
    prop = fdt_getprop(fdt, nodeoffset, "compatible", &len);
    if (!prop)
        return len;
    return !fdt_stringlist_contains(prop, len, compatible);
}
int fdt_node_depth (const void * fdt, int nodeoffset)
fdt_node_depth - find the depth of a given node : pointer to the device tree blob : offset of the node whose parent to find
fdt_node_depth() finds the depth of a given node. The root node has depth 0, its immediate subnodes depth 1 and so forth.
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset.
returns: depth of the node at nodeoffset (>=0), on success -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References can_assume, FDT_ERR_INTERNAL, and fdt_supernode_atdepth_offset().
Referenced by fdt_parent_offset().
{
    int nodedepth;
    int err;
    err = fdt_supernode_atdepth_offset(fdt, nodeoffset, 0, &nodedepth);
    if (err)
        return (can_assume(LIBFDT_FLAWLESS) || err < 0) ? err :
            -FDT_ERR_INTERNAL;
    return nodedepth;
}
int fdt_node_offset_by_compatible (const void * fdt, int startoffset, const char * compatible)
fdt_node_offset_by_compatible - find nodes with a given 'compatible' value : pointer to the device tree blob : only find nodes after this offset : 'compatible' string to match against
fdt_node_offset_by_compatible() returns the offset of the first node after startoffset, which has a 'compatible' property which lists the given compatible string; or if startoffset is -1, the very first such node in the tree.
To iterate through all nodes matching the criterion, the following idiom can be used: offset = fdt_node_offset_by_compatible(fdt, -1, compatible); while (offset != -FDT_ERR_NOTFOUND) { // other code here offset = fdt_node_offset_by_compatible(fdt, offset, compatible); }
Note the -1 in the first call to the function, if 0 is used here instead, the function will never locate the root node, even if it matches the criterion.
returns: structure block offset of the located node (>= 0, >startoffset), on success -FDT_ERR_NOTFOUND, no node matching the criterion exists in the tree after startoffset -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References FDT_ERR_NOTFOUND, fdt_next_node(), fdt_node_check_compatible(), FDT_RO_PROBE, and NULL.
Referenced by soc_dma_init(), soc_icu_init(), soc_timer_init(), and soc_tty_init().
{
    int offset, err;
    FDT_RO_PROBE(fdt);
    /* FIXME: The algorithm here is pretty horrible: we scan each
     * property of a node in fdt_node_check_compatible(), then if
     * that didn't find what we want, we scan over them again
     * making our way to the next node. Still it's the easiest to
     * implement approach; performance can come later. */
    for (offset = fdt_next_node(fdt, startoffset, NULL);
         offset >= 0;
         offset = fdt_next_node(fdt, offset, NULL)) {
        err = fdt_node_check_compatible(fdt, offset, compatible);
        if ((err < 0) && (err != -FDT_ERR_NOTFOUND))
            return err;
        else if (err == 0)
            return offset;
    }
    return offset; /* error from fdt_next_node() */
}
int fdt_node_offset_by_phandle (const void * fdt, uint32_t phandle)
fdt_node_offset_by_phandle - find the node with a given phandle : pointer to the device tree blob : phandle value
fdt_node_offset_by_phandle() returns the offset of the node which has the given phandle value. If there is more than one node in the tree with the given phandle (an invalid tree), results are undefined.
returns: structure block offset of the located node (>= 0), on success -FDT_ERR_NOTFOUND, no node with that phandle exists -FDT_ERR_BADPHANDLE, given phandle value was invalid (0 or -1) -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References FDT_ERR_BADPHANDLE, fdt_get_phandle(), fdt_next_node(), FDT_RO_PROBE, and NULL.
Referenced by fdt_overlay_target_offset().
{
    int offset;
    if ((phandle == 0) || (phandle == ~0U))
        return -FDT_ERR_BADPHANDLE;
    FDT_RO_PROBE(fdt);
    /* FIXME: The algorithm here is pretty horrible: we
     * potentially scan each property of a node in
     * fdt_get_phandle(), then if that didn't find what
     * we want, we scan over them again making our way to the next
     * node. Still it's the easiest to implement approach;
     * performance can come later. */
    for (offset = fdt_next_node(fdt, -1, NULL);
         offset >= 0;
         offset = fdt_next_node(fdt, offset, NULL)) {
        if (fdt_get_phandle(fdt, offset) == phandle)
            return offset;
    }
    return offset; /* error from fdt_next_node() */
}
int fdt_node_offset_by_prop_value (const void * fdt, int startoffset, const char * propname, const void * propval, int proplen)
fdt_node_offset_by_prop_value - find nodes with a given property value : pointer to the device tree blob : only find nodes after this offset : property name to check : property value to search for : length of the value in propval
fdt_node_offset_by_prop_value() returns the offset of the first node after startoffset, which has a property named propname whose value is of length proplen and has value equal to propval; or if startoffset is -1, the very first such node in the tree.
To iterate through all nodes matching the criterion, the following idiom can be used: offset = fdt_node_offset_by_prop_value(fdt, -1, propname, propval, proplen); while (offset != -FDT_ERR_NOTFOUND) { // other code here offset = fdt_node_offset_by_prop_value(fdt, offset, propname, propval, proplen); }
Note the -1 in the first call to the function, if 0 is used here instead, the function will never locate the root node, even if it matches the criterion.
returns: structure block offset of the located node (>= 0, >startoffset), on success -FDT_ERR_NOTFOUND, no node matching the criterion exists in the tree after startoffset -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References fdt_getprop(), fdt_next_node(), FDT_RO_PROBE, fdt_property::len, memcmp(), and NULL.
{
    int offset;
    const void *val;
    int len;
    FDT_RO_PROBE(fdt);
    /* FIXME: The algorithm here is pretty horrible: we scan each
     * property of a node in fdt_getprop(), then if that didn't
     * find what we want, we scan over them again making our way
     * to the next node. Still it's the easiest to implement
     * approach; performance can come later. */
    for (offset = fdt_next_node(fdt, startoffset, NULL);
         offset >= 0;
         offset = fdt_next_node(fdt, offset, NULL)) {
        val = fdt_getprop(fdt, offset, propname, &len);
        if (val && (len == proplen)
            && (memcmp(val, propval, len) == 0))
            return offset;
    }
    return offset; /* error from fdt_next_node() */
}
int fdt_nop_node (void * fdt, int nodeoffset)
fdt_nop_node - replace a node (subtree) with nop tags : pointer to the device tree blob : offset of the node to nop
fdt_nop_node() will replace a given node's representation in the blob, including all its subnodes, if any, with FDT_NOP tags, effectively removing it from the tree.
This function will alter only the bytes in the blob which contain the node and its properties and subnodes, and will not alter or move any other part of the tree.
returns: 0, on success -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
References fdt_node_end_offset_(), fdt_nop_region_(), and fdt_offset_ptr_w().
{
    int endoffset;
    endoffset = fdt_node_end_offset_(fdt, nodeoffset);
    if (endoffset < 0)
        return endoffset;
    fdt_nop_region_(fdt_offset_ptr_w(fdt, nodeoffset, 0),
            endoffset - nodeoffset);
    return 0;
}
int fdt_nop_property (void * fdt, int nodeoffset, const char * name)
References fdt_get_property_w(), fdt_nop_region_(), and fdt_property::len.
{
    struct fdt_property *prop;
    int len;
    prop = fdt_get_property_w(fdt, nodeoffset, name, &len);
    if (!prop)
        return len;
    fdt_nop_region_(prop, len + sizeof(*prop));
    return 0;
}
int fdt_num_mem_rsv (const void * fdt)
fdt_num_mem_rsv - retrieve the number of memory reserve map entries : pointer to the device tree blob
Returns the number of entries in the device tree blob's memory reservation map. This does not include the terminating 0,0 entry or any other (0,0) entries reserved for expansion.
returns: the number of entries
References fdt64_ld_(), FDT_ERR_TRUNCATED, fdt_mem_rsv(), NULL, and fdt_reserve_entry::size.
Referenced by fdt_add_mem_rsv(), fdt_check_full(), fdt_del_mem_rsv(), fdt_open_into(), and fdt_pack().
{
    int i;
    const struct fdt_reserve_entry *re;
    for (i = 0; (re = fdt_mem_rsv(fdt, i)) != NULL; i++) {
        if (fdt64_ld_(&re->size) == 0)
            return i;
    }
    return -FDT_ERR_TRUNCATED;
}
const void* fdt_offset_ptr (const void * fdt, int offset, unsigned int checklen)
References can_assume, fdt_off_dt_struct, fdt_offset_ptr_(), fdt_size_dt_struct, fdt_totalsize, fdt_version, and NULL.
Referenced by fdt_next_tag(), and fdt_offset_ptr_w().
{
    unsigned int uoffset = offset;
    unsigned int absoffset = offset + fdt_off_dt_struct(fdt);
    if (offset < 0)
        return NULL;
    if (!can_assume(VALID_INPUT))
        if ((absoffset < uoffset)
            || ((absoffset + len) < absoffset)
            || (absoffset + len) > fdt_totalsize(fdt))
            return NULL;
    if (can_assume(LATEST) || fdt_version(fdt) >= 0x11)
        if (((uoffset + len) < uoffset)
            || ((offset + len) > fdt_size_dt_struct(fdt)))
            return NULL;
    return fdt_offset_ptr_(fdt, offset);
}
static void* fdt_offset_ptr_w (void * fdt, int offset, int checklen) [inline], [static]
References fdt_offset_ptr().
Referenced by fdt_nop_node().
{
    return (void *)(uintptr_t)fdt_offset_ptr(fdt, offset, checklen);
}
int fdt_open_into (const void * fdt, void * buf, int bufsize)
References can_assume, FDT_ALIGN, fdt_blocks_misordered_(), fdt_boot_cpuid_phys, FDT_END, FDT_ERR_BADVERSION, FDT_ERR_NOSPACE, FDT_MAGIC, fdt_move(), fdt_next_tag(), fdt_num_mem_rsv(), fdt_packblocks_(), FDT_RO_PROBE, fdt_size_dt_strings, fdt_size_dt_struct, fdt_totalsize, fdt_version, and memmove().
Referenced by fdt_create_empty_tree().
{
    int err;
    int mem_rsv_size, struct_size;
    int newsize;
    const char *fdtstart = fdt;
    const char *fdtend = fdtstart + fdt_totalsize(fdt);
    char *tmp;
    FDT_RO_PROBE(fdt);
    mem_rsv_size = (fdt_num_mem_rsv(fdt)+1)
        * sizeof(struct fdt_reserve_entry);
    if (can_assume(LATEST) || fdt_version(fdt) >= 17) {
        struct_size = fdt_size_dt_struct(fdt);
    } else if (fdt_version(fdt) == 16) {
        struct_size = 0;
        while (fdt_next_tag(fdt, struct_size, &struct_size) !=
      FDT_END)
            ;
        if (struct_size < 0)
            return struct_size;
    } else {
        return -FDT_ERR_BADVERSION;
    }
    if (can_assume(LIBFDT_ORDER) ||
        !fdt_blocks_misordered_(fdt, mem_rsv_size, struct_size)) {
        /* no further work necessary */
        err = fdt_move(fdt, buf, bufsize);
        if (err)
            return err;
        fdt_set_version(buf, 17);
        fdt_set_size_dt_struct(buf, struct_size);
        fdt_set_totalsize(buf, bufsize);
        return 0;
    }
    /* Need to reorder */
    newsize = FDT_ALIGN(sizeof(struct fdt_header), 8) + mem_rsv_size
        + struct_size + fdt_size_dt_strings(fdt);
    if (bufsize < newsize)
        return -FDT_ERR_NOSPACE;
    /* First attempt to build converted tree at beginning of buffer */
    tmp = buf;
    /* But if that overlaps with the old tree... */
    if (((tmp + newsize) > fdtstart) && (tmp < fdtend)) {
        /* Try right after the old tree instead */
        tmp = (char *)(uintptr_t)fdtend;
        if ((tmp + newsize) > ((char *)buf + bufsize))
            return -FDT_ERR_NOSPACE;
    }
    fdt_packblocks_(fdt, tmp, mem_rsv_size, struct_size,
            fdt_size_dt_strings(fdt));
    memmove(buf, tmp, newsize);
    fdt_set_magic(buf, FDT_MAGIC);
    fdt_set_totalsize(buf, bufsize);
    fdt_set_version(buf, 17);
    fdt_set_last_comp_version(buf, 16);
    fdt_set_boot_cpuid_phys(buf, fdt_boot_cpuid_phys(fdt));
    return 0;
}
int fdt_overlay_apply (void * fdt, void * fdto)
fdt_overlay_apply - Applies a DT overlay on a base DT : pointer to the base device tree blob : pointer to the device tree overlay blob
fdt_overlay_apply() will apply the given device tree overlay on the given base device tree.
Expect the base device tree to be modified, even if the function returns an error.
returns: 0, on success -FDT_ERR_NOSPACE, there's not enough space in the base device tree -FDT_ERR_NOTFOUND, the overlay points to some inexistant nodes or properties in the base DT -FDT_ERR_BADPHANDLE, -FDT_ERR_BADOVERLAY, -FDT_ERR_NOPHANDLES, -FDT_ERR_INTERNAL, -FDT_ERR_BADLAYOUT, -FDT_ERR_BADMAGIC, -FDT_ERR_BADOFFSET, -FDT_ERR_BADPATH, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADSTATE, -FDT_ERR_TRUNCATED, standard meanings
References fdt_find_max_phandle(), FDT_RO_PROBE, overlay_adjust_local_phandles(), overlay_fixup_phandles(), overlay_merge(), overlay_symbol_update(), and overlay_update_local_references().
{
    uint32_t delta;
    int ret;
    FDT_RO_PROBE(fdt);
    FDT_RO_PROBE(fdto);
    ret = fdt_find_max_phandle(fdt, &delta);
    if (ret)
        goto err;
    ret = overlay_adjust_local_phandles(fdto, delta);
    if (ret)
        goto err;
    ret = overlay_update_local_references(fdto, delta);
    if (ret)
        goto err;
    ret = overlay_fixup_phandles(fdt, fdto);
    if (ret)
        goto err;
    ret = overlay_merge(fdt, fdto);
    if (ret)
        goto err;
    ret = overlay_symbol_update(fdt, fdto);
    if (ret)
        goto err;
    /*
     * The overlay has been damaged, erase its magic.
     */
    fdt_set_magic(fdto, ~0);
    return 0;
err:
    /*
     * The overlay might have been damaged, erase its magic.
     */
    fdt_set_magic(fdto, ~0);
    /*
     * The base device tree might have been damaged, erase its
     * magic.
     */
    fdt_set_magic(fdt, ~0);
    return ret;
}
int fdt_overlay_target_offset (const void * fdt, const void * fdto, int fragment_offset, char const ** pathp)
fdt_overlay_target_offset - retrieves the offset of a fragment's target : Base device tree blob : Device tree overlay blob : node offset of the fragment in the overlay : pointer which receives the path of the target (or NULL)
fdt_overlay_target_offset() retrieves the target offset in the base device tree of a fragment, no matter how the actual targeting is done (through a phandle or a path)
returns: the targeted node offset in the base device tree Negative error code on error
References FDT_ERR_BADOVERLAY, FDT_ERR_BADPHANDLE, FDT_ERR_NOTFOUND, fdt_getprop(), fdt_node_offset_by_phandle(), fdt_path_offset(), NULL, and overlay_get_target_phandle().
Referenced by overlay_merge(), and overlay_symbol_update().
{
    uint32_t phandle;
    const char *path = NULL;
    int path_len = 0, ret;
    /* Try first to do a phandle based lookup */
    phandle = overlay_get_target_phandle(fdto, fragment_offset);
    if (phandle == (uint32_t)-1)
        return -FDT_ERR_BADPHANDLE;
    /* no phandle, try path */
    if (!phandle) {
        /* And then a path based lookup */
        path = fdt_getprop(fdto, fragment_offset, "target-path", &path_len);
        if (path)
            ret = fdt_path_offset(fdt, path);
        else
            ret = path_len;
    } else
        ret = fdt_node_offset_by_phandle(fdt, phandle);
    /*
    * If we haven't found either a target or a
    * target-path property in a node that contains a
    * __overlay__ subnode (we wouldn't be called
    * otherwise), consider it a improperly written
    * overlay
    */
    if (ret < 0 && path_len == -FDT_ERR_NOTFOUND)
        ret = -FDT_ERR_BADOVERLAY;
    /* return on error */
    if (ret < 0)
        return ret;
    /* return pointer to path (if available) */
    if (pathp)
        *pathp = path ? path : NULL;
    return ret;
}
int fdt_pack (void * fdt)
References fdt_data_size_(), fdt_num_mem_rsv(), fdt_packblocks_(), FDT_RW_PROBE, fdt_size_dt_strings, and fdt_size_dt_struct.
{
    int mem_rsv_size;
    FDT_RW_PROBE(fdt);
    mem_rsv_size = (fdt_num_mem_rsv(fdt)+1)
        * sizeof(struct fdt_reserve_entry);
    fdt_packblocks_(fdt, fdt, mem_rsv_size, fdt_size_dt_struct(fdt),
            fdt_size_dt_strings(fdt));
    fdt_set_totalsize(fdt, fdt_data_size_(fdt));
    return 0;
}
int fdt_parent_offset (const void * fdt, int nodeoffset)
fdt_parent_offset - find the parent of a given node : pointer to the device tree blob : offset of the node whose parent to find
fdt_parent_offset() locates the parent node of a given node (that is, it finds the offset of the node which contains the node at nodeoffset as a subnode).
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset, twice.
returns: structure block offset of the parent of the node at nodeoffset (>=0), on success -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References fdt_node_depth(), fdt_supernode_atdepth_offset(), and NULL.
Referenced by get_path_len().
{
    int nodedepth = fdt_node_depth(fdt, nodeoffset);
    if (nodedepth < 0)
        return nodedepth;
    return fdt_supernode_atdepth_offset(fdt, nodeoffset,
                        nodedepth - 1, NULL);
}
int fdt_path_offset (const void * fdt, const char * path)
fdt_path_offset - find a tree node by its full path : pointer to the device tree blob : full path of the node to locate
fdt_path_offset() finds a node of a given path in the device tree. Each path component may omit the unit address portion, but the results of this are undefined if any such path component is ambiguous (that is if there are multiple nodes at the relevant level matching the given component, differentiated only by unit address).
If the path is not absolute (i.e. does not begin with '/'), the first component is treated as an alias. That is, the property by that name is looked up in the /aliases node, and the value of that property used in place of that first component.
For example, for this small fragment
/ { aliases { i2c2 = // RHS compiles to `/soc@0/i2c@30a40000/eeprom@52` }; soc@0 { foo: i2c@30a40000 { bar: eeprom@52 { }; }; }; };
these would be equivalent:
/soc@0/i2c@30a40000/eeprom@52 i2c2/eeprom@52
returns: structure block offset of the node with the requested path (>=0), on success -FDT_ERR_BADPATH, given path does not begin with '/' and the first component is not a valid alias -FDT_ERR_NOTFOUND, if the requested node does not exist -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings.
References fdt_path_offset_namelen(), and strlen().
Referenced by fdt_overlay_target_offset(), fdt_path_getprop_namelen(), fdt_path_offset_namelen(), overlay_fixup_one_phandle(), overlay_fixup_phandles(), and overlay_update_local_references().
{
    return fdt_path_offset_namelen(fdt, path, strlen(path));
}
int fdt_path_offset_namelen (const void * fdt, const char * path, int namelen)
fdt_path_offset_namelen - find a tree node by its full path : pointer to the device tree blob : full path of the node to locate : number of characters of path to consider
Identical to fdt_path_offset(), but only consider the first namelen characters of path as the path name.
Return: offset of the node or negative libfdt error value otherwise
References FDT_ERR_BADPATH, fdt_get_alias_namelen(), fdt_path_offset(), FDT_RO_PROBE, fdt_subnode_offset_namelen(), and memchr().
Referenced by fdt_path_offset(), and overlay_fixup_one_phandle().
{
    const char *end = path + namelen;
    const char *p = path;
    int offset = 0;
    FDT_RO_PROBE(fdt);
    /* see if we have an alias */
    if (*path != '/') {
        const char *q = memchr(path, '/', end - p);
        if (!q)
            q = end;
        p = fdt_get_alias_namelen(fdt, p, q - p);
        if (!p)
            return -FDT_ERR_BADPATH;
        offset = fdt_path_offset(fdt, p);
        p = q;
    }
    while (p < end) {
        const char *q;
        while (*p == '/') {
            p++;
            if (p == end)
                return offset;
        }
        q = memchr(p, '/', end - p);
        if (! q)
            q = end;
        offset = fdt_subnode_offset_namelen(fdt, offset, p, q-p);
        if (offset < 0)
            return offset;
        p = q;
    }
    return offset;
}
int fdt_property (void * fdt, const char * name, const void * val, int len)
References fdt_property_placeholder(), and memcpy().
Referenced by fdt_property_u32(), and fdt_property_u64().
{
    void *ptr;
    int ret;
    ret = fdt_property_placeholder(fdt, name, len, &ptr);
    if (ret)
        return ret;
    memcpy(ptr, val, len);
    return 0;
}
static int fdt_property_cell (void * fdt, const char * name, uint32_t val) [inline], [static]
References fdt_property_u32().
{
    return fdt_property_u32(fdt, name, val);
}
int fdt_property_placeholder (void * fdt, const char * name, int len, void ** valp)
References cpu_to_fdt32(), fdt_property::data, fdt_add_string_(), FDT_CREATE_FLAG_NO_NAME_DEDUP, fdt_del_last_string_(), FDT_ERR_NOSPACE, fdt_find_add_string_(), fdt_grab_space_(), FDT_PROP, FDT_SW_PROBE_STRUCT, FDT_TAGALIGN, fdt_property::len, fdt_property::nameoff, sw_flags(), and fdt_property::tag.
Referenced by fdt_property().
{
    struct fdt_property *prop;
    int nameoff;
    int allocated;
    FDT_SW_PROBE_STRUCT(fdt);
    /* String de-duplication can be slow, _NO_NAME_DEDUP skips it */
    if (sw_flags(fdt) & FDT_CREATE_FLAG_NO_NAME_DEDUP) {
        allocated = 1;
        nameoff = fdt_add_string_(fdt, name);
    } else {
        nameoff = fdt_find_add_string_(fdt, name, &allocated);
    }
    if (nameoff == 0)
        return -FDT_ERR_NOSPACE;
    prop = fdt_grab_space_(fdt, sizeof(*prop) + FDT_TAGALIGN(
      len));
    if (! prop) {
        if (allocated)
            fdt_del_last_string_(fdt, name);
        return -FDT_ERR_NOSPACE;
    }
    prop->tag = cpu_to_fdt32(FDT_PROP);
    prop->nameoff = cpu_to_fdt32(nameoff);
    prop->len = cpu_to_fdt32(len);
    *valp = prop->data;
    return 0;
}
static int fdt_property_u32 (void * fdt, const char * name, uint32_t val) [inline], [static]
References cpu_to_fdt32(), and fdt_property().
Referenced by fdt_property_cell().
{
    fdt32_t tmp = cpu_to_fdt32(val);
    return fdt_property(fdt, name, &tmp, sizeof(tmp));
}
static int fdt_property_u64 (void * fdt, const char * name, uint64_t val) [inline], [static]
References cpu_to_fdt64(), and fdt_property().
{
    fdt64_t tmp = cpu_to_fdt64(val);
    return fdt_property(fdt, name, &tmp, sizeof(tmp));
}
int fdt_resize (void * fdt, void * buf, int bufsize)
References can_assume, FDT_ERR_INTERNAL, FDT_ERR_NOSPACE, fdt_off_dt_strings, fdt_off_dt_struct, fdt_size_dt_strings, fdt_size_dt_struct, FDT_SW_PROBE, fdt_totalsize, and memmove().
{
    size_t headsize, tailsize;
    char *oldtail, *newtail;
    FDT_SW_PROBE(fdt);
    if (bufsize < 0)
        return -FDT_ERR_NOSPACE;
    headsize = fdt_off_dt_struct(fdt) + fdt_size_dt_struct(fdt);
    tailsize = fdt_size_dt_strings(fdt);
    if (!can_assume(VALID_DTB) &&
        headsize + tailsize > fdt_totalsize(fdt))
        return -FDT_ERR_INTERNAL;
    if ((headsize + tailsize) > (unsigned)bufsize)
        return -FDT_ERR_NOSPACE;
    oldtail = (char *)fdt + fdt_totalsize(fdt) - tailsize;
    newtail = (char *)buf + bufsize - tailsize;
    /* Two cases to avoid clobbering data if the old and new
     * buffers partially overlap */
    if (buf <= fdt) {
        memmove(buf, fdt, headsize);
        memmove(newtail, oldtail, tailsize);
    } else {
        memmove(newtail, oldtail, tailsize);
        memmove(buf, fdt, headsize);
    }
    fdt_set_totalsize(buf, bufsize);
    if (fdt_off_dt_strings(buf))
        fdt_set_off_dt_strings(buf, bufsize);
    return 0;
}
fdt_set_hdr_ (magic)
fdt_set_hdr_ (totalsize)
fdt_set_hdr_ (off_dt_struct)
fdt_set_hdr_ (off_dt_strings)
fdt_set_hdr_ (off_mem_rsvmap)
fdt_set_hdr_ (version)
fdt_set_hdr_ (last_comp_version)
fdt_set_hdr_ (boot_cpuid_phys)
fdt_set_hdr_ (size_dt_strings)
fdt_set_hdr_ (size_dt_struct)
int fdt_set_name (void * fdt, int nodeoffset, const char * name)
References fdt_get_name(), FDT_RW_PROBE, fdt_splice_struct_(), FDT_TAGALIGN, memcpy(), and strlen().
{
    char *namep;
    int oldlen, newlen;
    int err;
    FDT_RW_PROBE(fdt);
    namep = (char *)(uintptr_t)fdt_get_name(fdt, nodeoffset, &oldlen);
    if (!namep)
        return oldlen;
    newlen = strlen(name);
    err = fdt_splice_struct_(fdt, namep, FDT_TAGALIGN(oldlen+1),
                 FDT_TAGALIGN(newlen+1));
    if (err)
        return err;
    memcpy(namep, name, newlen+1);
    return 0;
}
int fdt_setprop (void * fdt, int nodeoffset, const char * name, const void * val, int len)
References fdt_setprop_placeholder(), and memcpy().
Referenced by fdt_setprop_u32(), fdt_setprop_u64(), and overlay_apply_node().
{
    void *prop_data;
    int err;
    err = fdt_setprop_placeholder(fdt, nodeoffset, name,
      len, &prop_data);
    if (err)
        return err;
    if (len)
        memcpy(prop_data, val, len);
    return 0;
}
static int fdt_setprop_cell (void * fdt, int nodeoffset, const char * name, uint32_t val) [inline], [static]
References fdt_setprop_u32().
{
    return fdt_setprop_u32(fdt, nodeoffset, name, val);
}
int fdt_setprop_inplace (void * fdt, int nodeoffset, const char * name, const void * val, int len)
References FDT_ERR_NOSPACE, fdt_getprop(), fdt_setprop_inplace_namelen_partial(), and strlen().
Referenced by fdt_setprop_inplace_u32(), and fdt_setprop_inplace_u64().
{
    const void *propval;
    int proplen;
    propval = fdt_getprop(fdt, nodeoffset, name, &proplen);
    if (!propval)
        return proplen;
    if (proplen != len)
        return -FDT_ERR_NOSPACE;
    return fdt_setprop_inplace_namelen_partial(fdt, nodeoffset, name,
                           strlen(name), 0,
                           val, len);
}
static int fdt_setprop_inplace_cell (void * fdt, int nodeoffset, const char * name, uint32_t val) [inline], [static]
References fdt_setprop_inplace_u32().
{
    return fdt_setprop_inplace_u32(fdt, nodeoffset, name, val);
}
int fdt_setprop_inplace_namelen_partial (void * fdt, int nodeoffset, const char * name, int namelen, uint32_t idx, const void * val, int len)
References FDT_ERR_NOSPACE, fdt_getprop_namelen_w(), and memcpy().
Referenced by fdt_setprop_inplace(), overlay_fixup_one_phandle(), and overlay_update_local_node_references().
{
    void *propval;
    int proplen;
    propval = fdt_getprop_namelen_w(fdt, nodeoffset, name, namelen,
                    &proplen);
    if (!propval)
        return proplen;
    if ((unsigned)proplen < (len + idx))
        return -FDT_ERR_NOSPACE;
    memcpy((char *)propval + idx, val, len);
    return 0;
}
static int fdt_setprop_inplace_u32 (void * fdt, int nodeoffset, const char * name, uint32_t val) [inline], [static]
References cpu_to_fdt32(), and fdt_setprop_inplace().
Referenced by fdt_setprop_inplace_cell(), and overlay_phandle_add_offset().
{
    fdt32_t tmp = cpu_to_fdt32(val);
    return fdt_setprop_inplace(fdt, nodeoffset, name, &tmp, sizeof(tmp));
}
static int fdt_setprop_inplace_u64 (void * fdt, int nodeoffset, const char * name, uint64_t val) [inline], [static]
References cpu_to_fdt64(), and fdt_setprop_inplace().
{
    fdt64_t tmp = cpu_to_fdt64(val);
    return fdt_setprop_inplace(fdt, nodeoffset, name, &tmp, sizeof(tmp));
}
int fdt_setprop_placeholder (void * fdt, int nodeoffset, const char * name, int len, void ** prop_data)
References fdt_property::data, fdt_add_property_(), FDT_ERR_NOTFOUND, fdt_resize_property_(), and FDT_RW_PROBE.
Referenced by fdt_setprop(), and overlay_symbol_update().
{
    struct fdt_property *prop;
    int err;
    FDT_RW_PROBE(fdt);
    err = fdt_resize_property_(fdt, nodeoffset, name, len, &prop);
    if (err == -FDT_ERR_NOTFOUND)
        err = fdt_add_property_(fdt, nodeoffset, name, len, &prop);
    if (err)
        return err;
    *prop_data = prop->data;
    return 0;
}
static int fdt_setprop_u32 (void * fdt, int nodeoffset, const char * name, uint32_t val) [inline], [static]
References cpu_to_fdt32(), and fdt_setprop().
Referenced by fdt_setprop_cell().
{
    fdt32_t tmp = cpu_to_fdt32(val);
    return fdt_setprop(fdt, nodeoffset, name, &tmp, sizeof(tmp));
}
static int fdt_setprop_u64 (void * fdt, int nodeoffset, const char * name, uint64_t val) [inline], [static]
References cpu_to_fdt64(), and fdt_setprop().
{
    fdt64_t tmp = cpu_to_fdt64(val);
    return fdt_setprop(fdt, nodeoffset, name, &tmp, sizeof(tmp));
}
int fdt_size_cells (const void * fdt, int nodeoffset)
fdt_size_cells - retrieve address range size for a bus represented in the tree : pointer to the device tree blob : offset of the node to find the address range size for
When the node has a valid #size-cells property, returns its value.
returns: 0 <= n < FDT_MAX_NCELLS, on success 1, if the node has no #size-cells property -FDT_ERR_BADNCELLS, if the node has a badly formatted or invalid #size-cells property -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
References fdt_cells(), and FDT_ERR_NOTFOUND.
Referenced by fdt_appendprop_addrrange().
{
    int val;
    val = fdt_cells(fdt, nodeoffset, "#size-cells");
    if (val == -FDT_ERR_NOTFOUND)
        return 1;
    return val;
}
const char* fdt_strerror (int errval)
References FDT_ERRTABSIZE, and fdt_errtabent::str.
{
    if (errval > 0)
        return "<valid offset/length>";
    else if (errval == 0)
        return "<no error>";
    else if (-errval < FDT_ERRTABSIZE) {
        const char *s = fdt_errtable[-errval].str;
        if (s)
            return s;
    }
    return "<unknown error>";
}
const char* fdt_string (const void * fdt, int stroffset)
fdt_string - retrieve a string from the strings block of a device tree : pointer to the device tree blob : offset of the string within the strings block (native endian)
fdt_string() retrieves a pointer to a single string from the strings block of the device tree blob at fdt.
returns: a pointer to the string, on success NULL, if stroffset is out of bounds, or doesn't point to a valid string
References fdt_get_string(), and NULL.
Referenced by fdt_getprop_by_offset().
{
    return fdt_get_string(fdt, stroffset, NULL);
}
int fdt_stringlist_contains (const char * strlist, int listlen, const char * str)
fdt_stringlist_contains - check a string list property for a string : Property containing a list of strings to check : Length of property : String to search for
This is a utility function provided for convenience. The list contains one or more strings, each terminated by \0, as is found in a device tree `compatible` property.
Return: 1 if the string is found in the list, 0 not found, or invalid list
References fdt_property::len, memchr(), memcmp(), and strlen().
Referenced by fdt_node_check_compatible().
{
    int len = strlen(str);
    const char *p;
    while (listlen >= len) {
        if (memcmp(str, strlist, len+1) == 0)
            return 1;
        p = memchr(strlist, '\0', listlen);
        if (!p)
            return 0; /* malformed strlist.. */
        listlen -= (p-strlist) + 1;
        strlist = p + 1;
    }
    return 0;
}
int fdt_stringlist_count (const void * fdt, int nodeoffset, const char * property)
References FDT_ERR_BADVALUE, fdt_getprop(), and strnlen().
{
    const char *list, *end;
    int length, count = 0;
    list = fdt_getprop(fdt, nodeoffset, property, &length);
    if (!list)
        return length;
    end = list + length;
    while (list < end) {
        length = strnlen(list, end - list) + 1;
        /* Abort if the last string isn't properly NUL-terminated. */
        if (list + length > end)
            return -FDT_ERR_BADVALUE;
        list += length;
        count++;
    }
    return count;
}
const char* fdt_stringlist_get (const void * fdt, int nodeoffset, const char * property, int index, int * lenp)
References FDT_ERR_BADVALUE, FDT_ERR_NOTFOUND, fdt_getprop(), NULL, and strnlen().
{
    const char *list, *end;
    int length;
    list = fdt_getprop(fdt, nodeoffset, property, &length);
    if (!list) {
        if (lenp)
            *lenp = length;
        return NULL;
    }
    end = list + length;
    while (list < end) {
        length = strnlen(list, end - list) + 1;
        /* Abort if the last string isn't properly NUL-terminated. */
        if (list + length > end) {
            if (lenp)
                *lenp = -FDT_ERR_BADVALUE;
            return NULL;
        }
        if (idx == 0) {
            if (lenp)
                *lenp = length - 1;
            return list;
        }
        list += length;
        idx--;
    }
    if (lenp)
        *lenp = -FDT_ERR_NOTFOUND;
    return NULL;
}
int fdt_stringlist_search (const void * fdt, int nodeoffset, const char * property, const char * string)
References FDT_ERR_BADVALUE, FDT_ERR_NOTFOUND, fdt_getprop(), fdt_property::len, memcmp(), strlen(), and strnlen().
{
    int length, len, idx = 0;
    const char *list, *end;
    list = fdt_getprop(fdt, nodeoffset, property, &length);
    if (!list)
        return length;
    len = strlen(string) + 1;
    end = list + length;
    while (list < end) {
        length = strnlen(list, end - list) + 1;
        /* Abort if the last string isn't properly NUL-terminated. */
        if (list + length > end)
            return -FDT_ERR_BADVALUE;
        if (length == len && memcmp(list, string, length) == 0)
            return idx;
        list += length;
        idx++;
    }
    return -FDT_ERR_NOTFOUND;
}
int fdt_subnode_offset (const void * fdt, int parentoffset, const char * name)
References fdt_subnode_offset_namelen(), and strlen().
Referenced by overlay_apply_node(), overlay_merge(), overlay_symbol_update(), and overlay_update_local_node_references().
{
    return fdt_subnode_offset_namelen(fdt, parentoffset, name,
      strlen(name));
}
int fdt_subnode_offset_namelen (const void * fdt, int parentoffset, const char * name, int namelen)
References FDT_ERR_NOTFOUND, fdt_next_node(), fdt_nodename_eq_(), and FDT_RO_PROBE.
Referenced by fdt_add_subnode_namelen(), fdt_path_offset_namelen(), fdt_subnode_offset(), and overlay_symbol_update().
{
    int depth;
    FDT_RO_PROBE(fdt);
    for (depth = 0;
         (offset >= 0) && (depth >= 0);
         offset = fdt_next_node(fdt, offset, &depth))
        if ((depth == 1)
            && fdt_nodename_eq_(fdt, offset, name, namelen))
            return offset;
    if (depth < 0)
        return -FDT_ERR_NOTFOUND;
    return offset; /* error */
}
int fdt_supernode_atdepth_offset (const void * fdt, int nodeoffset, int supernodedepth, int * nodedepth)
fdt_supernode_atdepth_offset - find a specific ancestor of a node : pointer to the device tree blob : offset of the node whose parent to find : depth of the ancestor to find : pointer to an integer variable (will be overwritten) or NULL
fdt_supernode_atdepth_offset() finds an ancestor of the given node at a specific depth from the root (where the root itself has depth 0, its immediate subnodes depth 1 and so forth). So fdt_supernode_atdepth_offset(fdt, nodeoffset, 0, NULL); will always return 0, the offset of the root node. If the node at nodeoffset has depth D, then: fdt_supernode_atdepth_offset(fdt, nodeoffset, D, NULL); will return nodeoffset itself.
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset.
returns: structure block offset of the node at node offset's ancestor of depth supernodedepth (>=0), on success -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_NOTFOUND, supernodedepth was greater than the depth of nodeoffset -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
References can_assume, FDT_ERR_BADOFFSET, FDT_ERR_BADSTRUCTURE, FDT_ERR_INTERNAL, FDT_ERR_NOTFOUND, fdt_next_node(), and FDT_RO_PROBE.
Referenced by fdt_node_depth(), and fdt_parent_offset().
{
    int offset, depth;
    int supernodeoffset = -FDT_ERR_INTERNAL;
    FDT_RO_PROBE(fdt);
    if (supernodedepth < 0)
        return -FDT_ERR_NOTFOUND;
    for (offset = 0, depth = 0;
         (offset >= 0) && (offset <= nodeoffset);
         offset = fdt_next_node(fdt, offset, &depth)) {
        if (depth == supernodedepth)
            supernodeoffset = offset;
        if (offset == nodeoffset) {
            if (nodedepth)
                *nodedepth = depth;
            if (supernodedepth > depth)
                return -FDT_ERR_NOTFOUND;
            else
                return supernodeoffset;
        }
    }
    if (!can_assume(VALID_INPUT)) {
        if ((offset == -FDT_ERR_NOTFOUND) || (offset >= 0))
            return -FDT_ERR_BADOFFSET;
        else if (offset == -FDT_ERR_BADOFFSET)
            return -FDT_ERR_BADSTRUCTURE;
    }
    return offset; /* error from fdt_next_node() */
}