/users/enseig/franck/ko6/src/soft/external/libfdt/libfdt_env.h File Reference
#include <stddef.h>
*
#include <common/cstd.h>
*
Macros
#define FDT_FORCE
#define FDT_BITWISE
#define EXTRACT_BYTE(x, n) ((unsigned long long)((uint8_t *)&x)[n])
#define CPU_TO_FDT16(x) ((EXTRACT_BYTE(x, 0) << 8) | EXTRACT_BYTE(x, 1))
#define CPU_TO_FDT32(x)
#define CPU_TO_FDT64(x)
Typedefs
typedef unsigned char uint8_t
typedef unsigned short uint16_t
typedef unsigned int uint32_t
typedef unsigned long long uint64_t
typedef unsigned long uintptr_t
typedef int int32_t
typedef int bool
typedef uint16_t FDT_BITWISE fdt16_t
typedef uint32_t FDT_BITWISE fdt32_t
typedef uint64_t FDT_BITWISE fdt64_t
Functions
static uint16_t fdt16_to_cpu (fdt16_t x)
static fdt16_t cpu_to_fdt16 (uint16_t x)
static uint32_t fdt32_to_cpu (fdt32_t x)
static fdt32_t cpu_to_fdt32 (uint32_t x)
static uint64_t fdt64_to_cpu (fdt64_t x)
static fdt64_t cpu_to_fdt64 (uint64_t x)
Macro Definition Documentation
#define CPU_TO_FDT16(x) ((EXTRACT_BYTE(x, 0) << 8) | EXTRACT_BYTE(x, 1))
Referenced by cpu_to_fdt16(), and fdt16_to_cpu().
#define CPU_TO_FDT32(x)
Value:
((EXTRACT_BYTE(x, 0) << 24) | (EXTRACT_BYTE(x, 1) << 16) | \
             (EXTRACT_BYTE(x, 2) << 8) | EXTRACT_BYTE(x, 3))
Referenced by cpu_to_fdt32(), and fdt32_to_cpu().
#define CPU_TO_FDT64(x)
Value:
((EXTRACT_BYTE(x, 0) << 56) | (EXTRACT_BYTE(x, 1) << 48) | \
             (EXTRACT_BYTE(x, 2) << 40) | (EXTRACT_BYTE(x, 3) << 32) | \
             (EXTRACT_BYTE(x, 4) << 24) | (EXTRACT_BYTE(x, 5) << 16) | \
             (EXTRACT_BYTE(x, 6) << 8) | EXTRACT_BYTE(x, 7))
Referenced by cpu_to_fdt64(), and fdt64_to_cpu().
#define EXTRACT_BYTE(x, n) ((unsigned long long)((uint8_t *)&x)[n])
#define FDT_BITWISE
#define FDT_FORCE
Referenced by cpu_to_fdt16(), cpu_to_fdt32(), cpu_to_fdt64(), fdt16_to_cpu(), fdt32_to_cpu(), and fdt64_to_cpu().
Typedef Documentation
typedef int bool
typedef uint16_t FDT_BITWISE fdt16_t
typedef uint32_t FDT_BITWISE fdt32_t
typedef uint64_t FDT_BITWISE fdt64_t
typedef int int32_t
typedef unsigned short uint16_t
typedef unsigned int uint32_t
typedef unsigned long long uint64_t
typedef unsigned char uint8_t
typedef unsigned long uintptr_t
Function Documentation
static fdt16_t cpu_to_fdt16 (uint16_t x) [inline], [static]
References CPU_TO_FDT16, and FDT_FORCE.
{
    return (FDT_FORCE fdt16_t)CPU_TO_FDT16(x);
}
static fdt32_t cpu_to_fdt32 (uint32_t x) [inline], [static]
References CPU_TO_FDT32, and FDT_FORCE.
Referenced by fdt_add_property_(), fdt_add_subnode_namelen(), fdt_appendprop(), fdt_appendprop_u32(), fdt_begin_node(), fdt_end_node(), fdt_finish(), fdt_nop_region_(), fdt_property_placeholder(), fdt_property_u32(), fdt_resize_property_(), fdt_setprop_inplace_u32(), fdt_setprop_u32(), overlay_fixup_one_phandle(), and overlay_update_local_node_references().
{
    return (FDT_FORCE fdt32_t)CPU_TO_FDT32(x);
}
static fdt64_t cpu_to_fdt64 (uint64_t x) [inline], [static]
References CPU_TO_FDT64, and FDT_FORCE.
Referenced by fdt_add_mem_rsv(), fdt_add_reservemap_entry(), fdt_appendprop_u64(), fdt_property_u64(), fdt_setprop_inplace_u64(), and fdt_setprop_u64().
{
    return (FDT_FORCE fdt64_t)CPU_TO_FDT64(x);
}
static uint16_t fdt16_to_cpu (fdt16_t x) [inline], [static]
References CPU_TO_FDT16, and FDT_FORCE.
{
    return (FDT_FORCE uint16_t)CPU_TO_FDT16(x);
}
static uint32_t fdt32_to_cpu (fdt32_t x) [inline], [static]
References CPU_TO_FDT32, and FDT_FORCE.
Referenced by fdt32_ld_(), fdt_cells(), fdt_finish(), fdt_next_tag(), get_base_address(), get_irq(), overlay_get_target_phandle(), overlay_phandle_add_offset(), and overlay_update_local_node_references().
{
    return (FDT_FORCE uint32_t)CPU_TO_FDT32(x);
}
static uint64_t fdt64_to_cpu (fdt64_t x) [inline], [static]
References CPU_TO_FDT64, and FDT_FORCE.
Referenced by fdt64_ld_().
{
    return (FDT_FORCE uint64_t)CPU_TO_FDT64(x);
}