/users/enseig/franck/ko6/src/soft/external/libfdt/libfdt_internal.h File Reference
#include <external/libfdt/fdt.h>
*
Macros
#define FDT_ALIGN(x, a) (((x) + (a) - 1) & ~((a) - 1))
#define FDT_TAGALIGN(x) (FDT_ALIGN((x), FDT_TAGSIZE))
#define FDT_RO_PROBE(fdt)
#define FDT_SW_MAGIC (~FDT_MAGIC)
#define FDT_ASSUME_MASK 0
#define can_assume(_assume) can_assume_(ASSUME_ ## _assume)
Enumerations
enum {
*
ASSUME_PERFECT = 0xff,
ASSUME_VALID_DTB = 1 << 0,
ASSUME_VALID_INPUT = 1 << 1,
ASSUME_LATEST = 1 << 2,
*
ASSUME_NO_ROLLBACK = 1 << 3,
ASSUME_LIBFDT_ORDER = 1 << 4,
ASSUME_LIBFDT_FLAWLESS = 1 << 5
 }
Functions
int32_t fdt_ro_probe_ (const void *fdt)
int fdt_check_node_offset_ (const void *fdt, int offset)
int fdt_check_prop_offset_ (const void *fdt, int offset)
const char * fdt_find_string_ (const char *strtab, int tabsize, const char *s)
int fdt_node_end_offset_ (void *fdt, int nodeoffset)
static const void * fdt_offset_ptr_ (const void *fdt, int offset)
static void * fdt_offset_ptr_w_ (void *fdt, int offset)
static struct fdt_reserve_entry * fdt_mem_rsv_ (const void *fdt, int n)
static struct fdt_reserve_entry * fdt_mem_rsv_w_ (void *fdt, int n)
static uint32_t fdt32_ld_ (const fdt32_t *p)
static uint64_t fdt64_ld_ (const fdt64_t *p)
static bool can_assume_ (int mask)
Macro Definition Documentation
#define can_assume(_assume) can_assume_(ASSUME_ ## _assume)
helper macros for checking assumptions
Referenced by fdt_add_property_(), fdt_add_subnode_namelen(), fdt_check_header(), fdt_check_node_offset_(), fdt_check_prop_offset_(), fdt_find_add_string_(), fdt_get_mem_rsv(), fdt_get_name(), fdt_get_property_by_offset(), fdt_get_property_by_offset_(), fdt_get_property_namelen(), fdt_get_property_namelen_(), fdt_get_string(), fdt_getprop_by_offset(), fdt_getprop_namelen(), fdt_header_size(), fdt_mem_rsv(), fdt_move(), fdt_next_tag(), fdt_node_depth(), fdt_offset_ptr(), fdt_open_into(), fdt_resize(), fdt_ro_probe_(), fdt_rw_probe_(), fdt_supernode_atdepth_offset(), fdt_sw_probe_(), fdt_sw_probe_memrsv_(), and fdt_sw_probe_struct_().
#define FDT_ALIGN(x, a) (((x) + (a) - 1) & ~((a) - 1))
Referenced by fdt_blocks_misordered_(), fdt_create_with_flags(), fdt_open_into(), and fdt_packblocks_().
#define FDT_ASSUME_MASK 0
Referenced by can_assume_().
#define FDT_RO_PROBE(fdt)
Value:
{ \
        int32_t totalsize_; \
        if ((totalsize_ = fdt_ro_probe_(fdt)) < 0) \
            return totalsize_; \
    }
Referenced by fdt_get_mem_rsv(), fdt_get_path(), fdt_move(), fdt_node_offset_by_compatible(), fdt_node_offset_by_phandle(), fdt_node_offset_by_prop_value(), fdt_open_into(), fdt_overlay_apply(), fdt_path_offset_namelen(), fdt_rw_probe_(), fdt_subnode_offset_namelen(), fdt_supernode_atdepth_offset(), and get_path_len().
#define FDT_SW_MAGIC (~FDT_MAGIC)
Referenced by fdt_create_with_flags(), fdt_get_string(), fdt_ro_probe_(), and fdt_sw_probe_().
#define FDT_TAGALIGN(x) (FDT_ALIGN((x), FDT_TAGSIZE))
Referenced by fdt_add_property_(), fdt_add_subnode_namelen(), fdt_appendprop(), fdt_begin_node(), fdt_delprop(), fdt_next_tag(), fdt_property_placeholder(), fdt_resize_property_(), and fdt_set_name().
Enumeration Type Documentation
anonymous enum
Enumerator
ASSUME_PERFECT
ASSUME_VALID_DTB
ASSUME_VALID_INPUT
ASSUME_LATEST
ASSUME_NO_ROLLBACK
ASSUME_LIBFDT_ORDER
ASSUME_LIBFDT_FLAWLESS
     {
    /*
     * This does essentially no checks. Only the latest device-tree
     * version is correctly handled. Inconsistencies or errors in the device
     * tree may cause undefined behaviour or crashes. Invalid parameters
     * passed to libfdt may do the same.
     *
     * If an error occurs when modifying the tree it may leave the tree in
     * an intermediate (but valid) state. As an example, adding a property
     * where there is insufficient space may result in the property name
     * being added to the string table even though the property itself is
     * not added to the struct section.
     *
     * Only use this if you have a fully validated device tree with
     * the latest supported version and wish to minimise code size.
     */
    ASSUME_PERFECT = 0xff,
    /*
     * This assumes that the device tree is sane. i.e. header metadata
     * and basic hierarchy are correct.
     *
     * With this assumption enabled, normal device trees produced by libfdt
     * and the compiler should be handled safely. Malicious device trees and
     * complete garbage may cause libfdt to behave badly or crash. Truncated
     * device trees (e.g. those only partially loaded) can also cause
     * problems.
     *
     * Note: Only checks that relate exclusively to the device tree itself
     * (not the parameters passed to libfdt) are disabled by this
     * assumption. This includes checking headers, tags and the like.
     */
    ASSUME_VALID_DTB = 1 << 0,
    /*
     * This builds on ASSUME_VALID_DTB and further assumes that libfdt
     * functions are called with valid parameters, i.e. not trigger
     * FDT_ERR_BADOFFSET or offsets that are out of bounds. It disables any
     * extensive checking of parameters and the device tree, making various
     * assumptions about correctness.
     *
     * It doesn't make sense to enable this assumption unless
     * ASSUME_VALID_DTB is also enabled.
     */
    ASSUME_VALID_INPUT = 1 << 1,
    /*
     * This disables checks for device-tree version and removes all code
     * which handles older versions.
     *
     * Only enable this if you know you have a device tree with the latest
     * version.
     */
    ASSUME_LATEST = 1 << 2,
    /*
     * This assumes that it is OK for a failed addition to the device tree,
     * due to lack of space or some other problem, to skip any rollback
     * steps (such as dropping the property name from the string table).
     * This is safe to enable in most circumstances, even though it may
     * leave the tree in a sub-optimal state.
     */
    ASSUME_NO_ROLLBACK = 1 << 3,
    /*
     * This assumes that the device tree components appear in a 'convenient'
     * order, i.e. the memory reservation block first, then the structure
     * block and finally the string block.
     *
     * This order is not specified by the device-tree specification,
     * but is expected by libfdt. The device-tree compiler always created
     * device trees with this order.
     *
     * This assumption disables a check in fdt_open_into() and removes the
     * ability to fix the problem there. This is safe if you know that the
     * device tree is correctly ordered. See fdt_blocks_misordered_().
     */
    ASSUME_LIBFDT_ORDER = 1 << 4,
    /*
     * This assumes that libfdt itself does not have any internal bugs. It
     * drops certain checks that should never be needed unless libfdt has an
     * undiscovered bug.
     *
     * This can generally be considered safe to enable.
     */
    ASSUME_LIBFDT_FLAWLESS = 1 << 5,
};
Function Documentation
static bool can_assume_ (int mask) [inline], [static]
can_assume_() - check if a particular assumption is enabled
: Mask to check (ASSUME_...)
Returns
true if that assumption is enabled, else false
References FDT_ASSUME_MASK.
{
    return FDT_ASSUME_MASK & mask;
}
static uint32_t fdt32_ld_ (const fdt32_t * p) [inline], [static]
References fdt32_to_cpu().
Referenced by fdt_get_phandle(), fdt_get_property_by_offset_(), fdt_get_property_namelen_(), fdt_getprop_by_offset(), and fdt_getprop_namelen().
{
    return fdt32_to_cpu(*p);
}
static uint64_t fdt64_ld_ (const fdt64_t * p) [inline], [static]
References fdt64_to_cpu().
Referenced by fdt_get_mem_rsv(), and fdt_num_mem_rsv().
{
    return fdt64_to_cpu(*p);
}
int fdt_check_node_offset_ (const void * fdt, int offset)
References can_assume, FDT_BEGIN_NODE, FDT_ERR_BADOFFSET, fdt_next_tag(), and FDT_TAGSIZE.
Referenced by fdt_add_property_(), fdt_first_property_offset(), fdt_get_name(), and fdt_next_node().
{
    if (!can_assume(VALID_INPUT)
        && ((offset < 0) || (offset % FDT_TAGSIZE)))
        return -FDT_ERR_BADOFFSET;
    if (fdt_next_tag(fdt, offset, &offset) != FDT_BEGIN_NODE)
        return -FDT_ERR_BADOFFSET;
    return offset;
}
int fdt_check_prop_offset_ (const void * fdt, int offset)
References can_assume, FDT_ERR_BADOFFSET, fdt_next_tag(), FDT_PROP, and FDT_TAGSIZE.
Referenced by fdt_get_property_by_offset_(), and fdt_next_property_offset().
{
    if (!can_assume(VALID_INPUT)
        && ((offset < 0) || (offset % FDT_TAGSIZE)))
        return -FDT_ERR_BADOFFSET;
    if (fdt_next_tag(fdt, offset, &offset) != FDT_PROP)
        return -FDT_ERR_BADOFFSET;
    return offset;
}
const char* fdt_find_string_ (const char * strtab, int tabsize, const char * s)
References fdt_property::len, memcmp(), NULL, and strlen().
Referenced by fdt_find_add_string_().
{
    int len = strlen(s) + 1;
    const char *last = strtab + tabsize - len;
    const char *p;
    for (p = strtab; p <= last; p++)
        if (memcmp(p, s, len) == 0)
            return p;
    return NULL;
}
static struct fdt_reserve_entry* fdt_mem_rsv_ (const void * fdt, int n) [static]
References fdt_off_mem_rsvmap.
Referenced by fdt_mem_rsv(), and fdt_mem_rsv_w_().
{
    const struct fdt_reserve_entry *rsv_table =
        (const struct fdt_reserve_entry *)
        ((const char *)fdt + fdt_off_mem_rsvmap(fdt));
    return rsv_table + n;
}
static struct fdt_reserve_entry* fdt_mem_rsv_w_ (void * fdt, int n) [static]
References fdt_mem_rsv_().
Referenced by fdt_add_mem_rsv(), and fdt_del_mem_rsv().
{
    return (void *)(uintptr_t)fdt_mem_rsv_(fdt, n);
}
int fdt_node_end_offset_ (void * fdt, int nodeoffset)
References fdt_next_node().
Referenced by fdt_del_node(), and fdt_nop_node().
{
    int depth = 0;
    while ((offset >= 0) && (depth >= 0))
        offset = fdt_next_node(fdt, offset, &depth);
    return offset;
}
static const void* fdt_offset_ptr_ (const void * fdt, int offset) [inline], [static]
References fdt_off_dt_struct.
Referenced by fdt_get_name(), fdt_get_property_by_offset_(), fdt_offset_ptr(), and fdt_offset_ptr_w_().
{
    return (const char *)fdt + fdt_off_dt_struct(fdt) + offset;
}
static void* fdt_offset_ptr_w_ (void * fdt, int offset) [inline], [static]
References fdt_offset_ptr_().
Referenced by fdt_add_property_(), fdt_add_subnode_namelen(), fdt_del_node(), fdt_finish(), and fdt_grab_space_().
{
    return (void *)(uintptr_t)fdt_offset_ptr_(fdt, offset);
}
int32_t fdt_ro_probe_ (const void * fdt)
References can_assume, FDT_ERR_ALIGNMENT, FDT_ERR_BADMAGIC, FDT_ERR_BADSTATE, FDT_ERR_BADVERSION, FDT_ERR_TRUNCATED, FDT_FIRST_SUPPORTED_VERSION, fdt_last_comp_version, FDT_LAST_SUPPORTED_VERSION, FDT_MAGIC, fdt_magic, fdt_size_dt_struct, FDT_SW_MAGIC, fdt_totalsize, fdt_version, and INT32_MAX.
Referenced by fdt_get_name(), and fdt_get_string().
{
    uint32_t totalsize = fdt_totalsize(fdt);
    if (can_assume(VALID_DTB))
        return totalsize;
    /* The device tree must be at an 8-byte aligned address */
    if ((uintptr_t)fdt & 7)
        return -FDT_ERR_ALIGNMENT;
    if (fdt_magic(fdt) == FDT_MAGIC) {
        /* Complete tree */
        if (!can_assume(LATEST)) {
            if (fdt_version(fdt) < FDT_FIRST_SUPPORTED_VERSION)
                return -FDT_ERR_BADVERSION;
            if (fdt_last_comp_version(fdt) >
                    FDT_LAST_SUPPORTED_VERSION)
                return -FDT_ERR_BADVERSION;
        }
    } else if (fdt_magic(fdt) == FDT_SW_MAGIC) {
        /* Unfinished sequential-write blob */
        if (!can_assume(VALID_INPUT) && fdt_size_dt_struct(fdt) == 0)
            return -FDT_ERR_BADSTATE;
    } else {
        return -FDT_ERR_BADMAGIC;
    }
    if (totalsize < INT32_MAX)
        return totalsize;
    else
        return -FDT_ERR_TRUNCATED;
}