/users/enseig/franck/ko6/src/soft/common/list.h File Reference
#include <stddef.h>
*
Classes
struct list_s
The 2-pointers structure to embed in the root of a list and in each of its items.
Macros
#define list_next(item) list_first(item)
#define list_prev(item) list_last(item)
#define list_foreach(ROOT, ITEM)
C instruction to iterate through a list of items from first to last. list_foreach will iterate as many times as there are items in the ROOT list. At each iteration, ITEM is defined with the current item: the first, the second, until the last. If you need several foreach() in the same function, you have to create a block (by adding braces): { foreach(root, item){ your instructions } } in order to handle the implicit local variables needed for list_foreach().
#define list_foreach_rev(ROOT, ITEM)
C instruction to iterate through a list of items from last to first. list_foreach will iterate as many times as there are items in the ROOT list. At each iteration, ITEM is defined with the current item: the first, the second, until the last. If you need several foreach() in the same function, you have to create a block (by adding braces): { foreach(root, item){ your instructions } } in order to handle the implicit local variables needed for list_foreach().
#define list_item(ITEM, TYPE, MEMBER) ((TYPE*)((void*)ITEM-offsetof(TYPE,MEMBER)))
Macro to get the address of the container of a list item.
#define list_addnext list_addfirst
#define list_addprev list_addlast
Typedefs
typedef struct list_s list_t
The 2-pointers structure to embed in the root of a list and in each of its items.
Functions
static unsigned list_isempty (list_t *root)
Tests if a list don't have any item.
static unsigned list_isfirst (list_t *root, list_t *item)
Tests if an item is the first item of the list root.
static unsigned list_islast (list_t *root, list_t *item)
Tests if an item is the last item of the list root.
static list_t * list_first (list_t *root)
Give the first item of the list, do not detache it.
static list_t * list_last (list_t *root)
Give the last item of the list, do not detache it.
static void list_init (list_t *root)
Initialize of the list root.
static void list_addfirst (list_t *root, list_t *added_item)
Add a new added item after the current item which is root the most often. then the added item is placed at the beginning of the list list_addfirst and list_addnext are synonymous, you can use either one. depending on the readability of the code.
static void list_addlast (list_t *root, list_t *added_item)
Add a new added item before the current item which is root the most often. then the added item is placed at the end of the list list_addlast and list_addprev are synonymous, you can use either one. depending on the readability of the code.
static list_t * list_unlink (list_t *item)
Unlink (i.e. detach) an item of list.
static list_t * list_getfirst (list_t *root)
Unlink (i.e. detach) the first item of list.
static list_t * list_getlast (list_t *root)
Unlink (i.e. detach) the last item of list.
static void list_replace (list_t *old_item, list_t *new_item)
Replace an old item by a new one, or an old root by a new one. When params are roots, that can be used to move an entire list new_item is not a list before to call list_replace.
static unsigned list_nbobj (list_t *root)
calculate the number of object of a list
static void list_addsort (list_t *root, list_t *added_item, int(*cmp)(list_t *A, list_t *B))
Add a new added item in a sorted list after root element.
Macro Definition Documentation
#define list_addnext list_addfirst
#define list_addprev list_addlast
Referenced by list_addsort().
#define list_foreach(ROOT, ITEM)
Value:
list_t * _NEXT, * ITEM; \
    for(ITEM = (ROOT)->next, _NEXT=(ITEM)->next;\
        (ITEM) != (ROOT); \
        ITEM = _NEXT, _NEXT = _NEXT->next)
C instruction to iterate through a list of items from first to last. list_foreach will iterate as many times as there are items in the ROOT list. At each iteration, ITEM is defined with the current item: the first, the second, until the last. If you need several foreach() in the same function, you have to create a block (by adding braces): { foreach(root, item){ your instructions } } in order to handle the implicit local variables needed for list_foreach().
Parameters
ROOT root of list
ITEM : create a list_t pointer, named _ITEM
Referenced by dev_get(), free_ustack(), kfree(), kmalloc_test(), list_addsort(), list_nbobj(), print_ustack(), and thread_barrier_wait().
#define list_foreach_rev(ROOT, ITEM)
Value:
list_t * _NEXT, * ITEM; \
    for(ITEM = (ROOT)->prev, _NEXT=(ITEM)->prev;\
        (ITEM) != (ROOT); \
        ITEM = _NEXT, _NEXT = _NEXT->prev)
C instruction to iterate through a list of items from last to first. list_foreach will iterate as many times as there are items in the ROOT list. At each iteration, ITEM is defined with the current item: the first, the second, until the last. If you need several foreach() in the same function, you have to create a block (by adding braces): { foreach(root, item){ your instructions } } in order to handle the implicit local variables needed for list_foreach().
Parameters
ROOT root of list
ITEM : create a list_t pointer, named _ITEM
Referenced by dev_next_no().
#define list_item(ITEM, TYPE, MEMBER) ((TYPE*)((void*)ITEM-offsetof(TYPE,MEMBER)))
Macro to get the address of the container of a list item.
Parameters
ITEM : pointer the list_t variable created by foreach()
TYPE C tyoe of the container
MEMBER member name of the list item in the container TYPE
Returns
A pointer to the container
Referenced by dev_get(), dev_next_no(), and thread_item().
#define list_next(item) list_first(item)
#define list_prev(item) list_last(item)
Typedef Documentation
typedef struct list_s list_t
The 2-pointers structure to embed in the root of a list and in each of its items.
Function Documentation
static void list_addfirst (list_t * root, list_t * added_item) [inline], [static]
Add a new added item after the current item which is root the most often. then the added item is placed at the beginning of the list list_addfirst and list_addnext are synonymous, you can use either one. depending on the readability of the code.
Parameters
root is the current item
added_item is the added item
Returns
No return but the list has changed.
References list_s::next, and list_s::prev.
Referenced by kfree(), and list_addlast().
                                                                      {
    added_item->next = root->next;
    added_item->prev = root;
    root->next->prev = added_item;
    root->next = added_item;
}
static void list_addlast (list_t * root, list_t * added_item) [inline], [static]
Add a new added item before the current item which is root the most often. then the added item is placed at the end of the list list_addlast and list_addprev are synonymous, you can use either one. depending on the readability of the code.
Parameters
root the current item
added_item the added item
Returns
No return but the list has changed.
References list_addfirst(), and list_s::prev.
Referenced by dev_alloc(), kmalloc(), kmalloc_test(), list_addsort(), memory_init(), and thread_addlast().
                                                                     {
    list_addfirst(root->prev, added_item);
}
static void list_addsort (list_t * root, list_t * added_item, int(*)(list_t *A, list_t *B) cmp) [inline], [static]
Add a new added item in a sorted list after root element.
Parameters
root is the beginng of the list
added_item is the added item into the sorted list
cmp is a pointer to a function that compares items A and B, it returns (A - B)
Returns
No return but the list has changed, all items are sorted by increasing value
References list_addlast(), list_addprev, and list_foreach.
Referenced by free_ustack().
                                                                                                   {
    list_foreach (root, curr_item) {
        if (cmp (curr_item, added_item)>=0) {
            list_addprev (curr_item, added_item);
            return;
        }
    }
    list_addlast (root, added_item);
}
static list_t* list_first (list_t * root) [inline], [static]
Give the first item of the list, do not detache it.
Parameters
root root of list
Returns
A pointer to the first elenent if there is, NULL if the list is empty
References list_isempty(), list_s::next, and NULL.
                                                  {
    return (list_isempty(root)) ? NULL : root->next;
}
static list_t* list_getfirst (list_t * root) [inline], [static]
Unlink (i.e. detach) the first item of list.
Parameters
root a list root
Returns
The unlinked item.
References list_isempty(), list_unlink(), list_s::next, and NULL.
Referenced by free_ustack(), kmalloc(), kmalloc_test(), and thread_mutex_unlock().
                                                     {
    return (list_isempty(root)) ? NULL : list_unlink (root->
      next);
}
static list_t* list_getlast (list_t * root) [inline], [static]
Unlink (i.e. detach) the last item of list.
Parameters
root a list root
Returns
The unlinked item.
References list_isempty(), list_unlink(), NULL, and list_s::prev.
Referenced by malloc_ustack().
                                                    {
    return (list_isempty(root)) ? NULL : list_unlink (root->
      prev);
}
static void list_init (list_t * root) [inline], [static]
Initialize of the list root.
Parameters
root a list root
References list_s::next, and list_s::prev.
Referenced by kmalloc_test(), list_replace(), memory_init(), thread_barrier_init(), thread_create(), and thread_mutex_init().
                                             {
    root->next = root->prev = root;
}
static unsigned list_isempty (list_t * root) [inline], [static]
Tests if a list don't have any item.
Parameters
root root of list
Returns
true if there is no item, false otherwise
References list_s::next.
Referenced by kmalloc(), list_first(), list_getfirst(), list_getlast(), and list_last().
                                                    {
    return root == root->next;
}
static unsigned list_isfirst (list_t * root, list_t * item) [inline], [static]
Tests if an item is the first item of the list root.
Parameters
root root of list
item an item of the list
Returns
true if elmenent is the first one, false otherwise
References list_s::next.
                                                                   {
    return item == root->next;
}
static unsigned list_islast (list_t * root, list_t * item) [inline], [static]
Tests if an item is the last item of the list root.
Parameters
root root of list
item an item of the list
Returns
true if elmenent is the last one, false otherwise
References list_s::prev.
                                                                   {
    return item == root->prev;
}
static list_t* list_last (list_t * root) [inline], [static]
Give the last item of the list, do not detache it.
Parameters
root root of list
Returns
A pointer to the last elenent if there is, NULL if the list is empty
References list_isempty(), NULL, and list_s::prev.
                                                 {
    return (list_isempty(root)) ? NULL : root->prev;
}
static unsigned list_nbobj (list_t * root) [inline], [static]
calculate the number of object of a list
Parameters
root root of list
Returns
a number or 0 if the list is empty
References list_foreach.
Referenced by kmalloc_print().
                                                  {
    size_t nbobj = 0;
    list_foreach (root, item) nbobj++;
    return nbobj;
}
static void list_replace (list_t * old_item, list_t * new_item) [inline], [static]
Replace an old item by a new one, or an old root by a new one. When params are roots, that can be used to move an entire list new_item is not a list before to call list_replace.
Parameters
old_item a list item to unlink, that can be also a root
new_item a list item to add, that can be also a root
References list_init(), list_s::next, and list_s::prev.
                                                                       {
    old_item->next->prev = old_item->prev->next = new_item ;
    new_item->next = old_item->next;
    new_item->prev = old_item->prev;
    list_init(old_item);
}
static list_t* list_unlink (list_t * item) [inline], [static]
Unlink (i.e. detach) an item of list.
Parameters
item the item to unlink
Returns
The unlinked item (given in param)
References list_s::next, and list_s::prev.
Referenced by dev_free(), kfree(), kmalloc_test(), list_getfirst(), list_getlast(), and thread_barrier_wait().
                                                   {
    item->prev->next = item->next;
    item->next->prev = item->prev;
    return item;
}