/users/enseig/franck/ko6/src/soft/ulib/pthread.c File Reference
#include <libc.h>
*
#include <pthread.h>
*
Functions
static void thread_start (void *(*fun)(void *), void *arg)
pthread_start is the function called by the kernel at the true start of a thread
int pthread_create (pthread_t *thread, pthread_attr_t *attr, void *(*fun)(void *), void *arg)
asks the kernel via a syscall to start a new thread by invoking fun(arg) fun() can stop the thread by calling thread_exit(value) or if it returns a value, it is equivalent to call thread_exit with this value The state of the new thread is TH_STATE_READY.
int pthread_yield (void)
Causes the current thread to give up the CPU in order to give it to another.
void pthread_exit (void *retval)
terminates the current thread and returns retval
void sched_dump (void)
Displays on the console (tty0) all active threads, it is for debugging.
void pthread_join (pthread_t thread, void **retval)
wait for a thread termination
int pthread_mutex_init (pthread_mutex_t *mutex, pthread_mutexattr_t *attr)
creates a new mutex and initializes mutex variable with the new mutex (side effect) it is a mutex with error checking
int pthread_mutex_destroy (pthread_mutex_t *mutex)
destroy the referenced mutex If the mutex is locked the destruction is not done, this is an error
int pthread_mutex_lock (pthread_mutex_t *mutex)
lock the referenced mutex, it is a blocking operation. If the mutex is already locked, the calling thread blocks until the mutex becomes available. If the mutex does not exist or is already locked, this is an error
int pthread_mutex_unlock (pthread_mutex_t *mutex)
unlock the referenced mutex If the mutex does not exist or is not locked or has been locked by another, this is an error that causes exit with error
int pthread_barrier_init (pthread_barrier_t *barrier, pthread_barrierattr_t *attr, size_t count)
creates or initialize a barrier depending the value of barrier parameter
int pthread_barrier_destroy (pthread_barrier_t *barrier)
destroy the referenced barrier If a thread is waiting at the barrier, then the destruction is not done, it is an error
int pthread_barrier_wait (pthread_barrier_t *barrier)
wait to the referenced barrier, it is a blocking operation for all thread but the last the last arrived thread doesn't wait and notifies the other threads which becomes READY
Function Documentation
int pthread_barrier_destroy (pthread_barrier_t * barrier)
destroy the referenced barrier If a thread is waiting at the barrier, then the destruction is not done, it is an error
Parameters
barrier a pointer referencing a barrier
Returns
SUCCESS if it all goes fine or EINVAL wrong argument EBUSY The implementation has detected an attempt to destroy a barrier while it is in use (for example, while being used in a thread_barrier_wait() call) by another thread.
References SYSCALL_BARRIER_DESTROY, and syscall_fct.
{
    return syscall_fct ((int)barrier, 0, 0, 0,
      SYSCALL_BARRIER_DESTROY);
}
int pthread_barrier_init (pthread_barrier_t * barrier, pthread_barrierattr_t * attr, size_t count)
creates or initialize a barrier depending the value of barrier parameter
Parameters
barrier a pointer referencing the barrier, there are two cases 1) if *barrier == NULL then allocate a new barrier, then initialize count 2) if *barrier != NULL it the barrier already exists, just initialize count
attr a pointer to the attribute of the new barrier (NULL for default)
count number of expected threads for this barrier
Returns
SUCCESS if it all goes fine or EINVAL The value specified by count is equal to zero. ENOMEM Insufficient memory exists to initialize the barrier EBUSY The implementation has detected an attempt to reinitialize a barrier while it is in use (for example, while being used in a thread_barrier_wait() call) by another thread.
References SYSCALL_BARRIER_INIT, and syscall_fct.
Referenced by main().
{
    return syscall_fct ((int)barrier, (int) count, (int) attr, 0,
      SYSCALL_BARRIER_INIT);
}
int pthread_barrier_wait (pthread_barrier_t * barrier)
wait to the referenced barrier, it is a blocking operation for all thread but the last the last arrived thread doesn't wait and notifies the other threads which becomes READY
Parameters
barrier a pointer referencing a barrier
Returns
SUCCESS or FEALURE
References SYSCALL_BARRIER_WAIT, and syscall_fct.
{
    return syscall_fct ((int)barrier, 0, 0, 0,
      SYSCALL_BARRIER_WAIT);
}
int pthread_create (pthread_t * thread, pthread_attr_t * attr, void *(*)(void *) fun, void * arg)
asks the kernel via a syscall to start a new thread by invoking fun(arg) fun() can stop the thread by calling thread_exit(value) or if it returns a value, it is equivalent to call thread_exit with this value The state of the new thread is TH_STATE_READY.
Parameters
thread pointer to the thread structure
attr pointer to the thread atribute structure (default if NULL)
fun pointer to the function of the thread
arg the argument given to fun()
References syscall_fct, SYSCALL_THREAD_CREATE, and thread_start().
Referenced by main().
{
    return syscall_fct ((int)thread, (int)fun, (int)arg, (int)
      thread_start, SYSCALL_THREAD_CREATE);
}
void pthread_exit (void * retval)
terminates the current thread and returns retval
Parameters
retval the value can be retrieved by calling the thread_join function of another thread
References syscall_fct, and SYSCALL_THREAD_EXIT.
Referenced by thread_start().
{
    syscall_fct ((int)retval, 0, 0, 0, SYSCALL_THREAD_EXIT);
}
void pthread_join (pthread_t thread, void ** retval)
wait for a thread termination
Parameters
thread expected thread
retval pointer to the return value of the expected thread
References syscall_fct, and SYSCALL_THREAD_JOIN.
Referenced by main().
{
    syscall_fct ((int)thread, (int)retval, 0, 0, SYSCALL_THREAD_JOIN);
}
int pthread_mutex_destroy (pthread_mutex_t * mutex)
destroy the referenced mutex If the mutex is locked the destruction is not done, this is an error
Parameters
mutex a pointer referencing a mutex
Returns
0 on success, 1 on fealure
References syscall_fct, and SYSCALL_MUTEX_DESTROY.
{
    return syscall_fct ((int)mutex, 0, 0, 0, SYSCALL_MUTEX_DESTROY);
}
int pthread_mutex_init (pthread_mutex_t * mutex, pthread_mutexattr_t * attr)
creates a new mutex and initializes mutex variable with the new mutex (side effect) it is a mutex with error checking
Parameters
mutex a pointer referencing the new mutex
attr a pointer to the attribute of the new mutex (NULL for default)
Returns
0 on success, 1 on fealure
References syscall_fct, and SYSCALL_MUTEX_INIT.
{
    return syscall_fct ((int)mutex, 0, 0, 0, SYSCALL_MUTEX_INIT);
}
int pthread_mutex_lock (pthread_mutex_t * mutex)
lock the referenced mutex, it is a blocking operation. If the mutex is already locked, the calling thread blocks until the mutex becomes available. If the mutex does not exist or is already locked, this is an error
Parameters
mutex a pointer referencing a mutex
Returns
0 on success, 1 on fealure
References syscall_fct, and SYSCALL_MUTEX_LOCK.
{
    return syscall_fct ((int)mutex, 0, 0, 0, SYSCALL_MUTEX_LOCK);
}
int pthread_mutex_unlock (pthread_mutex_t * mutex)
unlock the referenced mutex If the mutex does not exist or is not locked or has been locked by another, this is an error that causes exit with error
Parameters
mutex a pointer referencing a mutex
Returns
0 on success, 1 on fealure
References syscall_fct, and SYSCALL_MUTEX_UNLOCK.
{
    return syscall_fct ((int)mutex, 0, 0, 0, SYSCALL_MUTEX_UNLOCK);
}
int pthread_yield (void)
Causes the current thread to give up the CPU in order to give it to another.
References syscall_fct, and SYSCALL_THREAD_YIELD.
{
    return syscall_fct (0, 0, 0, 0, SYSCALL_THREAD_YIELD);
}
void sched_dump (void)
Displays on the console (tty0) all active threads, it is for debugging.
References thread_s::arg, clock, D, errno_mess, thread_s::fun, thread_s::join, kprintf(), thread_s::kstack, thread_s::kstack_b, list_s::next, P, list_s::prev, thread_s::ptls, thread_s::retval, S, thread_s::start, thread_s::state, syscall_fct, SYSCALL_SCHED_DUMP, TH_STATE_DEAD, TH_STATE_READY, TH_STATE_RUNNING, TH_STATE_WAIT, TH_STATE_ZOMBIE, TH_TYPE_KERNEL, TH_TYPE_USER, THREAD_MAX, ThreadCurrentIdx, thread_s::tid, _tls_s::tls_errno, thread_s::type, thread_s::ustack_b, thread_s::ustack_e, W, thread_s::wait, and Y.
{
    syscall_fct (0, 0, 0, 0, SYSCALL_SCHED_DUMP);
}
static void thread_start (void *(*)(void *) fun, void * arg) [static]
pthread_start is the function called by the kernel at the true start of a thread
Parameters
fun is the thread's function (the one defined in the user application)
arg is the thread argument, which will be given to the function fun
References pthread_exit().
Referenced by pthread_create().
{
// urandseed = 1; // initialise the user random seed (present in the tls)
    void * retval = fun (arg); // call the function with its arg (maybe, it will call thread_exit())
    pthread_exit(retval); // otherwise, if fun ends, ask the kernel to exit the thread
}