/users/enseig/franck/ko6/src/soft/uapp/test/main.c File Reference
#include <libc.h>
*
#include <pthread.h>
*
Functions
int main (void)
Function Documentation
int main (void)
References a0, a1, barrier, DELAY, fprintf(), NULL, pthread_barrier_init(), pthread_create(), pthread_join(), t0, t0_fun(), and t1.
{
    unsigned a = 0xdeadbeef;
    unsigned b = 0xcafebabe;
    unsigned char c = 'A';
    const char *d = "Hey! I’m no one’s messenger boy, all right? I’m a delivery boy.";
    fprintf(1, "a=0x%x b=%d c='%c' d=\"%s\"\n",
        a, b, c, d);
    return 0;
}