SRCDIR	= $(ko6)/src/soft/common
INCDIR	= -I. -I$(SRCDIR)
CFLAGS  = -D_HOST_ 
SRC 	= dejavu.c $(SRCDIR)/ht_prob.c	$(SRCDIR)/ctype.c
include ../Makefile.tool
# DEPENDENCIES

/dejavu.o: /dsk/l1/franck/ko6/src/soft/common/ctype.h
/dejavu.o: /dsk/l1/franck/ko6/src/soft/common/ht_prob.h /usr/include/stdlib.h
/dejavu.o: /usr/include/bits/libc-header-start.h /usr/include/features.h
/dejavu.o: /usr/include/features-time64.h /usr/include/bits/wordsize.h
/dejavu.o: /usr/include/bits/timesize.h /usr/include/stdc-predef.h
/dejavu.o: /usr/include/sys/cdefs.h /usr/include/bits/long-double.h
/dejavu.o: /usr/include/gnu/stubs.h /usr/include/bits/waitflags.h
/dejavu.o: /usr/include/bits/waitstatus.h /usr/include/bits/floatn.h
/dejavu.o: /usr/include/bits/floatn-common.h /usr/include/sys/types.h
/dejavu.o: /usr/include/bits/types.h /usr/include/bits/typesizes.h
/dejavu.o: /usr/include/bits/time64.h /usr/include/bits/types/clock_t.h
/dejavu.o: /usr/include/bits/types/clockid_t.h
/dejavu.o: /usr/include/bits/types/time_t.h /usr/include/bits/types/timer_t.h
/dejavu.o: /usr/include/bits/stdint-intn.h /usr/include/endian.h
/dejavu.o: /usr/include/bits/endian.h /usr/include/bits/endianness.h
/dejavu.o: /usr/include/bits/byteswap.h /usr/include/bits/uintn-identity.h
/dejavu.o: /usr/include/sys/select.h /usr/include/bits/select.h
/dejavu.o: /usr/include/bits/types/sigset_t.h
/dejavu.o: /usr/include/bits/types/__sigset_t.h
/dejavu.o: /usr/include/bits/types/struct_timeval.h
/dejavu.o: /usr/include/bits/types/struct_timespec.h
/dejavu.o: /usr/include/bits/pthreadtypes.h
/dejavu.o: /usr/include/bits/thread-shared-types.h
/dejavu.o: /usr/include/bits/pthreadtypes-arch.h
/dejavu.o: /usr/include/bits/struct_mutex.h /usr/include/bits/struct_rwlock.h
/dejavu.o: /usr/include/alloca.h /usr/include/bits/stdlib-float.h
/dejavu.o: /usr/include/stdio.h /usr/include/bits/types/__fpos_t.h
/dejavu.o: /usr/include/bits/types/__mbstate_t.h
/dejavu.o: /usr/include/bits/types/__fpos64_t.h
/dejavu.o: /usr/include/bits/types/__FILE.h /usr/include/bits/types/FILE.h
/dejavu.o: /usr/include/bits/types/struct_FILE.h
/dejavu.o: /usr/include/bits/stdio_lim.h /usr/include/string.h
/dejavu.o: /usr/include/bits/types/locale_t.h
/dejavu.o: /usr/include/bits/types/__locale_t.h /usr/include/strings.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /dsk/l1/franck/ko6/src/soft/common/ht_prob.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/stdlib.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/libc-header-start.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/features.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/features-time64.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/wordsize.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/timesize.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/stdc-predef.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/sys/cdefs.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/long-double.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/gnu/stubs.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/waitflags.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/waitstatus.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/floatn.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/floatn-common.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/sys/types.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/typesizes.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/time64.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/clock_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/clockid_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/time_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/timer_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/stdint-intn.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/endian.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/endian.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/endianness.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/byteswap.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/uintn-identity.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/sys/select.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/select.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/sigset_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/__sigset_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/struct_timeval.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/struct_timespec.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/pthreadtypes.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/thread-shared-types.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/pthreadtypes-arch.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/struct_mutex.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/struct_rwlock.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/alloca.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/stdlib-float.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/stdio.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/__fpos_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/__mbstate_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/__fpos64_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/__FILE.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/FILE.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/struct_FILE.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/stdio_lim.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/string.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/locale_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/bits/types/__locale_t.h
/dsk/l1/franck/ko6/src/soft/common/ht_prob.o: /usr/include/strings.h
