SRC 	= main.c
include ../Makefile.uapp
# DEPENDENCIES

../../../../build/obj/hello/main.o: ../../ulib/libc.h
../../../../build/obj/hello/main.o: ../../common/debug_off.h
../../../../build/obj/hello/main.o: ../../common/debug_on.h
../../../../build/obj/hello/main.o: ../../common/list.h
../../../../build/obj/hello/main.o: ../../common/syscalls.h
../../../../build/obj/hello/main.o: ../../ulib/memory.h
../../../../build/obj/hello/main.o: ../../common/usermem.h
../../../../build/obj/hello/main.o: ../../common/errno.h
../../../../build/obj/hello/main.o: ../../common/esc_code.h
