SRC 	= main.c
include ../Makefile.uapp
# DEPENDENCIES

../../../../build/obj/test/main.o: ../../ulib/libc.h ../../common/debug_off.h
../../../../build/obj/test/main.o: ../../common/debug_on.h
../../../../build/obj/test/main.o: ../../common/cstd.h ../../common/list.h
../../../../build/obj/test/main.o: ../../common/syscalls.h
../../../../build/obj/test/main.o: ../../ulib/memory.h ../../common/usermem.h
../../../../build/obj/test/main.o: ../../common/errno.h
../../../../build/obj/test/main.o: ../../common/esc_code.h
../../../../build/obj/test/main.o: ../../ulib/pthread.h
